# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_2349219654e5d7d2e144f24a376805b0aaa42ff7e6f5d14909d374d351328200
  def self._v_sum_y(input)
    t5 = input["x"] || input[:x]
    arr11 = []
    t5.each_with_index do |x_el6, x_i7|
      acc10 = 0
      x_el6.each_with_index do |y_el8, y_i9|
        acc10 += y_el8
      end
      t4 = acc10
      arr11 << t4
    end
    return arr11
  end
end
