# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_5b3f1fa69196cf9b659e48d120f973c8d8c7e1db3205f6332fb3c76ef30284e8
  def self._v_sum_y(input)
    out = []
    t1 = input["x"] || input[:x]
    t1.each_with_index do |x_el_2, x_i_3|
      acc_4 = 0
      x_el_2.each_with_index do |y_el_5, y_i_6|
        acc_4 += y_el_5
      end
      t7 = acc_4
      out << t7
    end
    out
  end
end
