# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_89360babebc3896b16e46cb4cf2f0f8feb3d6f6428e9bf430575b05328fa27eb
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :v_sum_y then _v_sum_y
    else raise KeyError, "Unknown declaration"
    end
  end

  def _v_sum_y(input = @input)
    out = []
    t1 = input["x"] || input[:x]
    t1.each_with_index do |x_el_2, x_i_3|
      acc_4 = 0
      x_el_2.each_with_index do |y_el_5, y_i_6|
        acc_4 += y_el_5
      end
      t7 = acc_4
      out << t7
    end
    out
  end
end
