# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_0cb193cac7097725954d884c342db7afb7158942e3608106d1d84042f47fb997
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :subtotals then _subtotals
    when :discounted_price then _discounted_price
    when :is_valid_quantity then _is_valid_quantity
    when :expensive_items then _expensive_items
    when :electronics then _electronics
    else raise KeyError, "Unknown declaration"
    end
  end

  def _subtotals(input = @input)
    out = []
    t1 = input["items"] || input[:items]
    t1.each_with_index do |items_el_2, items_i_3|
      t4 = items_el_2["price"] || items_el_2[:price]
      t5 = items_el_2["quantity"] || items_el_2[:quantity]
      t6 = t4 * t5
      out << t6
    end
    out
  end

  def _discounted_price(input = @input)
    out = []
    t7 = input["items"] || input[:items]
    t11 = 0.9
    t7.each_with_index do |items_el_8, items_i_9|
      t10 = items_el_8["price"] || items_el_8[:price]
      t12 = t10 * t11
      out << t12
    end
    out
  end

  def _is_valid_quantity(input = @input)
    out = []
    t13 = input["items"] || input[:items]
    t17 = 0
    t13.each_with_index do |items_el_14, items_i_15|
      t16 = items_el_14["quantity"] || items_el_14[:quantity]
      t18 = t16 > t17
      out << t18
    end
    out
  end

  def _expensive_items(input = @input)
    out = []
    t19 = input["items"] || input[:items]
    t23 = 100.0
    t19.each_with_index do |items_el_20, items_i_21|
      t22 = items_el_20["price"] || items_el_20[:price]
      t24 = t22 > t23
      out << t24
    end
    out
  end

  def _electronics(input = @input)
    out = []
    t25 = input["items"] || input[:items]
    t29 = "electronics"
    t25.each_with_index do |items_el_26, items_i_27|
      t28 = items_el_26["category"] || items_el_26[:category]
      t30 = t28 == t29
      out << t30
    end
    out
  end
end
