# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e4504edf626687333aef4d85adaabe128968741254711318cfd3f4fe5d40cebe
  def self._item_taxes(input)
    out = []
    t1 = input["items"] || input[:items]
    t1.each_with_index do |items_el_2, items_i_3|
      t4 = items_el_2["amount"] || items_el_2[:amount]
      t5 = Kumi::TestSharedSchemas::Tax._tax({"amount" => t4})
      out << t5
    end
    out
  end

  def self._total_tax(input)
    acc_6 = 0.0
    t7 = input["items"] || input[:items]
    t7.each_with_index do |items_el_8, items_i_9|
      t13 = items_el_8["amount"] || items_el_8[:amount]
      t14 = Kumi::TestSharedSchemas::Tax._tax({"amount" => t13})
      acc_6 += t14
    end
    acc_6
  end
end
