# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_640a831e4be1bf73dfb2e5c4cf0f2a484e1595c3f84aa7c58e6bf5d5ef40cd10
  def self._item_taxes(input)
    t7 = input["items"] || input[:items]
    arr12 = []
    t7.each_with_index do |items_el8, items_i9|
      t10 = items_el8["amount"] || items_el8[:amount]
      t11 = 0.15
      t6 = t10 * t11
      arr12 << t6
    end
    return arr12
  end

  def self._total_tax(input)
    t13 = input["items"] || input[:items]
    acc18 = 0
    t13.each_with_index do |items_el14, items_i15|
      t16 = items_el14["amount"] || items_el14[:amount]
      t17 = 0.15
      t12 = t16 * t17
      acc18 += t12
    end
    t6 = acc18
    return t6
  end
end
