# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_c35d17b75791ed5a62bfa3700e066dd16047a18a0bc2de3d0b208a6eb39d86f2
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :item_taxes then _item_taxes
    when :total_tax then _total_tax
    else raise KeyError, "Unknown declaration"
    end
  end

  def _item_taxes(input = @input)
    out = []
    t1 = input["items"] || input[:items]
    t1.each_with_index do |items_el_2, items_i_3|
      t4 = items_el_2["amount"] || items_el_2[:amount]
      t5 = GoldenSchemas::Tax.from({"amount" => t4})._tax
      out << t5
    end
    out
  end

  def _total_tax(input = @input)
    acc_6 = 0.0
    t7 = input["items"] || input[:items]
    t7.each_with_index do |items_el_8, items_i_9|
      t13 = items_el_8["amount"] || items_el_8[:amount]
      t14 = GoldenSchemas::Tax.from({"amount" => t13})._tax
      acc_6 += t14
    end
    acc_6
  end
end
