# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_c879b4eba9136931d92d38445c36560710069d8c7a373b73f661913e044879ef
  def self._result(input)
    t9 = input["vals"] || input[:vals]
    arr18 = []
    t9.each_with_index do |vals_el10, vals_i11|
      t12 = input["vals"] || input[:vals]
      acc17 = 0.0
      t12.each_with_index do |vals__x_el13, vals__x_i14|
        t15 = vals__x_el13["a"] || vals__x_el13[:a]
        t5 = t15
        t16 = vals_el10["a"] || vals_el10[:a]
        t7 = t5 - t16
        acc17 += t7
      end
      t8 = acc17
      arr18 << t8
    end
    return arr18
  end
end
