# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e203de5c68b26fd15aa35a94fe471163e4bd0e57a0f71d65446ee48c0042a122
  def self._result(input)
    t9 = input["vals"] || input[:vals]
    arr18 = []
    t9.each_with_index do |vals_el10, vals_i11|
      t12 = input["vals"] || input[:vals]
      acc17 = 0.0
      t12.each_with_index do |vals__x_el13, vals__x_i14|
        t15 = vals__x_el13["a"] || vals__x_el13[:a]
        t16 = vals_el10["a"] || vals_el10[:a]
        t7 = t15 - t16
        acc17 += t7
      end
      arr18 << acc17
    end
    return arr18
  end
end
