# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
      when :cube then _eval_cube
      when :layer then _eval_layer
      when :row then _eval_row
      when :cell then _eval_cell
      when :cell_over_limit then _eval_cell_over_limit
      when :cell_sum then _eval_cell_sum
      when :count_over_limit then _eval_count_over_limit
      else raise KeyError, "Unknown declaration"
    end
  end

  def _eval_cube
    out = nil
    t1 = @input["cube"]
    out = t1
    out
  end

  def _eval_layer
    out = []
    t2 = @input["cube"]
    t2.each_with_index do |cube_el_3, cube_i_4|
      out << cube_el_3
    end
    out
  end

  def _eval_row
    out = []
    t5 = @input["cube"]
    t5.each_with_index do |cube_el_6, cube_i_7|
      out_1 = []
      cube_el_6.each_with_index do |layer_el_8, layer_i_9|
        out_1 << layer_el_8
      end
      out << out_1
    end
    out
  end

  def _eval_cell
    out = []
    t10 = @input["cube"]
    t10.each_with_index do |cube_el_11, cube_i_12|
      out_1 = []
      cube_el_11.each_with_index do |layer_el_13, layer_i_14|
        out_2 = []
        layer_el_13.each_with_index do |row_el_15, row_i_16|
          out_2 << row_el_15
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def _eval_cell_over_limit
    out = []
    t17 = @input["cube"]
    t17.each_with_index do |cube_el_18, cube_i_19|
      out_1 = []
      cube_el_18.each_with_index do |layer_el_20, layer_i_21|
        out_2 = []
        layer_el_20.each_with_index do |row_el_22, row_i_23|
          t24 = 100
          t25 = __core_gt(row_el_22, t24)
          out_2 << t25
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def _eval_cell_sum
    out = []
    t26 = @input["cube"]
    t26.each_with_index do |cube_el_27, cube_i_28|
      out_1 = []
      cube_el_27.each_with_index do |layer_el_29, layer_i_30|
        acc_31 = 0
        layer_el_29.each_with_index do |row_el_32, row_i_33|
          t55 = 100
          t56 = __core_gt(row_el_32, t55)
          t35 = 0
          t36 = (t56) ? (row_el_32) : (t35)
          acc_31 = __agg_sum(acc_31, t36)
        end
        t37 = acc_31
        out_1 << t37
      end
      out << out_1
    end
    out
  end

  def _eval_count_over_limit
    out = nil
    acc_38 = 0
    t39 = @input["cube"]
    t39.each_with_index do |cube_el_40, cube_i_41|
      acc_42 = 0
      cube_el_40.each_with_index do |layer_el_43, layer_i_44|
        acc_45 = 0
        layer_el_43.each_with_index do |row_el_46, row_i_47|
          t57 = 100
          t58 = __core_gt(row_el_46, t57)
          t49 = 1
          t50 = 0
          t51 = (t58) ? (t49) : (t50)
          acc_45 = __agg_sum(acc_45, t51)
        end
        t52 = acc_45
        acc_42 = __agg_sum(acc_42, t52)
      end
      t53 = acc_42
      acc_38 = __agg_sum(acc_38, t53)
    end
    t54 = acc_38
    out = t54
    out
  end

  private

  def __agg_sum(a,b)
    a + b
  end

  def __core_gt(a, b)
    a > b
  end

end
