# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_9a2111bf14459644776802d1b3dfdabc49a11cfad41193655a27e5b06f29d871
  def self._cube(input)
    input["cube"] || input[:cube]
  end

  def self._layer(input)
    out = []
    t2 = input["cube"] || input[:cube]
    t2.each_with_index do |cube_el_3, cube_i_4|
      out << cube_el_3
    end
    out
  end

  def self._row(input)
    out = []
    t5 = input["cube"] || input[:cube]
    t5.each_with_index do |cube_el_6, cube_i_7|
      out_1 = []
      cube_el_6.each_with_index do |layer_el_8, layer_i_9|
        out_1 << layer_el_8
      end
      out << out_1
    end
    out
  end

  def self._cell(input)
    out = []
    t10 = input["cube"] || input[:cube]
    t10.each_with_index do |cube_el_11, cube_i_12|
      out_1 = []
      cube_el_11.each_with_index do |layer_el_13, layer_i_14|
        out_2 = []
        layer_el_13.each_with_index do |row_el_15, row_i_16|
          out_2 << row_el_15
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def self._cell_over_limit(input)
    out = []
    t17 = input["cube"] || input[:cube]
    t24 = 100
    t17.each_with_index do |cube_el_18, cube_i_19|
      out_1 = []
      cube_el_18.each_with_index do |layer_el_20, layer_i_21|
        out_2 = []
        layer_el_20.each_with_index do |row_el_22, row_i_23|
          t25 = row_el_22 > t24
          out_2 << t25
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def self._cell_sum(input)
    out = []
    t26 = input["cube"] || input[:cube]
    t56 = 100
    t35 = 0
    t26.each_with_index do |cube_el_27, cube_i_28|
      out_1 = []
      cube_el_27.each_with_index do |layer_el_29, layer_i_30|
        acc_31 = 0
        layer_el_29.each_with_index do |row_el_32, row_i_33|
          t57 = row_el_32 > t56
          t36 = t57 ? row_el_32 : t35
          acc_31 += t36
        end
        t37 = acc_31
        out_1 << t37
      end
      out << out_1
    end
    out
  end

  def self._count_over_limit(input)
    acc_38 = 0
    t39 = input["cube"] || input[:cube]
    t59 = 100
    t49 = 1
    t50 = 0
    t39.each_with_index do |cube_el_40, cube_i_41|
      acc_42 = 0
      cube_el_40.each_with_index do |layer_el_43, layer_i_44|
        acc_45 = 0
        layer_el_43.each_with_index do |row_el_46, row_i_47|
          t60 = row_el_46 > t59
          t51 = t60 ? t49 : t50
          acc_45 += t51
        end
        t52 = acc_45
        acc_42 += t52
      end
      t53 = acc_42
      acc_38 += t53
    end
    acc_38
  end
end
