# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_466b25cf0c819df52c2ac63d1a79ae3e9f7eaa9e94570208049d5963db8ddcf0
  def self._cube(input)
    t2 = input["cube"] || input[:cube]
    return t2
  end

  def self._layer(input)
    t4 = input["cube"] || input[:cube]
    arr8 = []
    t4.each_with_index do |cube_el5, cube_i6|
      arr8 << cube_el5
    end
    return arr8
  end

  def self._row(input)
    t7 = input["cube"] || input[:cube]
    arr13 = []
    t7.each_with_index do |cube_el8, cube_i9|
      arr14 = []
      cube_el8.each_with_index do |layer_el10, layer_i11|
        arr14 << layer_el10
      end
      arr13 << arr14
    end
    return arr13
  end

  def self._cell(input)
    t11 = input["cube"] || input[:cube]
    arr19 = []
    t11.each_with_index do |cube_el12, cube_i13|
      arr20 = []
      cube_el12.each_with_index do |layer_el14, layer_i15|
        arr21 = []
        layer_el14.each_with_index do |row_el16, row_i17|
          arr21 << row_el16
        end
        arr20 << arr21
      end
      arr19 << arr20
    end
    return arr19
  end

  def self._cell_over_limit(input)
    t18 = input["cube"] || input[:cube]
    arr26 = []
    t18.each_with_index do |cube_el19, cube_i20|
      arr27 = []
      cube_el19.each_with_index do |layer_el21, layer_i22|
        arr28 = []
        layer_el21.each_with_index do |row_el23, row_i24|
          t25 = 100
          t17 = row_el23 > t25
          arr28 << t17
        end
        arr27 << arr28
      end
      arr26 << arr27
    end
    return arr26
  end

  def self._cell_sum(input)
    t34 = input["cube"] || input[:cube]
    arr44 = []
    t34.each_with_index do |cube_el35, cube_i36|
      arr45 = []
      cube_el35.each_with_index do |layer_el37, layer_i38|
        acc43 = 0
        layer_el37.each_with_index do |row_el39, row_i40|
          t41 = 100
          t33 = row_el39 > t41
          t42 = 0
          t25 = t33 ? row_el39 : t42
          acc43 += t25
        end
        arr45 << acc43
      end
      arr44 << arr45
    end
    return arr44
  end

  def self._count_over_limit(input)
    t43 = input["cube"] || input[:cube]
    acc55 = 0
    t43.each_with_index do |cube_el44, cube_i45|
      acc54 = 0
      cube_el44.each_with_index do |layer_el46, layer_i47|
        acc53 = 0
        layer_el46.each_with_index do |row_el48, row_i49|
          t50 = 100
          t42 = row_el48 > t50
          t51 = 1
          t52 = 0
          t32 = t42 ? t51 : t52
          acc53 += t32
        end
        acc54 += acc53
      end
      acc55 += acc54
    end
    return acc55
  end
end
