// Autogenerated by Kumi Codegen for schema KUMI_5abd226e4fb46d8f7b623d2c9ba2f7455069710c75721566249a59046ea9ada1
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'numbers_mult_10': return this._numbers_mult_10();
      case 'sum_of_nums': return this._sum_of_nums();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _numbers_mult_10(input = this.input) {
    let out = [];
    let t1 = input["a1"];
    t1?.forEach((a1_el_2, a1_i_3) => {
      let out_1 = [];
      a1_el_2?.forEach((ea1_el_4, ea1_i_5) => {
        let out_2 = [];
        let t6 = ea1_el_4?.a2;
        t6?.forEach((a2_el_7, a2_i_8) => {
          let out_3 = [];
          let t9 = a2_el_7?.h1;
          let t10 = t9?.ea2;
          t10?.forEach((ea2_el_11, ea2_i_12) => {
            let t14 = ea2_el_11 * 10;
            out_3.push(t14);
          });
          out_2.push(out_3);
        });
        out_1.push(out_2);
      });
      out.push(out_1);
    });
    return out;
  }

  _sum_of_nums(input = this.input) {
    let out = [];
    let t15 = input["a1"];
    t15?.forEach((a1_el_16, a1_i_17) => {
      let out_1 = [];
      a1_el_16?.forEach((ea1_el_18, ea1_i_19) => {
        let out_2 = [];
        let t20 = ea1_el_18?.a2;
        t20?.forEach((a2_el_21, a2_i_22) => {
          let acc_23 = 0;
          let t24 = a2_el_21?.h1;
          let t25 = t24?.ea2;
          t25?.forEach((ea2_el_26, ea2_i_27) => {
            let t35 = ea2_el_26 * 10;
            acc_23 += t35;
          });
          out_2.push(acc_23);
        });
        out_1.push(out_2);
      });
      out.push(out_1);
    });
    return out;
  }

}
