# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_da8a14f5173aeacc57a51c4ce575639861c36278e0af1886b5340976ef99de82
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :next_state then _next_state
    else raise KeyError, "Unknown declaration"
    end
  end

  def _next_state(input = @input)
    out = []
    t285 = input["rows"] || input[:rows]
    t1548 = t285.length
    t1549 = -1
    t1551 = 0
    t1555 = 1
    t1534 = 3
    t1745 = 2
    t1952 = 0
    t291 = 1
    t1556 = t1548 - t1555
    t285.each_with_index do |rows_el_286, rows_i_287|
      out_1 = []
      t1550 = rows_i_287 - t1549
      t1570 = rows_i_287 - t1555
      t1589 = rows_i_287 % t1548
      t1552 = t1550 >= t1551
      t1553 = t1550 < t1548
      t1558 = [[ t1550, t1551 ].max, t1556 ].min
      t1572 = t1570 >= t1551
      t1573 = t1570 < t1548
      t1578 = [[ t1570, t1551 ].max, t1556 ].min
      t1590 = t1589 + t1548
      t1554 = t1552 && t1553
      t1559 = t285[t1558]
      t1574 = t1572 && t1573
      t1579 = t285[t1578]
      t1591 = t1590 % t1548
      t1560 = t1559.length
      t1580 = t1579.length
      t1592 = t285[t1591]
      t1593 = t1592.length
      t1649 = t1560 - t1555
      t1705 = t1580 - t1555
      t1601 = t1593 - t1555
      rows_el_286.each_with_index do |col_el_288, col_i_289|
        t1561 = col_i_289 % t1560
        t1562 = t1561 + t1560
        t1563 = t1562 % t1560
        t1564 = t1559[t1563]
        t1566 = t1554 ? t1564 : t1551
        t1581 = col_i_289 % t1580
        t1582 = t1581 + t1580
        t1583 = t1582 % t1580
        t1584 = t1579[t1583]
        t1586 = t1574 ? t1584 : t1551
        t1595 = col_i_289 - t1549
        t1597 = t1595 >= t1551
        t1598 = t1595 < t1593
        t1599 = t1597 && t1598
        t1603 = [[ t1595, t1551 ].max, t1601 ].min
        t1604 = t1592[t1603]
        t1606 = t1599 ? t1604 : t1551
        t1615 = col_i_289 - t1555
        t1617 = t1615 >= t1551
        t1618 = t1615 < t1593
        t1619 = t1617 && t1618
        t1623 = [[ t1615, t1551 ].max, t1601 ].min
        t1624 = t1592[t1623]
        t1626 = t1619 ? t1624 : t1551
        t1645 = t1595 < t1560
        t1646 = t1597 && t1645
        t1647 = t1554 && t1646
        t1651 = [[ t1595, t1551 ].max, t1649 ].min
        t1652 = t1559[t1651]
        t1654 = t1647 ? t1652 : t1551
        t1673 = t1615 < t1560
        t1674 = t1617 && t1673
        t1675 = t1554 && t1674
        t1679 = [[ t1615, t1551 ].max, t1649 ].min
        t1680 = t1559[t1679]
        t1682 = t1675 ? t1680 : t1551
        t1701 = t1595 < t1580
        t1702 = t1597 && t1701
        t1703 = t1574 && t1702
        t1707 = [[ t1595, t1551 ].max, t1705 ].min
        t1708 = t1579[t1707]
        t1710 = t1703 ? t1708 : t1551
        t1729 = t1615 < t1580
        t1730 = t1617 && t1729
        t1731 = t1574 && t1730
        t1735 = [[ t1615, t1551 ].max, t1705 ].min
        t1736 = t1579[t1735]
        t1738 = t1731 ? t1736 : t1551
        t1545 = [t1566, t1586, t1606, t1626, t1654, t1682, t1710, t1738]
        t1546 = t1545.sum
        t1535 = t1546 == t1534
        t1746 = t1546 == t1745
        t1953 = col_el_288 > t1952
        t1742 = t1746 && t1953
        t1531 = t1535 || t1742
        t293 = t1531 ? t291 : t1952
        out_1 << t293
      end
      out << out_1
    end
    out
  end
end
