# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_63891484c21343587e5bfed707bd1de5fa48b1f9543d2c21300ec466f8e6a9b2
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :a then _a
    when :n then _n
    when :s then _s
    when :w then _w
    when :e then _e
    when :nw then _nw
    when :ne then _ne
    when :sw then _sw
    when :se then _se
    when :neighbors then _neighbors
    when :alive then _alive
    when :n3_alive then _n3_alive
    when :n2_alive then _n2_alive
    when :keep_alive then _keep_alive
    when :next_alive then _next_alive
    when :next_state then _next_state
    else raise KeyError, "Unknown declaration"
    end
  end

  def _a(input = @input)
    out = []
    t1 = input["rows"] || input[:rows]
    t1.each_with_index do |rows_el_2, rows_i_3|
      out_1 = []
      rows_el_2.each_with_index do |col_el_4, col_i_5|
        out_1 << col_el_4
      end
      out << out_1
    end
    out
  end

  def _n(input = @input)
    out = []
    t6 = input["rows"] || input[:rows]
    t11 = t6.length
    t12 = -1
    t6.each_with_index do |rows_el_7, rows_i_8|
      out_1 = []
      t13 = rows_i_8 - t12
      t14 = t13 % t11
      t15 = t14 + t11
      t16 = t15 % t11
      t17 = t6[t16]
      t18 = t17.length
      rows_el_7.each_with_index do |col_el_9, col_i_10|
        t19 = col_i_10 % t18
        t20 = t19 + t18
        t21 = t20 % t18
        t22 = t17[t21]
        out_1 << t22
      end
      out << out_1
    end
    out
  end

  def _s(input = @input)
    out = []
    t23 = input["rows"] || input[:rows]
    t28 = t23.length
    t29 = 1
    t23.each_with_index do |rows_el_24, rows_i_25|
      out_1 = []
      t30 = rows_i_25 - t29
      t31 = t30 % t28
      t32 = t31 + t28
      t33 = t32 % t28
      t34 = t23[t33]
      t35 = t34.length
      rows_el_24.each_with_index do |col_el_26, col_i_27|
        t36 = col_i_27 % t35
        t37 = t36 + t35
        t38 = t37 % t35
        t39 = t34[t38]
        out_1 << t39
      end
      out << out_1
    end
    out
  end

  def _w(input = @input)
    out = []
    t40 = input["rows"] || input[:rows]
    t45 = t40.length
    t51 = -1
    t40.each_with_index do |rows_el_41, rows_i_42|
      out_1 = []
      t46 = rows_i_42 % t45
      t47 = t46 + t45
      t48 = t47 % t45
      t49 = t40[t48]
      t50 = t49.length
      rows_el_41.each_with_index do |col_el_43, col_i_44|
        t52 = col_i_44 - t51
        t53 = t52 % t50
        t54 = t53 + t50
        t55 = t54 % t50
        t56 = t49[t55]
        out_1 << t56
      end
      out << out_1
    end
    out
  end

  def _e(input = @input)
    out = []
    t57 = input["rows"] || input[:rows]
    t62 = t57.length
    t68 = 1
    t57.each_with_index do |rows_el_58, rows_i_59|
      out_1 = []
      t63 = rows_i_59 % t62
      t64 = t63 + t62
      t65 = t64 % t62
      t66 = t57[t65]
      t67 = t66.length
      rows_el_58.each_with_index do |col_el_60, col_i_61|
        t69 = col_i_61 - t68
        t70 = t69 % t67
        t71 = t70 + t67
        t72 = t71 % t67
        t73 = t66[t72]
        out_1 << t73
      end
      out << out_1
    end
    out
  end

  def _nw(input = @input)
    out = []
    t74 = input["rows"] || input[:rows]
    t79 = t74.length
    t80 = -1
    t74.each_with_index do |rows_el_75, rows_i_76|
      out_1 = []
      t81 = rows_i_76 - t80
      t82 = t81 % t79
      t83 = t82 + t79
      t84 = t83 % t79
      t85 = t74[t84]
      t86 = t85.length
      rows_el_75.each_with_index do |col_el_77, col_i_78|
        t88 = col_i_78 - t80
        t89 = t88 % t86
        t90 = t89 + t86
        t91 = t90 % t86
        t92 = t85[t91]
        out_1 << t92
      end
      out << out_1
    end
    out
  end

  def _ne(input = @input)
    out = []
    t93 = input["rows"] || input[:rows]
    t98 = t93.length
    t99 = -1
    t106 = 1
    t93.each_with_index do |rows_el_94, rows_i_95|
      out_1 = []
      t100 = rows_i_95 - t99
      t101 = t100 % t98
      t102 = t101 + t98
      t103 = t102 % t98
      t104 = t93[t103]
      t105 = t104.length
      rows_el_94.each_with_index do |col_el_96, col_i_97|
        t107 = col_i_97 - t106
        t108 = t107 % t105
        t109 = t108 + t105
        t110 = t109 % t105
        t111 = t104[t110]
        out_1 << t111
      end
      out << out_1
    end
    out
  end

  def _sw(input = @input)
    out = []
    t112 = input["rows"] || input[:rows]
    t117 = t112.length
    t118 = 1
    t125 = -1
    t112.each_with_index do |rows_el_113, rows_i_114|
      out_1 = []
      t119 = rows_i_114 - t118
      t120 = t119 % t117
      t121 = t120 + t117
      t122 = t121 % t117
      t123 = t112[t122]
      t124 = t123.length
      rows_el_113.each_with_index do |col_el_115, col_i_116|
        t126 = col_i_116 - t125
        t127 = t126 % t124
        t128 = t127 + t124
        t129 = t128 % t124
        t130 = t123[t129]
        out_1 << t130
      end
      out << out_1
    end
    out
  end

  def _se(input = @input)
    out = []
    t131 = input["rows"] || input[:rows]
    t136 = t131.length
    t137 = 1
    t131.each_with_index do |rows_el_132, rows_i_133|
      out_1 = []
      t138 = rows_i_133 - t137
      t139 = t138 % t136
      t140 = t139 + t136
      t141 = t140 % t136
      t142 = t131[t141]
      t143 = t142.length
      rows_el_132.each_with_index do |col_el_134, col_i_135|
        t145 = col_i_135 - t137
        t146 = t145 % t143
        t147 = t146 + t143
        t148 = t147 % t143
        t149 = t142[t148]
        out_1 << t149
      end
      out << out_1
    end
    out
  end

  def _neighbors(input = @input)
    out = []
    t150 = input["rows"] || input[:rows]
    t215 = t150.length
    t216 = -1
    t229 = 1
    t150.each_with_index do |rows_el_151, rows_i_152|
      out_1 = []
      t217 = rows_i_152 - t216
      t230 = rows_i_152 - t229
      t242 = rows_i_152 % t215
      t218 = t217 % t215
      t231 = t230 % t215
      t243 = t242 + t215
      t219 = t218 + t215
      t232 = t231 + t215
      t244 = t243 % t215
      t220 = t219 % t215
      t233 = t232 % t215
      t245 = t150[t244]
      t221 = t150[t220]
      t234 = t150[t233]
      t246 = t245.length
      t222 = t221.length
      t235 = t234.length
      rows_el_151.each_with_index do |col_el_153, col_i_154|
        t223 = col_i_154 % t222
        t224 = t223 + t222
        t225 = t224 % t222
        t226 = t221[t225]
        t236 = col_i_154 % t235
        t237 = t236 + t235
        t238 = t237 % t235
        t239 = t234[t238]
        t248 = col_i_154 - t216
        t249 = t248 % t246
        t250 = t249 + t246
        t251 = t250 % t246
        t252 = t245[t251]
        t261 = col_i_154 - t229
        t262 = t261 % t246
        t263 = t262 + t246
        t264 = t263 % t246
        t265 = t245[t264]
        t277 = t248 % t222
        t278 = t277 + t222
        t279 = t278 % t222
        t280 = t221[t279]
        t292 = t261 % t222
        t293 = t292 + t222
        t294 = t293 % t222
        t295 = t221[t294]
        t307 = t248 % t235
        t308 = t307 + t235
        t309 = t308 % t235
        t310 = t234[t309]
        t322 = t261 % t235
        t323 = t322 + t235
        t324 = t323 % t235
        t325 = t234[t324]
        t163 = [t226, t239, t252, t265, t280, t295, t310, t325]
        t164 = t163.sum
        out_1 << t164
      end
      out << out_1
    end
    out
  end

  def _alive(input = @input)
    out = []
    t165 = input["rows"] || input[:rows]
    t171 = 0
    t165.each_with_index do |rows_el_166, rows_i_167|
      out_1 = []
      rows_el_166.each_with_index do |col_el_168, col_i_169|
        t172 = col_el_168 > t171
        out_1 << t172
      end
      out << out_1
    end
    out
  end

  def _n3_alive(input = @input)
    out = []
    t173 = input["rows"] || input[:rows]
    t370 = t173.length
    t371 = -1
    t384 = 1
    t179 = 3
    t173.each_with_index do |rows_el_174, rows_i_175|
      out_1 = []
      t372 = rows_i_175 - t371
      t385 = rows_i_175 - t384
      t397 = rows_i_175 % t370
      t373 = t372 % t370
      t386 = t385 % t370
      t398 = t397 + t370
      t374 = t373 + t370
      t387 = t386 + t370
      t399 = t398 % t370
      t375 = t374 % t370
      t388 = t387 % t370
      t400 = t173[t399]
      t376 = t173[t375]
      t389 = t173[t388]
      t401 = t400.length
      t377 = t376.length
      t390 = t389.length
      rows_el_174.each_with_index do |col_el_176, col_i_177|
        t378 = col_i_177 % t377
        t379 = t378 + t377
        t380 = t379 % t377
        t381 = t376[t380]
        t391 = col_i_177 % t390
        t392 = t391 + t390
        t393 = t392 % t390
        t394 = t389[t393]
        t403 = col_i_177 - t371
        t404 = t403 % t401
        t405 = t404 + t401
        t406 = t405 % t401
        t407 = t400[t406]
        t416 = col_i_177 - t384
        t417 = t416 % t401
        t418 = t417 + t401
        t419 = t418 % t401
        t420 = t400[t419]
        t432 = t403 % t377
        t433 = t432 + t377
        t434 = t433 % t377
        t435 = t376[t434]
        t447 = t416 % t377
        t448 = t447 + t377
        t449 = t448 % t377
        t450 = t376[t449]
        t462 = t403 % t390
        t463 = t462 + t390
        t464 = t463 % t390
        t465 = t389[t464]
        t477 = t416 % t390
        t478 = t477 + t390
        t479 = t478 % t390
        t480 = t389[t479]
        t336 = [t381, t394, t407, t420, t435, t450, t465, t480]
        t337 = t336.sum
        t180 = t337 == t179
        out_1 << t180
      end
      out << out_1
    end
    out
  end

  def _n2_alive(input = @input)
    out = []
    t181 = input["rows"] || input[:rows]
    t482 = t181.length
    t483 = -1
    t496 = 1
    t187 = 2
    t181.each_with_index do |rows_el_182, rows_i_183|
      out_1 = []
      t484 = rows_i_183 - t483
      t497 = rows_i_183 - t496
      t509 = rows_i_183 % t482
      t485 = t484 % t482
      t498 = t497 % t482
      t510 = t509 + t482
      t486 = t485 + t482
      t499 = t498 + t482
      t511 = t510 % t482
      t487 = t486 % t482
      t500 = t499 % t482
      t512 = t181[t511]
      t488 = t181[t487]
      t501 = t181[t500]
      t513 = t512.length
      t489 = t488.length
      t502 = t501.length
      rows_el_182.each_with_index do |col_el_184, col_i_185|
        t490 = col_i_185 % t489
        t491 = t490 + t489
        t492 = t491 % t489
        t493 = t488[t492]
        t503 = col_i_185 % t502
        t504 = t503 + t502
        t505 = t504 % t502
        t506 = t501[t505]
        t515 = col_i_185 - t483
        t516 = t515 % t513
        t517 = t516 + t513
        t518 = t517 % t513
        t519 = t512[t518]
        t528 = col_i_185 - t496
        t529 = t528 % t513
        t530 = t529 + t513
        t531 = t530 % t513
        t532 = t512[t531]
        t544 = t515 % t489
        t545 = t544 + t489
        t546 = t545 % t489
        t547 = t488[t546]
        t559 = t528 % t489
        t560 = t559 + t489
        t561 = t560 % t489
        t562 = t488[t561]
        t574 = t515 % t502
        t575 = t574 + t502
        t576 = t575 % t502
        t577 = t501[t576]
        t589 = t528 % t502
        t590 = t589 + t502
        t591 = t590 % t502
        t592 = t501[t591]
        t347 = [t493, t506, t519, t532, t547, t562, t577, t592]
        t348 = t347.sum
        t188 = t348 == t187
        out_1 << t188
      end
      out << out_1
    end
    out
  end

  def _keep_alive(input = @input)
    out = []
    t189 = input["rows"] || input[:rows]
    t595 = t189.length
    t596 = -1
    t609 = 1
    t351 = 2
    t355 = 0
    t189.each_with_index do |rows_el_190, rows_i_191|
      out_1 = []
      t597 = rows_i_191 - t596
      t610 = rows_i_191 - t609
      t622 = rows_i_191 % t595
      t598 = t597 % t595
      t611 = t610 % t595
      t623 = t622 + t595
      t599 = t598 + t595
      t612 = t611 + t595
      t624 = t623 % t595
      t600 = t599 % t595
      t613 = t612 % t595
      t625 = t189[t624]
      t601 = t189[t600]
      t614 = t189[t613]
      t626 = t625.length
      t602 = t601.length
      t615 = t614.length
      rows_el_190.each_with_index do |col_el_192, col_i_193|
        t603 = col_i_193 % t602
        t604 = t603 + t602
        t605 = t604 % t602
        t606 = t601[t605]
        t616 = col_i_193 % t615
        t617 = t616 + t615
        t618 = t617 % t615
        t619 = t614[t618]
        t628 = col_i_193 - t596
        t629 = t628 % t626
        t630 = t629 + t626
        t631 = t630 % t626
        t632 = t625[t631]
        t641 = col_i_193 - t609
        t642 = t641 % t626
        t643 = t642 + t626
        t644 = t643 % t626
        t645 = t625[t644]
        t657 = t628 % t602
        t658 = t657 + t602
        t659 = t658 % t602
        t660 = t601[t659]
        t672 = t641 % t602
        t673 = t672 + t602
        t674 = t673 % t602
        t675 = t601[t674]
        t687 = t628 % t615
        t688 = t687 + t615
        t689 = t688 % t615
        t690 = t614[t689]
        t702 = t641 % t615
        t703 = t702 + t615
        t704 = t703 % t615
        t705 = t614[t704]
        t706 = [t606, t619, t632, t645, t660, t675, t690, t705]
        t707 = t706.sum
        t352 = t707 == t351
        t356 = col_el_192 > t355
        t196 = t352 && t356
        out_1 << t196
      end
      out << out_1
    end
    out
  end

  def _next_alive(input = @input)
    out = []
    t197 = input["rows"] || input[:rows]
    t711 = t197.length
    t712 = -1
    t725 = 1
    t359 = 3
    t836 = 2
    t840 = 0
    t197.each_with_index do |rows_el_198, rows_i_199|
      out_1 = []
      t713 = rows_i_199 - t712
      t726 = rows_i_199 - t725
      t738 = rows_i_199 % t711
      t714 = t713 % t711
      t727 = t726 % t711
      t739 = t738 + t711
      t715 = t714 + t711
      t728 = t727 + t711
      t740 = t739 % t711
      t716 = t715 % t711
      t729 = t728 % t711
      t741 = t197[t740]
      t717 = t197[t716]
      t730 = t197[t729]
      t742 = t741.length
      t718 = t717.length
      t731 = t730.length
      rows_el_198.each_with_index do |col_el_200, col_i_201|
        t719 = col_i_201 % t718
        t720 = t719 + t718
        t721 = t720 % t718
        t722 = t717[t721]
        t732 = col_i_201 % t731
        t733 = t732 + t731
        t734 = t733 % t731
        t735 = t730[t734]
        t744 = col_i_201 - t712
        t745 = t744 % t742
        t746 = t745 + t742
        t747 = t746 % t742
        t748 = t741[t747]
        t757 = col_i_201 - t725
        t758 = t757 % t742
        t759 = t758 + t742
        t760 = t759 % t742
        t761 = t741[t760]
        t773 = t744 % t718
        t774 = t773 + t718
        t775 = t774 % t718
        t776 = t717[t775]
        t788 = t757 % t718
        t789 = t788 + t718
        t790 = t789 % t718
        t791 = t717[t790]
        t803 = t744 % t731
        t804 = t803 + t731
        t805 = t804 % t731
        t806 = t730[t805]
        t818 = t757 % t731
        t819 = t818 + t731
        t820 = t819 % t731
        t821 = t730[t820]
        t822 = [t722, t735, t748, t761, t776, t791, t806, t821]
        t823 = t822.sum
        t360 = t823 == t359
        t837 = t823 == t836
        t841 = col_el_200 > t840
        t364 = t837 && t841
        t204 = t360 || t364
        out_1 << t204
      end
      out << out_1
    end
    out
  end

  def _next_state(input = @input)
    out = []
    t205 = input["rows"] || input[:rows]
    t979 = t205.length
    t980 = -1
    t993 = 1
    t854 = 3
    t859 = 2
    t863 = 0
    t205.each_with_index do |rows_el_206, rows_i_207|
      out_1 = []
      t981 = rows_i_207 - t980
      t994 = rows_i_207 - t993
      t1006 = rows_i_207 % t979
      t982 = t981 % t979
      t995 = t994 % t979
      t1007 = t1006 + t979
      t983 = t982 + t979
      t996 = t995 + t979
      t1008 = t1007 % t979
      t984 = t983 % t979
      t997 = t996 % t979
      t1009 = t205[t1008]
      t985 = t205[t984]
      t998 = t205[t997]
      t1010 = t1009.length
      t986 = t985.length
      t999 = t998.length
      rows_el_206.each_with_index do |col_el_208, col_i_209|
        t987 = col_i_209 % t986
        t988 = t987 + t986
        t989 = t988 % t986
        t990 = t985[t989]
        t1000 = col_i_209 % t999
        t1001 = t1000 + t999
        t1002 = t1001 % t999
        t1003 = t998[t1002]
        t1012 = col_i_209 - t980
        t1013 = t1012 % t1010
        t1014 = t1013 + t1010
        t1015 = t1014 % t1010
        t1016 = t1009[t1015]
        t1025 = col_i_209 - t993
        t1026 = t1025 % t1010
        t1027 = t1026 + t1010
        t1028 = t1027 % t1010
        t1029 = t1009[t1028]
        t1041 = t1012 % t986
        t1042 = t1041 + t986
        t1043 = t1042 % t986
        t1044 = t985[t1043]
        t1056 = t1025 % t986
        t1057 = t1056 + t986
        t1058 = t1057 % t986
        t1059 = t985[t1058]
        t1071 = t1012 % t999
        t1072 = t1071 + t999
        t1073 = t1072 % t999
        t1074 = t998[t1073]
        t1086 = t1025 % t999
        t1087 = t1086 + t999
        t1088 = t1087 % t999
        t1089 = t998[t1088]
        t852 = [t990, t1003, t1016, t1029, t1044, t1059, t1074, t1089]
        t853 = t852.sum
        t855 = t853 == t854
        t860 = t853 == t859
        t864 = col_el_208 > t863
        t865 = t860 && t864
        t368 = t855 || t865
        t213 = t368 ? t993 : t863
        out_1 << t213
      end
      out << out_1
    end
    out
  end
end
