# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_72c943d81be34feb5fe484d2480e233accb8f461c408bfa07b6c70f6af3556bc
  def self._a(input)
    t4 = input["rows"] || input[:rows]
    arr10 = []
    t4.each_with_index do |rows_el5, rows_i6|
      arr11 = []
      rows_el5.each_with_index do |col_el7, col_i8|
        t9 = col_el7
        arr11 << t9
      end
      arr10 << arr11
    end
    return arr10
  end

  def self._n(input)
    t9 = input["rows"] || input[:rows]
    arr20 = []
    t9.each_with_index do |rows_el10, rows_i11|
      arr21 = []
      rows_el10.each_with_index do |col_el12, col_i13|
        t14 = input["rows"] || input[:rows]
        t15 = t14.length
        t16 = t14[(rows_i11 - (-1)).clamp(0, t15 - 1)]
        t17 = t16[col_i13]
        t18_j = rows_i11 - (-1)
        t18 = t18_j >= 0 && t18_j < t15
        t19 = 0
        t4 = t18 ? t17 : t19
        arr21 << t4
      end
      arr20 << arr21
    end
    return arr20
  end

  def self._s(input)
    t11 = input["rows"] || input[:rows]
    arr22 = []
    t11.each_with_index do |rows_el12, rows_i13|
      arr23 = []
      rows_el12.each_with_index do |col_el14, col_i15|
        t16 = input["rows"] || input[:rows]
        t17 = t16.length
        t18 = t16[(rows_i13 - (1)).clamp(0, t17 - 1)]
        t19 = t18[col_i15]
        t20_j = rows_i13 - (1)
        t20 = t20_j >= 0 && t20_j < t17
        t21 = 0
        t6 = t20 ? t19 : t21
        arr23 << t6
      end
      arr22 << arr23
    end
    return arr22
  end

  def self._w(input)
    t13 = input["rows"] || input[:rows]
    arr22 = []
    t13.each_with_index do |rows_el14, rows_i15|
      arr23 = []
      rows_el14.each_with_index do |col_el16, col_i17|
        t18 = rows_el14.length
        t19 = rows_el14[(col_i17 - (-1)).clamp(0, t18 - 1)]
        t20_j = col_i17 - (-1)
        t20 = t20_j >= 0 && t20_j < t18
        t21 = 0
        t8 = t20 ? t19 : t21
        arr23 << t8
      end
      arr22 << arr23
    end
    return arr22
  end

  def self._e(input)
    t15 = input["rows"] || input[:rows]
    arr24 = []
    t15.each_with_index do |rows_el16, rows_i17|
      arr25 = []
      rows_el16.each_with_index do |col_el18, col_i19|
        t20 = rows_el16.length
        t21 = rows_el16[(col_i19 - (1)).clamp(0, t20 - 1)]
        t22_j = col_i19 - (1)
        t22 = t22_j >= 0 && t22_j < t20
        t23 = 0
        t10 = t22 ? t21 : t23
        arr25 << t10
      end
      arr24 << arr25
    end
    return arr24
  end

  def self._nw(input)
    t18 = input["rows"] || input[:rows]
    arr37 = []
    t18.each_with_index do |rows_el19, rows_i20|
      arr30 = []
      rows_el19.each_with_index do |col_el21, col_i22|
        t23 = input["rows"] || input[:rows]
        t24 = t23.length
        t25 = t23[(rows_i20 - (-1)).clamp(0, t24 - 1)]
        t26 = t25[col_i22]
        t27_j = rows_i20 - (-1)
        t27 = t27_j >= 0 && t27_j < t24
        t28 = 0
        t17 = t27 ? t26 : t28
        arr30 << t17
      end
      arr38 = []
      rows_el19.each_with_index do |col_el31, col_i32|
        t33 = arr30.length
        t34 = arr30[(col_i32 - (-1)).clamp(0, t33 - 1)]
        t35_j = col_i32 - (-1)
        t35 = t35_j >= 0 && t35_j < t33
        t36 = 0
        t12 = t35 ? t34 : t36
        arr38 << t12
      end
      arr37 << arr38
    end
    return arr37
  end

  def self._ne(input)
    t20 = input["rows"] || input[:rows]
    arr39 = []
    t20.each_with_index do |rows_el21, rows_i22|
      arr32 = []
      rows_el21.each_with_index do |col_el23, col_i24|
        t25 = input["rows"] || input[:rows]
        t26 = t25.length
        t27 = t25[(rows_i22 - (-1)).clamp(0, t26 - 1)]
        t28 = t27[col_i24]
        t29_j = rows_i22 - (-1)
        t29 = t29_j >= 0 && t29_j < t26
        t30 = 0
        t19 = t29 ? t28 : t30
        arr32 << t19
      end
      arr40 = []
      rows_el21.each_with_index do |col_el33, col_i34|
        t35 = arr32.length
        t36 = arr32[(col_i34 - (1)).clamp(0, t35 - 1)]
        t37_j = col_i34 - (1)
        t37 = t37_j >= 0 && t37_j < t35
        t38 = 0
        t14 = t37 ? t36 : t38
        arr40 << t14
      end
      arr39 << arr40
    end
    return arr39
  end

  def self._sw(input)
    t22 = input["rows"] || input[:rows]
    arr41 = []
    t22.each_with_index do |rows_el23, rows_i24|
      arr34 = []
      rows_el23.each_with_index do |col_el25, col_i26|
        t27 = input["rows"] || input[:rows]
        t28 = t27.length
        t29 = t27[(rows_i24 - (1)).clamp(0, t28 - 1)]
        t30 = t29[col_i26]
        t31_j = rows_i24 - (1)
        t31 = t31_j >= 0 && t31_j < t28
        t32 = 0
        t21 = t31 ? t30 : t32
        arr34 << t21
      end
      arr42 = []
      rows_el23.each_with_index do |col_el35, col_i36|
        t37 = arr34.length
        t38 = arr34[(col_i36 - (-1)).clamp(0, t37 - 1)]
        t39_j = col_i36 - (-1)
        t39 = t39_j >= 0 && t39_j < t37
        t40 = 0
        t16 = t39 ? t38 : t40
        arr42 << t16
      end
      arr41 << arr42
    end
    return arr41
  end

  def self._se(input)
    t24 = input["rows"] || input[:rows]
    arr43 = []
    t24.each_with_index do |rows_el25, rows_i26|
      arr36 = []
      rows_el25.each_with_index do |col_el27, col_i28|
        t29 = input["rows"] || input[:rows]
        t30 = t29.length
        t31 = t29[(rows_i26 - (1)).clamp(0, t30 - 1)]
        t32 = t31[col_i28]
        t33_j = rows_i26 - (1)
        t33 = t33_j >= 0 && t33_j < t30
        t34 = 0
        t23 = t33 ? t32 : t34
        arr36 << t23
      end
      arr44 = []
      rows_el25.each_with_index do |col_el37, col_i38|
        t39 = arr36.length
        t40 = arr36[(col_i38 - (1)).clamp(0, t39 - 1)]
        t41_j = col_i38 - (1)
        t41 = t41_j >= 0 && t41_j < t39
        t42 = 0
        t18 = t41 ? t40 : t42
        arr44 << t18
      end
      arr43 << arr44
    end
    return arr43
  end

  def self._neighbors(input)
    t66 = input["rows"] || input[:rows]
    arr116 = []
    t66.each_with_index do |rows_el67, rows_i68|
      arr89 = []
      arr100 = []
      arr111 = []
      arr114 = []
      rows_el67.each_with_index do |col_el69, col_i70|
        t71 = input["rows"] || input[:rows]
        t72 = t71.length
        t73 = t71[(rows_i68 - (-1)).clamp(0, t72 - 1)]
        t74 = t73[col_i70]
        t75_j = rows_i68 - (-1)
        t75 = t75_j >= 0 && t75_j < t72
        t76 = 0
        t33 = t75 ? t74 : t76
        arr89 << t33
        t77 = t71[(rows_i68 - (1)).clamp(0, t72 - 1)]
        t78 = t77[col_i70]
        t79_j = rows_i68 - (1)
        t79 = t79_j >= 0 && t79_j < t72
        t80 = 0
        t37 = t79 ? t78 : t80
        arr100 << t37
        t81 = rows_el67.length
        t82 = rows_el67[(col_i70 - (-1)).clamp(0, t81 - 1)]
        t83_j = col_i70 - (-1)
        t83 = t83_j >= 0 && t83_j < t81
        t84 = 0
        t41 = t83 ? t82 : t84
        arr111 << t41
        t85 = rows_el67[(col_i70 - (1)).clamp(0, t81 - 1)]
        t86_j = col_i70 - (1)
        t86 = t86_j >= 0 && t86_j < t81
        t87 = 0
        t45 = t86 ? t85 : t87
        arr114 << t45
      end
      arr117 = []
      rows_el67.each_with_index do |col_el90, col_i91|
        t92 = arr89.length
        t93 = arr89[(col_i91 - (-1)).clamp(0, t92 - 1)]
        t94_j = col_i91 - (-1)
        t94 = t94_j >= 0 && t94_j < t92
        t95 = 0
        t50 = t94 ? t93 : t95
        t96 = arr89[(col_i91 - (1)).clamp(0, t92 - 1)]
        t97_j = col_i91 - (1)
        t97 = t97_j >= 0 && t97_j < t92
        t98 = 0
        t55 = t97 ? t96 : t98
        t101 = arr100.length
        t102 = arr100[(col_i91 - (-1)).clamp(0, t101 - 1)]
        t103_j = col_i91 - (-1)
        t103 = t103_j >= 0 && t103_j < t101
        t104 = 0
        t60 = t103 ? t102 : t104
        t105 = arr100[(col_i91 - (1)).clamp(0, t101 - 1)]
        t106_j = col_i91 - (1)
        t106 = t106_j >= 0 && t106_j < t101
        t107 = 0
        t65 = t106 ? t105 : t107
        t108 = arr89[col_i91]
        t109 = arr100[col_i91]
        acc0 = t108 + t109
        t112 = arr111[col_i91]
        acc1 = acc0 + t112
        t115 = arr114[col_i91]
        acc2 = acc1 + t115
        acc3 = acc2 + t50
        acc4 = acc3 + t55
        acc5 = acc4 + t60
        acc6 = acc5 + t65
        arr117 << acc6
      end
      arr116 << arr117
    end
    return arr116
  end

  def self._alive(input)
    t37 = input["rows"] || input[:rows]
    arr43 = []
    t37.each_with_index do |rows_el38, rows_i39|
      arr44 = []
      rows_el38.each_with_index do |col_el40, col_i41|
        t42 = 0
        t33 = col_el40 > t42
        arr44 << t33
      end
      arr43 << arr44
    end
    return arr43
  end

  def self._n3_alive(input)
    t74 = input["rows"] || input[:rows]
    arr125 = []
    t74.each_with_index do |rows_el75, rows_i76|
      arr97 = []
      arr108 = []
      arr119 = []
      arr122 = []
      rows_el75.each_with_index do |col_el77, col_i78|
        t79 = input["rows"] || input[:rows]
        t80 = t79.length
        t81 = t79[(rows_i76 - (-1)).clamp(0, t80 - 1)]
        t82 = t81[col_i78]
        t83_j = rows_i76 - (-1)
        t83 = t83_j >= 0 && t83_j < t80
        t84 = 0
        t41 = t83 ? t82 : t84
        arr97 << t41
        t85 = t79[(rows_i76 - (1)).clamp(0, t80 - 1)]
        t86 = t85[col_i78]
        t87_j = rows_i76 - (1)
        t87 = t87_j >= 0 && t87_j < t80
        t88 = 0
        t45 = t87 ? t86 : t88
        arr108 << t45
        t89 = rows_el75.length
        t90 = rows_el75[(col_i78 - (-1)).clamp(0, t89 - 1)]
        t91_j = col_i78 - (-1)
        t91 = t91_j >= 0 && t91_j < t89
        t92 = 0
        t49 = t91 ? t90 : t92
        arr119 << t49
        t93 = rows_el75[(col_i78 - (1)).clamp(0, t89 - 1)]
        t94_j = col_i78 - (1)
        t94 = t94_j >= 0 && t94_j < t89
        t95 = 0
        t53 = t94 ? t93 : t95
        arr122 << t53
      end
      arr126 = []
      rows_el75.each_with_index do |col_el98, col_i99|
        t100 = arr97.length
        t101 = arr97[(col_i99 - (-1)).clamp(0, t100 - 1)]
        t102_j = col_i99 - (-1)
        t102 = t102_j >= 0 && t102_j < t100
        t103 = 0
        t58 = t102 ? t101 : t103
        t104 = arr97[(col_i99 - (1)).clamp(0, t100 - 1)]
        t105_j = col_i99 - (1)
        t105 = t105_j >= 0 && t105_j < t100
        t106 = 0
        t63 = t105 ? t104 : t106
        t109 = arr108.length
        t110 = arr108[(col_i99 - (-1)).clamp(0, t109 - 1)]
        t111_j = col_i99 - (-1)
        t111 = t111_j >= 0 && t111_j < t109
        t112 = 0
        t68 = t111 ? t110 : t112
        t113 = arr108[(col_i99 - (1)).clamp(0, t109 - 1)]
        t114_j = col_i99 - (1)
        t114 = t114_j >= 0 && t114_j < t109
        t115 = 0
        t73 = t114 ? t113 : t115
        t116 = arr97[col_i99]
        t117 = arr108[col_i99]
        acc0 = t116 + t117
        t120 = arr119[col_i99]
        acc1 = acc0 + t120
        t123 = arr122[col_i99]
        acc2 = acc1 + t123
        acc3 = acc2 + t58
        acc4 = acc3 + t63
        acc5 = acc4 + t68
        acc6 = acc5 + t73
        t124 = 3
        t37 = acc6 == t124
        arr126 << t37
      end
      arr125 << arr126
    end
    return arr125
  end

  def self._n2_alive(input)
    t78 = input["rows"] || input[:rows]
    arr129 = []
    t78.each_with_index do |rows_el79, rows_i80|
      arr101 = []
      arr112 = []
      arr123 = []
      arr126 = []
      rows_el79.each_with_index do |col_el81, col_i82|
        t83 = input["rows"] || input[:rows]
        t84 = t83.length
        t85 = t83[(rows_i80 - (-1)).clamp(0, t84 - 1)]
        t86 = t85[col_i82]
        t87_j = rows_i80 - (-1)
        t87 = t87_j >= 0 && t87_j < t84
        t88 = 0
        t45 = t87 ? t86 : t88
        arr101 << t45
        t89 = t83[(rows_i80 - (1)).clamp(0, t84 - 1)]
        t90 = t89[col_i82]
        t91_j = rows_i80 - (1)
        t91 = t91_j >= 0 && t91_j < t84
        t92 = 0
        t49 = t91 ? t90 : t92
        arr112 << t49
        t93 = rows_el79.length
        t94 = rows_el79[(col_i82 - (-1)).clamp(0, t93 - 1)]
        t95_j = col_i82 - (-1)
        t95 = t95_j >= 0 && t95_j < t93
        t96 = 0
        t53 = t95 ? t94 : t96
        arr123 << t53
        t97 = rows_el79[(col_i82 - (1)).clamp(0, t93 - 1)]
        t98_j = col_i82 - (1)
        t98 = t98_j >= 0 && t98_j < t93
        t99 = 0
        t57 = t98 ? t97 : t99
        arr126 << t57
      end
      arr130 = []
      rows_el79.each_with_index do |col_el102, col_i103|
        t104 = arr101.length
        t105 = arr101[(col_i103 - (-1)).clamp(0, t104 - 1)]
        t106_j = col_i103 - (-1)
        t106 = t106_j >= 0 && t106_j < t104
        t107 = 0
        t62 = t106 ? t105 : t107
        t108 = arr101[(col_i103 - (1)).clamp(0, t104 - 1)]
        t109_j = col_i103 - (1)
        t109 = t109_j >= 0 && t109_j < t104
        t110 = 0
        t67 = t109 ? t108 : t110
        t113 = arr112.length
        t114 = arr112[(col_i103 - (-1)).clamp(0, t113 - 1)]
        t115_j = col_i103 - (-1)
        t115 = t115_j >= 0 && t115_j < t113
        t116 = 0
        t72 = t115 ? t114 : t116
        t117 = arr112[(col_i103 - (1)).clamp(0, t113 - 1)]
        t118_j = col_i103 - (1)
        t118 = t118_j >= 0 && t118_j < t113
        t119 = 0
        t77 = t118 ? t117 : t119
        t120 = arr101[col_i103]
        t121 = arr112[col_i103]
        acc0 = t120 + t121
        t124 = arr123[col_i103]
        acc1 = acc0 + t124
        t127 = arr126[col_i103]
        acc2 = acc1 + t127
        acc3 = acc2 + t62
        acc4 = acc3 + t67
        acc5 = acc4 + t72
        acc6 = acc5 + t77
        t128 = 2
        t41 = acc6 == t128
        arr130 << t41
      end
      arr129 << arr130
    end
    return arr129
  end

  def self._keep_alive(input)
    t92 = input["rows"] || input[:rows]
    arr144 = []
    t92.each_with_index do |rows_el93, rows_i94|
      arr115 = []
      arr126 = []
      arr137 = []
      arr140 = []
      rows_el93.each_with_index do |col_el95, col_i96|
        t97 = input["rows"] || input[:rows]
        t98 = t97.length
        t99 = t97[(rows_i94 - (-1)).clamp(0, t98 - 1)]
        t100 = t99[col_i96]
        t101_j = rows_i94 - (-1)
        t101 = t101_j >= 0 && t101_j < t98
        t102 = 0
        t48 = t101 ? t100 : t102
        arr115 << t48
        t103 = t97[(rows_i94 - (1)).clamp(0, t98 - 1)]
        t104 = t103[col_i96]
        t105_j = rows_i94 - (1)
        t105 = t105_j >= 0 && t105_j < t98
        t106 = 0
        t52 = t105 ? t104 : t106
        arr126 << t52
        t107 = rows_el93.length
        t108 = rows_el93[(col_i96 - (-1)).clamp(0, t107 - 1)]
        t109_j = col_i96 - (-1)
        t109 = t109_j >= 0 && t109_j < t107
        t110 = 0
        t56 = t109 ? t108 : t110
        arr137 << t56
        t111 = rows_el93[(col_i96 - (1)).clamp(0, t107 - 1)]
        t112_j = col_i96 - (1)
        t112 = t112_j >= 0 && t112_j < t107
        t113 = 0
        t60 = t112 ? t111 : t113
        arr140 << t60
      end
      arr145 = []
      rows_el93.each_with_index do |col_el116, col_i117|
        t118 = arr115.length
        t119 = arr115[(col_i117 - (-1)).clamp(0, t118 - 1)]
        t120_j = col_i117 - (-1)
        t120 = t120_j >= 0 && t120_j < t118
        t121 = 0
        t65 = t120 ? t119 : t121
        t122 = arr115[(col_i117 - (1)).clamp(0, t118 - 1)]
        t123_j = col_i117 - (1)
        t123 = t123_j >= 0 && t123_j < t118
        t124 = 0
        t70 = t123 ? t122 : t124
        t127 = arr126.length
        t128 = arr126[(col_i117 - (-1)).clamp(0, t127 - 1)]
        t129_j = col_i117 - (-1)
        t129 = t129_j >= 0 && t129_j < t127
        t130 = 0
        t75 = t129 ? t128 : t130
        t131 = arr126[(col_i117 - (1)).clamp(0, t127 - 1)]
        t132_j = col_i117 - (1)
        t132 = t132_j >= 0 && t132_j < t127
        t133 = 0
        t80 = t132 ? t131 : t133
        t134 = arr115[col_i117]
        t135 = arr126[col_i117]
        acc0 = t134 + t135
        t138 = arr137[col_i117]
        acc1 = acc0 + t138
        t141 = arr140[col_i117]
        acc2 = acc1 + t141
        acc3 = acc2 + t65
        acc4 = acc3 + t70
        acc5 = acc4 + t75
        acc6 = acc5 + t80
        t142 = 2
        t85 = acc6 == t142
        t143 = 0
        t91 = col_el116 > t143
        t44 = t85 && t91
        arr145 << t44
      end
      arr144 << arr145
    end
    return arr144
  end

  def self._next_alive(input)
    t137 = input["rows"] || input[:rows]
    arr190 = []
    t137.each_with_index do |rows_el138, rows_i139|
      arr160 = []
      arr171 = []
      arr182 = []
      arr185 = []
      rows_el138.each_with_index do |col_el140, col_i141|
        t142 = input["rows"] || input[:rows]
        t143 = t142.length
        t144 = t142[(rows_i139 - (-1)).clamp(0, t143 - 1)]
        t145 = t144[col_i141]
        t146_j = rows_i139 - (-1)
        t146 = t146_j >= 0 && t146_j < t143
        t147 = 0
        t51 = t146 ? t145 : t147
        arr160 << t51
        t148 = t142[(rows_i139 - (1)).clamp(0, t143 - 1)]
        t149 = t148[col_i141]
        t150_j = rows_i139 - (1)
        t150 = t150_j >= 0 && t150_j < t143
        t151 = 0
        t55 = t150 ? t149 : t151
        arr171 << t55
        t152 = rows_el138.length
        t153 = rows_el138[(col_i141 - (-1)).clamp(0, t152 - 1)]
        t154_j = col_i141 - (-1)
        t154 = t154_j >= 0 && t154_j < t152
        t155 = 0
        t59 = t154 ? t153 : t155
        arr182 << t59
        t156 = rows_el138[(col_i141 - (1)).clamp(0, t152 - 1)]
        t157_j = col_i141 - (1)
        t157 = t157_j >= 0 && t157_j < t152
        t158 = 0
        t63 = t157 ? t156 : t158
        arr185 << t63
      end
      arr191 = []
      rows_el138.each_with_index do |col_el161, col_i162|
        t163 = arr160.length
        t164 = arr160[(col_i162 - (-1)).clamp(0, t163 - 1)]
        t165_j = col_i162 - (-1)
        t165 = t165_j >= 0 && t165_j < t163
        t166 = 0
        t68 = t165 ? t164 : t166
        t167 = arr160[(col_i162 - (1)).clamp(0, t163 - 1)]
        t168_j = col_i162 - (1)
        t168 = t168_j >= 0 && t168_j < t163
        t169 = 0
        t73 = t168 ? t167 : t169
        t172 = arr171.length
        t173 = arr171[(col_i162 - (-1)).clamp(0, t172 - 1)]
        t174_j = col_i162 - (-1)
        t174 = t174_j >= 0 && t174_j < t172
        t175 = 0
        t78 = t174 ? t173 : t175
        t176 = arr171[(col_i162 - (1)).clamp(0, t172 - 1)]
        t177_j = col_i162 - (1)
        t177 = t177_j >= 0 && t177_j < t172
        t178 = 0
        t83 = t177 ? t176 : t178
        t179 = arr160[col_i162]
        t180 = arr171[col_i162]
        acc0 = t179 + t180
        t183 = arr182[col_i162]
        acc1 = acc0 + t183
        t186 = arr185[col_i162]
        acc2 = acc1 + t186
        acc3 = acc2 + t68
        acc4 = acc3 + t73
        acc5 = acc4 + t78
        acc6 = acc5 + t83
        t187 = 3
        t88 = acc6 == t187
        t188 = 2
        t129 = acc6 == t188
        t189 = 0
        t135 = col_el161 > t189
        t136 = t129 && t135
        t47 = t88 || t136
        arr191 << t47
      end
      arr190 << arr191
    end
    return arr190
  end

  def self._next_state(input)
    t144 = input["rows"] || input[:rows]
    arr198 = []
    t144.each_with_index do |rows_el145, rows_i146|
      arr167 = []
      arr178 = []
      arr189 = []
      arr192 = []
      rows_el145.each_with_index do |col_el147, col_i148|
        t149 = input["rows"] || input[:rows]
        t150 = t149.length
        t151 = t149[(rows_i146 - (-1)).clamp(0, t150 - 1)]
        t152 = t151[col_i148]
        t153_j = rows_i146 - (-1)
        t153 = t153_j >= 0 && t153_j < t150
        t154 = 0
        t57 = t153 ? t152 : t154
        arr167 << t57
        t155 = t149[(rows_i146 - (1)).clamp(0, t150 - 1)]
        t156 = t155[col_i148]
        t157_j = rows_i146 - (1)
        t157 = t157_j >= 0 && t157_j < t150
        t158 = 0
        t61 = t157 ? t156 : t158
        arr178 << t61
        t159 = rows_el145.length
        t160 = rows_el145[(col_i148 - (-1)).clamp(0, t159 - 1)]
        t161_j = col_i148 - (-1)
        t161 = t161_j >= 0 && t161_j < t159
        t162 = 0
        t65 = t161 ? t160 : t162
        arr189 << t65
        t163 = rows_el145[(col_i148 - (1)).clamp(0, t159 - 1)]
        t164_j = col_i148 - (1)
        t164 = t164_j >= 0 && t164_j < t159
        t165 = 0
        t69 = t164 ? t163 : t165
        arr192 << t69
      end
      arr199 = []
      rows_el145.each_with_index do |col_el168, col_i169|
        t170 = arr167.length
        t171 = arr167[(col_i169 - (-1)).clamp(0, t170 - 1)]
        t172_j = col_i169 - (-1)
        t172 = t172_j >= 0 && t172_j < t170
        t173 = 0
        t74 = t172 ? t171 : t173
        t174 = arr167[(col_i169 - (1)).clamp(0, t170 - 1)]
        t175_j = col_i169 - (1)
        t175 = t175_j >= 0 && t175_j < t170
        t176 = 0
        t79 = t175 ? t174 : t176
        t179 = arr178.length
        t180 = arr178[(col_i169 - (-1)).clamp(0, t179 - 1)]
        t181_j = col_i169 - (-1)
        t181 = t181_j >= 0 && t181_j < t179
        t182 = 0
        t84 = t181 ? t180 : t182
        t183 = arr178[(col_i169 - (1)).clamp(0, t179 - 1)]
        t184_j = col_i169 - (1)
        t184 = t184_j >= 0 && t184_j < t179
        t185 = 0
        t89 = t184 ? t183 : t185
        t186 = arr167[col_i169]
        t187 = arr178[col_i169]
        acc0 = t186 + t187
        t190 = arr189[col_i169]
        acc1 = acc0 + t190
        t193 = arr192[col_i169]
        acc2 = acc1 + t193
        acc3 = acc2 + t74
        acc4 = acc3 + t79
        acc5 = acc4 + t84
        acc6 = acc5 + t89
        t194 = 3
        t94 = acc6 == t194
        t195 = 2
        t135 = acc6 == t195
        t196 = 0
        t141 = col_el168 > t196
        t142 = t135 && t141
        t143 = t94 || t142
        t197 = 1
        t53 = t143 ? t197 : t196
        arr199 << t53
      end
      arr198 << arr199
    end
    return arr198
  end
end
