# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_2d05ccdf805bc9fc26db11e5fdeeca63e257fb47d9a6e051a3ba75d3369f2ab8
  def self._sum_x(input)
    t5 = input["xs"] || input[:xs]
    acc9 = 0.0
    t5.each_with_index do |xs_el6, xs_i7|
      t8 = xs_el6["v"] || xs_el6[:v]
      acc9 += t8
    end
    return acc9
  end

  def self._sum_y(input)
    t9 = input["ys"] || input[:ys]
    acc13 = 0.0
    t9.each_with_index do |ys_el10, ys_i11|
      t12 = ys_el10["v"] || ys_el10[:v]
      acc13 += t12
    end
    return acc13
  end

  def self._tail(input)
    t12 = 12.0
    return t12
  end

  def self._out(input)
    t27 = input["xs"] || input[:xs]
    acc31 = 0.0
    t27.each_with_index do |xs_el28, xs_i29|
      t30 = xs_el28["v"] || xs_el28[:v]
      acc31 += t30
    end
    t32 = input["ys"] || input[:ys]
    acc36 = 0.0
    t32.each_with_index do |ys_el33, ys_i34|
      t35 = ys_el33["v"] || ys_el33[:v]
      acc36 += t35
    end
    t37 = 12.0
    t15 = { "x" => acc31, "y" => acc36, "t" => t37 }
    return t15
  end
end
