# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_84a1ed6bf36465deb286d5e8d006345669b5b5f043f4fcf9aef5438a7cfcf78b
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :summary then _summary
    else raise KeyError, "Unknown declaration"
    end
  end

  def _summary(input = @input)
    t8 = input["name"] || input[:name]
    t9 = t8.length
    t10 = input["items"] || input[:items]
    t11 = t10.length
    t7 = {
      "name_length" => t9,
      "item_count" => t11
    }
    t7
  end
end
