# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_dd2b72b5bdcb6ed2fe404df5dde52c4a0eb13739ab2094e199d0215ac5a60bbc
  def self._double(input)
    t7 = input["items"] || input[:items]
    arr12 = []
    t7.each_with_index do |items_el8, items_i9|
      t10 = items_el8["price"] || items_el8[:price]
      t11 = 2.0
      t6 = t10 * t11
      arr12 << t6
    end
    return arr12
  end

  def self._dj(input)
    t15 = input["items"] || input[:items]
    arr20 = []
    t15.each_with_index do |items_el16, items_i17|
      t18 = items_el16["price"] || items_el16[:price]
      t19 = 2.0
      t14 = t18 * t19
      arr20 << t14
    end
    arr27 = []
    t15.each_with_index do |items_el21, items_i22|
      t23 = input["items"] || input[:items]
      arr28 = []
      t23.each_with_index do |items__x_el24, items__x_i25|
        t26 = arr20[items__x_i25]
        arr28 << t26
      end
      arr27 << arr28
    end
    return arr27
  end

  def self._pair_total(input)
    t18 = input["items"] || input[:items]
    arr23 = []
    t18.each_with_index do |items_el19, items_i20|
      t21 = items_el19["price"] || items_el19[:price]
      t22 = 2.0
      t16 = t21 * t22
      arr23 << t16
    end
    arr31 = []
    t18.each_with_index do |items_el24, items_i25|
      t26 = input["items"] || input[:items]
      acc30 = 0.0
      t26.each_with_index do |items__x_el27, items__x_i28|
        t29 = arr23[items__x_i28]
        acc30 += t29
      end
      arr31 << acc30
    end
    return arr31
  end

  def self._self_diff(input)
    t23 = input["items"] || input[:items]
    arr28 = []
    t23.each_with_index do |items_el24, items_i25|
      t26 = items_el24["price"] || items_el24[:price]
      t27 = 2.0
      t21 = t26 * t27
      arr28 << t21
    end
    arr37 = []
    t23.each_with_index do |items_el29, items_i30|
      t31 = input["items"] || input[:items]
      acc36 = 0.0
      t31.each_with_index do |items__x_el32, items__x_i33|
        t34 = arr28[items__x_i33]
        t35 = arr28[items_i30]
        t14 = t34 - t35
        acc36 += t14
      end
      arr37 << acc36
    end
    return arr37
  end

  def self._idx_i(input)
    t17 = input["items"] || input[:items]
    arr21 = []
    t17.each_with_index do |items_el18, items_i19|
      arr21 << items_i19
    end
    return arr21
  end

  def self._idx_j(input)
    t20 = input["items"] || input[:items]
    arr26 = []
    t20.each_with_index do |items_el21, items_i22|
      t23 = input["items"] || input[:items]
      arr27 = []
      t23.each_with_index do |items__x_el24, items__x_i25|
        arr27 << items__x_i25
      end
      arr26 << arr27
    end
    return arr26
  end

  def self._rank(input)
    t31 = input["items"] || input[:items]
    arr40 = []
    t31.each_with_index do |items_el32, items_i33|
      t34 = input["items"] || input[:items]
      acc39 = 0
      t34.each_with_index do |items__x_el35, items__x_i36|
        t22 = items__x_i36 < items_i33
        t37 = 1
        t38 = 0
        t27 = t22 ? t37 : t38
        acc39 += t27
      end
      arr40 << acc39
    end
    return arr40
  end
end
