# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_af91cecc599c3f3984cf224134c0501fe13d41110b43f5d0303b13e68842ac04
  def self._in_range(input)
    t1 = input["x"] || input[:x]
    t1.between?(1, 10)
  end

  def self._at_lower(input)
    t5 = input["x"] || input[:x]
    t5.between?(5, 5)
  end

  def self._any_flag(input)
    acc_9 = nil
    t10 = input["flags"] || input[:flags]
    t10.each_with_index do |flags_el_11, flags_i_12|
      t13 = flags_el_11["active"] || flags_el_11[:active]
      acc_9 = acc_9 || t13
    end
    acc_9
  end

  def self._no_flags(input)
    acc_15 = nil
    t16 = input["flags"] || input[:flags]
    t16.each_with_index do |flags_el_17, flags_i_18|
      t19 = flags_el_17["active"] || flags_el_17[:active]
      acc_15 = acc_15 || t19
    end
    !acc_15
  end
end
