# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_64c40eab72771870a32e20633871e9701c8aead1e32715eb083db4da45c3316c
  def self._shift_cols_right_zero(input)
    t5 = input["rows"] || input[:rows]
    arr14 = []
    t5.each_with_index do |rows_el6, rows_i7|
      arr15 = []
      rows_el6.each_with_index do |col_el8, col_i9|
        t10 = rows_el6.length
        t11 = rows_el6[(col_i9 - (1)).clamp(0, t10 - 1)]
        t12_j = col_i9 - (1)
        t12 = t12_j >= 0 && t12_j < t10
        t13 = 0
        t1 = t12 ? t11 : t13
        arr15 << t1
      end
      arr14 << arr15
    end
    return arr14
  end

  def self._shift_cols_right_clamp(input)
    t9 = input["rows"] || input[:rows]
    arr16 = []
    t9.each_with_index do |rows_el10, rows_i11|
      arr17 = []
      rows_el10.each_with_index do |col_el12, col_i13|
        t14 = rows_el10.length
        t15 = rows_el10[(col_i13 - (1)).clamp(0, t14 - 1)]
        arr17 << t15
      end
      arr16 << arr17
    end
    return arr16
  end

  def self._shift_cols_right_wrap(input)
    t13 = input["rows"] || input[:rows]
    arr20 = []
    t13.each_with_index do |rows_el14, rows_i15|
      arr21 = []
      rows_el14.each_with_index do |col_el16, col_i17|
        t18 = rows_el14.length
        t19 = rows_el14[((col_i17 - (1)) % t18 + t18) % t18]
        arr21 << t19
      end
      arr20 << arr21
    end
    return arr20
  end

  def self._shift_cols_left_zero(input)
    t17 = input["rows"] || input[:rows]
    arr26 = []
    t17.each_with_index do |rows_el18, rows_i19|
      arr27 = []
      rows_el18.each_with_index do |col_el20, col_i21|
        t22 = rows_el18.length
        t23 = rows_el18[(col_i21 - (-1)).clamp(0, t22 - 1)]
        t24_j = col_i21 - (-1)
        t24 = t24_j >= 0 && t24_j < t22
        t25 = 0
        t13 = t24 ? t23 : t25
        arr27 << t13
      end
      arr26 << arr27
    end
    return arr26
  end

  def self._shift_cols_left_clamp(input)
    t21 = input["rows"] || input[:rows]
    arr28 = []
    t21.each_with_index do |rows_el22, rows_i23|
      arr29 = []
      rows_el22.each_with_index do |col_el24, col_i25|
        t26 = rows_el22.length
        t27 = rows_el22[(col_i25 - (-1)).clamp(0, t26 - 1)]
        arr29 << t27
      end
      arr28 << arr29
    end
    return arr28
  end

  def self._shift_cols_left_wrap(input)
    t25 = input["rows"] || input[:rows]
    arr32 = []
    t25.each_with_index do |rows_el26, rows_i27|
      arr33 = []
      rows_el26.each_with_index do |col_el28, col_i29|
        t30 = rows_el26.length
        t31 = rows_el26[((col_i29 - (-1)) % t30 + t30) % t30]
        arr33 << t31
      end
      arr32 << arr33
    end
    return arr32
  end

  def self._shift_rows_down_zero(input)
    t29 = input["rows"] || input[:rows]
    arr40 = []
    t29.each_with_index do |rows_el30, rows_i31|
      arr41 = []
      rows_el30.each_with_index do |col_el32, col_i33|
        t34 = input["rows"] || input[:rows]
        t35 = t34.length
        t36 = t34[(rows_i31 - (1)).clamp(0, t35 - 1)]
        t37 = t36[col_i33]
        t38_j = rows_i31 - (1)
        t38 = t38_j >= 0 && t38_j < t35
        t39 = 0
        t25 = t38 ? t37 : t39
        arr41 << t25
      end
      arr40 << arr41
    end
    return arr40
  end

  def self._shift_rows_down_clamp(input)
    t33 = input["rows"] || input[:rows]
    arr42 = []
    t33.each_with_index do |rows_el34, rows_i35|
      arr43 = []
      rows_el34.each_with_index do |col_el36, col_i37|
        t38 = input["rows"] || input[:rows]
        t39 = t38.length
        t40 = t38[(rows_i35 - (1)).clamp(0, t39 - 1)]
        t41 = t40[col_i37]
        arr43 << t41
      end
      arr42 << arr43
    end
    return arr42
  end

  def self._shift_rows_down_wrap(input)
    t37 = input["rows"] || input[:rows]
    arr46 = []
    t37.each_with_index do |rows_el38, rows_i39|
      arr47 = []
      rows_el38.each_with_index do |col_el40, col_i41|
        t42 = input["rows"] || input[:rows]
        t43 = t42.length
        t44 = t42[((rows_i39 - (1)) % t43 + t43) % t43]
        t45 = t44[col_i41]
        arr47 << t45
      end
      arr46 << arr47
    end
    return arr46
  end

  def self._shift_rows_up_zero(input)
    t41 = input["rows"] || input[:rows]
    arr52 = []
    t41.each_with_index do |rows_el42, rows_i43|
      arr53 = []
      rows_el42.each_with_index do |col_el44, col_i45|
        t46 = input["rows"] || input[:rows]
        t47 = t46.length
        t48 = t46[(rows_i43 - (-1)).clamp(0, t47 - 1)]
        t49 = t48[col_i45]
        t50_j = rows_i43 - (-1)
        t50 = t50_j >= 0 && t50_j < t47
        t51 = 0
        t37 = t50 ? t49 : t51
        arr53 << t37
      end
      arr52 << arr53
    end
    return arr52
  end

  def self._shift_rows_up_clamp(input)
    t45 = input["rows"] || input[:rows]
    arr54 = []
    t45.each_with_index do |rows_el46, rows_i47|
      arr55 = []
      rows_el46.each_with_index do |col_el48, col_i49|
        t50 = input["rows"] || input[:rows]
        t51 = t50.length
        t52 = t50[(rows_i47 - (-1)).clamp(0, t51 - 1)]
        t53 = t52[col_i49]
        arr55 << t53
      end
      arr54 << arr55
    end
    return arr54
  end

  def self._shift_rows_up_wrap(input)
    t49 = input["rows"] || input[:rows]
    arr58 = []
    t49.each_with_index do |rows_el50, rows_i51|
      arr59 = []
      rows_el50.each_with_index do |col_el52, col_i53|
        t54 = input["rows"] || input[:rows]
        t55 = t54.length
        t56 = t54[((rows_i51 - (-1)) % t55 + t55) % t55]
        t57 = t56[col_i53]
        arr59 << t57
      end
      arr58 << arr59
    end
    return arr58
  end
end
