# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_886bab866ea4f5ef1d52910f9fd141773dd27be56e96c337fb54ded49d90b32f
  def self._meta(input)
    t14 = input["width"] || input[:width]
    t15 = input["height"] || input[:height]
    t4 = { "width" => t14, "height" => t15 }
    t16 = "random"
    t17 = 0.3
    t7 = { "kind" => t16, "density" => t17 }
    t18 = "#0f1219"
    t19 = "#10b981"
    t11 = { "0" => t18, "1" => t19 }
    t20 = 10
    t12 = { "cellSize" => t20, "palette" => t11 }
    t21 = "grid2d"
    t13 = { "render" => t21, "size" => t4, "prefill" => t7, "ui" => t12 }
    return t13
  end
end
