# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_4d4050f5db12d2919f74e9563209523eba649f489f0c87a9007494913114bdd5
  def self._meta(input)
    t1 = "grid2d"
    t2 = input["width"] || input[:width]
    t3 = input["height"] || input[:height]
    t4 = {
      "width" => t2,
      "height" => t3
    }
    t5 = "random"
    t6 = 0.3
    t7 = {
      "kind" => t5,
      "density" => t6
    }
    t8 = 10
    t9 = "#0f1219"
    t10 = "#10b981"
    t11 = {
      "0" => t9,
      "1" => t10
    }
    t12 = {
      "cellSize" => t8,
      "palette" => t11
    }
    t13 = {
      "render" => t1,
      "size" => t4,
      "prefill" => t7,
      "ui" => t12
    }
    t13
  end
end
