# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_4d4050f5db12d2919f74e9563209523eba649f489f0c87a9007494913114bdd5
  def self._meta(input)
    t2 = input["width"] || input[:width]
    t3 = input["height"] || input[:height]
    t4 = {
      "width" => t2,
      "height" => t3
    }
    t7 = {
      "kind" => "random",
      "density" => 0.3
    }
    t11 = {
      "0" => "#0f1219",
      "1" => "#10b981"
    }
    t12 = {
      "cellSize" => 10,
      "palette" => t11
    }
    t13 = {
      "render" => "grid2d",
      "size" => t4,
      "prefill" => t7,
      "ui" => t12
    }
    t13
  end
end
