# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_879c3a35caf522702255513fd2a63d8fe507644c985bcc31321a806c4b7de9a4
  def self._tax_amount(input)
    t5 = input["price"] || input[:price]
    t6 = 0.15
    t4 = t5 * t6
    return t4
  end

  def self._price_after_discount(input)
    t9 = 1.0
    t10 = input["discount_rate"] || input[:discount_rate]
    t7 = t9 - t10
    t11 = input["price"] || input[:price]
    t8 = t11 * t7
    return t8
  end

  def self._discount_saved(input)
    t10 = input["price"] || input[:price]
    t11 = input["discount_rate"] || input[:discount_rate]
    t9 = t10 * t11
    return t9
  end

  def self._tax_on_discounted(input)
    t19 = 1.0
    t20 = input["discount_rate"] || input[:discount_rate]
    t15 = t19 - t20
    t21 = input["price"] || input[:price]
    t16 = t21 * t15
    t22 = 0.15
    t18 = t16 * t22
    return t18
  end

  def self._final_total(input)
    t26 = 1.0
    t27 = input["discount_rate"] || input[:discount_rate]
    t22 = t26 - t27
    t28 = input["price"] || input[:price]
    t23 = t28 * t22
    t29 = 0.15
    t25 = t23 * t29
    t13 = t23 + t25
    return t13
  end
end
