# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_722ee006c51b8b8b4c53ab676d8c894d515cf789233550fe1bc4656ea3dfc891
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :tax_rate then _tax_rate
    when :item_taxes then _item_taxes
    else raise KeyError, "Unknown declaration"
    end
  end

  def _tax_rate(input = @input)
    0.15
  end

  def _item_taxes(input = @input)
    out = []
    t2 = input["items"] || input[:items]
    t6 = 0.15
    t2.each_with_index do |items_el_3, items_i_4|
      t5 = items_el_3["price"] || items_el_3[:price]
      t7 = t5 * t6
      out << t7
    end
    out
  end
end
