# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_7fd2abe829907bd6783b2d666163699b3d5cdaa63cfce09b2235828de95ca1ab
  def self._tax_amount(input)
    t5 = input["amount"] || input[:amount]
    t6 = 0.15
    t4 = t5 * t6
    return t4
  end

  def self._price_after_tax(input)
    t10 = input["amount"] || input[:amount]
    t11 = 0.15
    t9 = t10 * t11
    t5 = t10 + t9
    return t5
  end

  def self._discounted_price(input)
    t18 = input["amount"] || input[:amount]
    t19 = 0.15
    t14 = t18 * t19
    t12 = t18 + t14
    t20 = 1.0
    t21 = input["discount_rate"] || input[:discount_rate]
    t16 = t20 - t21
    t17 = t12 * t16
    return t17
  end

  def self._discount_amount(input)
    t19 = input["amount"] || input[:amount]
    t20 = 0.15
    t17 = t19 * t20
    t15 = t19 + t17
    t21 = input["discount_rate"] || input[:discount_rate]
    t18 = t15 * t21
    return t18
  end

  def self._final_price(input)
    t24 = input["amount"] || input[:amount]
    t25 = 0.15
    t20 = t24 * t25
    t16 = t24 + t20
    t26 = 1.0
    t27 = input["discount_rate"] || input[:discount_rate]
    t22 = t26 - t27
    t23 = t16 * t22
    return t23
  end
end
