# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_ad6e7ee5524d611f2ec03728b7e9f8c097e1308dbaf49da390610067b59c4145
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :regional_sales then _regional_sales
    when :total_sales then _total_sales
    when :adjusted_total then _adjusted_total
    else raise KeyError, "Unknown declaration"
    end
  end

  def _regional_sales(input = @input)
    out = []
    t1 = input["regions"] || input[:regions]
    t1.each_with_index do |regions_el_2, regions_i_3|
      acc_4 = 0
      t5 = regions_el_2["sales"] || regions_el_2[:sales]
      t5.each_with_index do |sales_el_6, sales_i_7|
        t8 = sales_el_6["amount"] || sales_el_6[:amount]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _total_sales(input = @input)
    acc_10 = 0
    t11 = input["regions"] || input[:regions]
    t11.each_with_index do |regions_el_12, regions_i_13|
      acc21 = 0
      t22 = regions_el_12["sales"] || regions_el_12[:sales]
      t22.each_with_index do |t23, t24|
        t25 = t23["amount"] || t23[:amount]
        acc21 += t25
      end
      t26 = acc21
      acc_10 += t26
    end
    acc_10
  end

  def _adjusted_total(input = @input)
    acc28 = 0
    t29 = input["regions"] || input[:regions]
    t29.each_with_index do |t30, t31|
      acc36 = 0
      t37 = t30["sales"] || t30[:sales]
      t37.each_with_index do |t38, t39|
        t40 = t38["amount"] || t38[:amount]
        acc36 += t40
      end
      t41 = acc36
      acc28 += t41
    end
    t33 = acc28
    t17 = input["adjustment"] || input[:adjustment]
    t33 + t17
  end
end
