# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_66b672a69c6018b50be95fdc43efa0d033f231c6bb754d6681e32f0de68f63b8
  def self._regional_sales(input)
    t7 = input["regions"] || input[:regions]
    arr15 = []
    t7.each_with_index do |regions_el8, regions_i9|
      t10 = regions_el8["sales"] || regions_el8[:sales]
      acc14 = 0
      t10.each_with_index do |sales_el11, sales_i12|
        t13 = sales_el11["amount"] || sales_el11[:amount]
        acc14 += t13
      end
      t6 = acc14
      arr15 << t6
    end
    return arr15
  end

  def self._total_sales(input)
    t15 = input["regions"] || input[:regions]
    acc23 = 0
    t15.each_with_index do |regions_el16, regions_i17|
      t18 = regions_el16["sales"] || regions_el16[:sales]
      acc22 = 0
      t18.each_with_index do |sales_el19, sales_i20|
        t21 = sales_el19["amount"] || sales_el19[:amount]
        acc22 += t21
      end
      t14 = acc22
      acc23 += t14
    end
    t8 = acc23
    return t8
  end

  def self._adjusted_total(input)
    t19 = input["regions"] || input[:regions]
    acc27 = 0
    t19.each_with_index do |regions_el20, regions_i21|
      t22 = regions_el20["sales"] || regions_el20[:sales]
      acc26 = 0
      t22.each_with_index do |sales_el23, sales_i24|
        t25 = sales_el23["amount"] || sales_el23[:amount]
        acc26 += t25
      end
      t17 = acc26
      acc27 += t17
    end
    t18 = acc27
    t28 = input["adjustment"] || input[:adjustment]
    t11 = t18 + t28
    return t11
  end
end
