# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_b5eda506631ac67b2fa4e23a5039573b754dbb87a45dd1e8bd18a5dd4c8c97b2
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :high_performer then _high_performer
    when :senior_level then _senior_level
    when :top_team then _top_team
    when :employee_bonus then _employee_bonus
    else raise KeyError, "Unknown declaration"
    end
  end

  def _high_performer(input = @input)
    out = []
    t1 = input["regions"] || input[:regions]
    t14 = 4.5
    t1.each_with_index do |regions_el_2, regions_i_3|
      out_1 = []
      t4 = regions_el_2["offices"] || regions_el_2[:offices]
      t4.each_with_index do |offices_el_5, offices_i_6|
        out_2 = []
        t7 = offices_el_5["teams"] || offices_el_5[:teams]
        t7.each_with_index do |teams_el_8, teams_i_9|
          out_3 = []
          t10 = teams_el_8["employees"] || teams_el_8[:employees]
          t10.each_with_index do |employees_el_11, employees_i_12|
            t13 = employees_el_11["rating"] || employees_el_11[:rating]
            t15 = t13 >= t14
            out_3 << t15
          end
          out_2 << out_3
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def _senior_level(input = @input)
    out = []
    t16 = input["regions"] || input[:regions]
    t29 = "senior"
    t16.each_with_index do |regions_el_17, regions_i_18|
      out_1 = []
      t19 = regions_el_17["offices"] || regions_el_17[:offices]
      t19.each_with_index do |offices_el_20, offices_i_21|
        out_2 = []
        t22 = offices_el_20["teams"] || offices_el_20[:teams]
        t22.each_with_index do |teams_el_23, teams_i_24|
          out_3 = []
          t25 = teams_el_23["employees"] || teams_el_23[:employees]
          t25.each_with_index do |employees_el_26, employees_i_27|
            t28 = employees_el_26["level"] || employees_el_26[:level]
            t30 = t28 == t29
            out_3 << t30
          end
          out_2 << out_3
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def _top_team(input = @input)
    out = []
    t31 = input["regions"] || input[:regions]
    t41 = 0.9
    t31.each_with_index do |regions_el_32, regions_i_33|
      out_1 = []
      t34 = regions_el_32["offices"] || regions_el_32[:offices]
      t34.each_with_index do |offices_el_35, offices_i_36|
        out_2 = []
        t37 = offices_el_35["teams"] || offices_el_35[:teams]
        t37.each_with_index do |teams_el_38, teams_i_39|
          t40 = teams_el_38["performance_score"] || teams_el_38[:performance_score]
          t42 = t40 >= t41
          out_2 << t42
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end

  def _employee_bonus(input = @input)
    out = []
    t43 = input["regions"] || input[:regions]
    t92 = 0.9
    t79 = 4.5
    t86 = "senior"
    t61 = 0.3
    t67 = 0.2
    t70 = 0.05
    t43.each_with_index do |regions_el_44, regions_i_45|
      out_1 = []
      t46 = regions_el_44["offices"] || regions_el_44[:offices]
      t46.each_with_index do |offices_el_47, offices_i_48|
        out_2 = []
        t49 = offices_el_47["teams"] || offices_el_47[:teams]
        t49.each_with_index do |teams_el_50, teams_i_51|
          out_3 = []
          t91 = teams_el_50["performance_score"] || teams_el_50[:performance_score]
          t93 = t91 >= t92
          t52 = teams_el_50["employees"] || teams_el_50[:employees]
          t52.each_with_index do |employees_el_53, employees_i_54|
            t78 = employees_el_53["rating"] || employees_el_53[:rating]
            t80 = t78 >= t79
            t85 = employees_el_53["level"] || employees_el_53[:level]
            t87 = t85 == t86
            t58 = t87 && t93
            t59 = t80 && t58
            t60 = employees_el_53["salary"] || employees_el_53[:salary]
            t62 = t60 * t61
            t65 = t80 && t93
            t68 = t60 * t67
            t71 = t60 * t70
            t72 = t65 ? t68 : t71
            t73 = t59 ? t62 : t72
            out_3 << t73
          end
          out_2 << out_3
        end
        out_1 << out_2
      end
      out << out_1
    end
    out
  end
end
