# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :tuple then _tuple
    when :max_1 then _max_1
    when :max_2 then _max_2
    when :min_1 then _min_1
    when :min_2 then _min_2
    else raise KeyError, "Unknown declaration"
    end
  end

  def _tuple
    t4 = @input["x"]
    [1, 2, 3, t4]
  end

  def _max_1
    t27 = @input["x"]
    t28 = [1, 2, 3, t27]
    t28.max
  end

  def _max_2
    t11 = @input["x"]
    t13 = [1, 2, 3, t11, 1000]
    t13.max
  end

  def _min_1
    t32 = @input["x"]
    t33 = [1, 2, 3, t32]
    t33.min
  end

  def _min_2
    t20 = @input["x"]
    t22 = [1, 2, 3, t20, -100]
    t22.min
  end
end
