// Autogenerated by Kumi Codegen for schema KUMI_4a12680e6daac0df77ed1403de11290ccb547d2ef4002b5b1617558b7ef80f52
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'tuple': return this._tuple();
      case 'max_1': return this._max_1();
      case 'max_2': return this._max_2();
      case 'min_1': return this._min_1();
      case 'min_2': return this._min_2();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _tuple(input = this.input) {
    let t4 = input["x"];
    let t5 = [1, 2, 3, t4];
    return t5;
  }

  _max_1(input = this.input) {
    let t27 = input["x"];
    let t28 = [1, 2, 3, t27];
    let t7 = Math.max(...t28);
    return t7;
  }

  _max_2(input = this.input) {
    let t11 = input["x"];
    let t13 = [1, 2, 3, t11, 1000];
    let t14 = Math.max(...t13);
    return t14;
  }

  _min_1(input = this.input) {
    let t32 = input["x"];
    let t33 = [1, 2, 3, t32];
    let t16 = Math.min(...t33);
    return t16;
  }

  _min_2(input = this.input) {
    let t20 = input["x"];
    let t22 = [1, 2, 3, t20, -100];
    let t23 = Math.min(...t22);
    return t23;
  }

}
