# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_45585fbfe73b28ca0082ec1690ca116a6626d66edd23cac41bf974384ba11136
  def self._tuple(input)
    t6 = 1
    t7 = 2
    t8 = 3
    t9 = input["x"] || input[:x]
    t5 = [t6, t7, t8, t9]
    return t5
  end

  def self._max_1(input)
    t12 = 1
    t13 = 2
    acc0 = t12 > t13 ? t12 : t13
    t14 = 3
    acc1 = acc0 > t14 ? acc0 : t14
    t15 = input["x"] || input[:x]
    acc2 = acc1 > t15 ? acc1 : t15
    return acc2
  end

  def self._max_2(input)
    t13 = 1
    t14 = 2
    acc0 = t13 > t14 ? t13 : t14
    t15 = 3
    acc1 = acc0 > t15 ? acc0 : t15
    t16 = input["x"] || input[:x]
    acc2 = acc1 > t16 ? acc1 : t16
    t17 = 1000
    acc3 = acc2 > t17 ? acc2 : t17
    return acc3
  end

  def self._min_1(input)
    t21 = 1
    t22 = 2
    acc0 = t21 < t22 ? t21 : t22
    t23 = 3
    acc1 = acc0 < t23 ? acc0 : t23
    t24 = input["x"] || input[:x]
    acc2 = acc1 < t24 ? acc1 : t24
    return acc2
  end

  def self._min_2(input)
    t22 = 1
    t23 = 2
    acc0 = t22 < t23 ? t22 : t23
    t24 = 3
    acc1 = acc0 < t24 ? acc0 : t24
    t25 = input["x"] || input[:x]
    acc2 = acc1 < t25 ? acc1 : t25
    t26 = -100
    acc3 = acc2 < t26 ? acc2 : t26
    return acc3
  end
end
