# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_a5782ad7009de5e4e4609cf25691a0938fe0f73cbaa05094b06c8cf283bb98d1
  def self._tuple(input)
    t4 = input["x"] || input[:x]
    [1, 2, 3, t4]
  end

  def self._max_1(input)
    t27 = input["x"] || input[:x]
    t28 = [1, 2, 3, t27]
    t28.max
  end

  def self._max_2(input)
    t11 = input["x"] || input[:x]
    t13 = [1, 2, 3, t11, 1000]
    t13.max
  end

  def self._min_1(input)
    t32 = input["x"] || input[:x]
    t33 = [1, 2, 3, t32]
    t33.min
  end

  def self._min_2(input)
    t20 = input["x"] || input[:x]
    t22 = [1, 2, 3, t20, -100]
    t22.min
  end
end
