// Autogenerated by Kumi Codegen for schema KUMI_ac4cd74ecdad66d1950894488be3a208183667a17fab2adc023eb6bedf7a27db
export class KumiCompiledModule {
  _sum_numbers(input) {
    let acc_1 = 0;
    let t2 = input["numbers"];
    t2.forEach((numbers_el_3, numbers_i_4) => {
      acc_1 += numbers_el_3;
    });
    return acc_1;
  }

  _matrix_sums(input) {
    let out = [];
    let t6 = input["matrix"];
    t6.forEach((matrix_el_7, matrix_i_8) => {
      let acc_9 = 0;
      matrix_el_7.forEach((row_el_10, row_i_11) => {
        acc_9 += row_el_10;
      });
      out.push(acc_9);
    });
    return out;
  }

  _mixed_array(input) {
    let out = [];
    let t13 = input["matrix"];
    let acc23 = 0;
    let t24 = input["numbers"];
    t24.forEach((numbers_el_3, numbers_i_4) => {
      acc23 += numbers_el_3;
    });
    let t18 = input["scalar_val"];
    t13.forEach((matrix_el_14, matrix_i_15) => {
      let out_1 = [];
      matrix_el_14.forEach((row_el_16, row_i_17) => {
        let t20 = [t18, acc23, row_el_16];
        out_1.push(t20);
      });
      out.push(out_1);
    });
    return out;
  }

  _constant(input) {
    const t21 = 42;
    return t21;
  }

}
