# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_0f166f97e7cd1e5ef968ce3b82801a0f7adae0f21cadbb4620532c09c745ac0d
  def self._sum_numbers(input)
    t5 = input["numbers"] || input[:numbers]
    acc9 = 0
    t5.each_with_index do |numbers_el6, numbers_i7|
      t8 = numbers_el6["value"] || numbers_el6[:value]
      acc9 += t8
    end
    t4 = acc9
    return t4
  end

  def self._matrix_sums(input)
    t11 = input["matrix"] || input[:matrix]
    arr19 = []
    t11.each_with_index do |matrix_el12, matrix_i13|
      t14 = matrix_el12["row"] || matrix_el12[:row]
      acc18 = 0.0
      t14.each_with_index do |row_el15, row_i16|
        t17 = row_el15["cell"] || row_el15[:cell]
        acc18 += t17
      end
      t10 = acc18
      arr19 << t10
    end
    return arr19
  end

  def self._mixed_array(input)
    t23 = input["numbers"] || input[:numbers]
    acc27 = 0
    t23.each_with_index do |numbers_el24, numbers_i25|
      t26 = numbers_el24["value"] || numbers_el24[:value]
      acc27 += t26
    end
    t22 = acc27
    t28 = input["matrix"] || input[:matrix]
    arr36 = []
    t28.each_with_index do |matrix_el29, matrix_i30|
      t31 = matrix_el29["row"] || matrix_el29[:row]
      arr37 = []
      t31.each_with_index do |row_el32, row_i33|
        t34 = input["scalar_val"] || input[:scalar_val]
        t35 = row_el32["cell"] || row_el32[:cell]
        t18 = [t34, t22, t35]
        arr37 << t18
      end
      arr36 << arr37
    end
    return arr36
  end

  def self._constant(input)
    t20 = 42
    return t20
  end
end
