# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_adba212c934dd9b75d995f59b1cb45a46b09113bb08947019aa4e751b3e4f1ce
  def self._interest(input)
    t7 = input["amount"] || input[:amount]
    t8 = 1.05
    t3 = t7 * t8
    t9 = input["rate"] || input[:rate]
    t6 = t3 * t9
    return t6
  end

  def self._total_over_periods(input)
    t15 = input["amount"] || input[:amount]
    t16 = 1.05
    t11 = t15 * t16
    t17 = input["rate"] || input[:rate]
    t14 = t11 * t17
    t18 = input["periods"] || input[:periods]
    t8 = t14 * t18
    return t8
  end

  def self._doubled(input)
    t20 = input["amount"] || input[:amount]
    t21 = 1.05
    t14 = t20 * t21
    t22 = input["rate"] || input[:rate]
    t19 = t14 * t22
    t23 = input["periods"] || input[:periods]
    t18 = t19 * t23
    t24 = 2
    t11 = t18 * t24
    return t11
  end
end
