# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_d00b0f3970ed821bd243f767754608cc9b5efc88eae9ef9f6236d89729405d23
  def self._interest(input)
    t7 = input["amount"] || input[:amount]
    t8 = 1.05
    t3 = t7 * t8
    t9 = input["rate"] || input[:rate]
    t6 = t3 * t9
    return t6
  end

  def self._total_over_periods(input)
    t15 = input["amount"] || input[:amount]
    t16 = 1.05
    t11 = t15 * t16
    t17 = input["rate"] || input[:rate]
    t14 = t11 * t17
    t18 = input["periods"] || input[:periods]
    t8 = t14 * t18
    return t8
  end

  def self._doubled(input)
    t20 = input["amount"] || input[:amount]
    t21 = 1.05
    t14 = t20 * t21
    t22 = input["rate"] || input[:rate]
    t19 = t14 * t22
    t23 = input["periods"] || input[:periods]
    t18 = t19 * t23
    t24 = 2
    t11 = t18 * t24
    return t11
  end
end
