# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_99431895d5f7d245b10926a792cae20b14485a0e38800a3e91c4cecfdf1541fd
  def self._order_subtotal(input)
    t1 = input["order_items"] || input[:order_items]
    Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t1})
  end

  def self._tax_amount(input)
    t9 = input["order_items"] || input[:order_items]
    t10 = Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t9})
    t4 = input["tax_rate"] || input[:tax_rate]
    t10 * t4
  end

  def self._total(input)
    t11 = input["order_items"] || input[:order_items]
    t12 = Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t11})
    t14 = input["tax_rate"] || input[:tax_rate]
    t15 = t12 * t14
    t12 + t15
  end
end
