# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_20f9b0ca3a492d9c3175af190d6e04de64cfaec4f8d8e730c8581f39625883f9
  def self._order_subtotal(input)
    t8 = input["order_items"] || input[:order_items]
    acc13 = 0
    t8.each_with_index do |order_items_el9, order_items_i10|
      t11 = order_items_el9["quantity"] || order_items_el9[:quantity]
      t12 = order_items_el9["unit_price"] || order_items_el9[:unit_price]
      t6 = t11 * t12
      acc13 += t6
    end
    t7 = acc13
    return t7
  end

  def self._tax_amount(input)
    t13 = input["order_items"] || input[:order_items]
    acc18 = 0
    t13.each_with_index do |order_items_el14, order_items_i15|
      t16 = order_items_el14["quantity"] || order_items_el14[:quantity]
      t17 = order_items_el14["unit_price"] || order_items_el14[:unit_price]
      t11 = t16 * t17
      acc18 += t11
    end
    t12 = acc18
    t19 = input["tax_rate"] || input[:tax_rate]
    t5 = t12 * t19
    return t5
  end

  def self._total(input)
    t20 = input["order_items"] || input[:order_items]
    acc25 = 0
    t20.each_with_index do |order_items_el21, order_items_i22|
      t23 = order_items_el21["quantity"] || order_items_el21[:quantity]
      t24 = order_items_el21["unit_price"] || order_items_el21[:unit_price]
      t18 = t23 * t24
      acc25 += t18
    end
    t19 = acc25
    t26 = input["tax_rate"] || input[:tax_rate]
    t14 = t19 * t26
    t8 = t19 + t14
    return t8
  end
end
