# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e49d4593d2a036872aa8f62fd0c6e8dc9421112f6cce747e934ea0fb2455fce6
  def self._order_subtotal(input)
    t1 = input["order_items"] || input[:order_items]
    Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t1})
  end

  def self._tax_amount(input)
    t9 = input["order_items"] || input[:order_items]
    t10 = Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t9})
    t4 = input["tax_rate"] || input[:tax_rate]
    t10 * t4
  end

  def self._total(input)
    t11 = input["order_items"] || input[:order_items]
    t12 = Kumi::TestSharedSchemas::Subtotal._subtotal({"items" => t11})
    t14 = input["tax_rate"] || input[:tax_rate]
    t15 = t12 * t14
    t12 + t15
  end
end
