# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_1c841aefa943ccbd3b89bd507f1dd9fcea9c3504ba5f4692de88de403a644386
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :x_is_large then _x_is_large
    when :selected_value then _selected_value
    when :final_value_per_point then _final_value_per_point
    when :grand_total then _grand_total
    else raise KeyError, "Unknown declaration"
    end
  end

  def _x_is_large(input = @input)
    out = []
    t1 = input["points"] || input[:points]
    t5 = 100
    t1.each_with_index do |points_el_2, points_i_3|
      t4 = points_el_2["x"] || points_el_2[:x]
      t6 = t4 > t5
      out << t6
    end
    out
  end

  def _selected_value(input = @input)
    out = []
    t7 = input["points"] || input[:points]
    t29 = 100
    t7.each_with_index do |points_el_8, points_i_9|
      t28 = points_el_8["x"] || points_el_8[:x]
      t12 = points_el_8["y"] || points_el_8[:y]
      t30 = t28 > t29
      t13 = t30 ? t28 : t12
      out << t13
    end
    out
  end

  def _final_value_per_point(input = @input)
    out = []
    t14 = input["points"] || input[:points]
    t38 = 100
    t14.each_with_index do |points_el_15, points_i_16|
      t37 = points_el_15["x"] || points_el_15[:x]
      t34 = points_el_15["y"] || points_el_15[:y]
      t39 = t37 > t38
      t35 = t39 ? t37 : t34
      t19 = [t35, t37]
      t20 = t19.max
      out << t20
    end
    out
  end

  def _grand_total(input = @input)
    acc_21 = 0
    t22 = input["points"] || input[:points]
    t52 = 100
    t22.each_with_index do |points_el_23, points_i_24|
      t51 = points_el_23["x"] || points_el_23[:x]
      t48 = points_el_23["y"] || points_el_23[:y]
      t53 = t51 > t52
      t49 = t53 ? t51 : t48
      t43 = [t49, t51]
      t44 = t43.max
      acc_21 += t44
    end
    acc_21
  end
end
