# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_10d24737af0cd29fba6597e5c51a6a6fa81bdc09b7495873e6247ca3fb0423ac
  def self._summary(input)
    out = []
    t974 = input["income"] || input[:income]
    t976 = [t974, 168600.0]
    t977 = t976.min
    t979 = t977 * 0.062
    t982 = t974 * 0.0145
    t1032 = input["state_rate"] || input[:state_rate]
    t1033 = t974 * t1032
    t1035 = input["local_rate"] || input[:local_rate]
    t1036 = t974 * t1035
    t181 = input["statuses"] || input[:statuses]
    t971 = t979 + t982
    t195 = {
      "marginal" => t1032,
      "effective" => t1032,
      "tax" => t1033
    }
    t199 = {
      "marginal" => t1035,
      "effective" => t1035,
      "tax" => t1036
    }
    t204 = input["retirement_contrib"] || input[:retirement_contrib]
    t858 = [t974, 1.0]
    t859 = t858.max
    t181.each_with_index do |statuses_el_182, statuses_i_183|
      t184 = statuses_el_182["name"] || statuses_el_182[:name]
      t822 = statuses_el_182["std"] || statuses_el_182[:std]
      acc802 = 0.0
      t803 = statuses_el_182["rates"] || statuses_el_182[:rates]
      acc863 = 0.0
      acc913 = 0.0
      t985 = statuses_el_182["addl_threshold"] || statuses_el_182[:addl_threshold]
      acc1039 = 0.0
      acc1127 = 0.0
      acc1219 = 0.0
      acc1315 = 0.0
      t823 = t974 - t822
      t986 = t974 - t985
      t825 = [t823, 0]
      t988 = [t986, 0]
      t826 = t825.max
      t989 = t988.max
      t803.each_with_index do |t804, t805|
        t829 = t804["lo"] || t804[:lo]
        t815 = t826 >= t829
        t847 = t804["hi"] || t804[:hi]
        t841 = t847 == -1
        t844 = t841 ? 100000000000.0 : t847
        t818 = t826 < t844
        t819 = t815 && t818
        t853 = t804["rate"] || t804[:rate]
        t809 = t819 ? t853 : 0
        acc802 += t809
      end
      t991 = t989 * 0.009
      t810 = acc802
      t803.each_with_index do |t865, t866|
        t890 = t865["lo"] || t865[:lo]
        t875 = t826 - t890
        t901 = t865["hi"] || t865[:hi]
        t895 = t901 == -1
        t898 = t895 ? 100000000000.0 : t901
        t879 = t898 - t890
        t880 = [[ t875, 0 ].max, t879 ].min
        t910 = t865["rate"] || t865[:rate]
        t869 = t880 * t910
        acc863 += t869
        acc913 += t869
        acc1039 += t869
        acc1127 += t869
        acc1219 += t869
        acc1315 += t869
      end
      t973 = t971 + t991
      t870 = acc863
      t920 = acc913
      t1046 = acc1039
      t1134 = acc1127
      t1226 = acc1219
      t1322 = acc1315
      t967 = t973 / t859.to_f
      t860 = t870 / t859.to_f
      t1028 = t1046 + t973
      t1116 = t1134 + t973
      t1208 = t1226 + t973
      t1304 = t1322 + t973
      t191 = {
        "effective" => t967,
        "tax" => t973
      }
      t188 = {
        "marginal" => t810,
        "effective" => t860,
        "tax" => t920
      }
      t1029 = t1028 + t1033
      t1117 = t1116 + t1033
      t1209 = t1208 + t1033
      t1305 = t1304 + t1033
      t1030 = t1029 + t1036
      t1118 = t1117 + t1036
      t1210 = t1209 + t1036
      t1306 = t1305 + t1036
      t1022 = t1030 / t859.to_f
      t1202 = t974 - t1210
      t1298 = t974 - t1306
      t202 = {
        "effective" => t1022,
        "tax" => t1118
      }
      t1294 = t1298 - t204
      t206 = {
        "filing_status" => t184,
        "federal" => t188,
        "fica" => t191,
        "state" => t195,
        "local" => t199,
        "total" => t202,
        "after_tax" => t1202,
        "retirement_contrib" => t204,
        "take_home" => t1294
      }
      out << t206
    end
    out
  end
end
