# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_9006cc81344dd7ea708cb391d948967f59806f386c7a081ca8b5ff85d597b75f
  def self._state_tax(input)
    t4 = input["income"] || input[:income]
    t5 = input["state_rate"] || input[:state_rate]
    t3 = t4 * t5
    return t3
  end

  def self._local_tax(input)
    t7 = input["income"] || input[:income]
    t8 = input["local_rate"] || input[:local_rate]
    t6 = t7 * t8
    return t6
  end

  def self._taxable(input)
    t14 = input["statuses"] || input[:statuses]
    arr20 = []
    t14.each_with_index do |statuses_el15, statuses_i16|
      t17 = input["income"] || input[:income]
      t18 = statuses_el15["std"] || statuses_el15[:std]
      t12 = t17 - t18
      t19 = 0
      acc0 = t12 > t19 ? t12 : t19
      arr20 << acc0
    end
    return arr20
  end

  def self._lo(input)
    t21 = input["statuses"] || input[:statuses]
    arr29 = []
    t21.each_with_index do |statuses_el22, statuses_i23|
      t24 = statuses_el22["rates"] || statuses_el22[:rates]
      arr30 = []
      t24.each_with_index do |rates_el25, rates_i26|
        t27 = rates_el25["lo"] || rates_el25[:lo]
        t28 = t27
        arr30 << t28
      end
      arr29 << arr30
    end
    return arr29
  end

  def self._hi(input)
    t26 = input["statuses"] || input[:statuses]
    arr34 = []
    t26.each_with_index do |statuses_el27, statuses_i28|
      t29 = statuses_el27["rates"] || statuses_el27[:rates]
      arr35 = []
      t29.each_with_index do |rates_el30, rates_i31|
        t32 = rates_el30["hi"] || rates_el30[:hi]
        t33 = t32
        arr35 << t33
      end
      arr34 << arr35
    end
    return arr34
  end

  def self._rate(input)
    t31 = input["statuses"] || input[:statuses]
    arr39 = []
    t31.each_with_index do |statuses_el32, statuses_i33|
      t34 = statuses_el32["rates"] || statuses_el32[:rates]
      arr40 = []
      t34.each_with_index do |rates_el35, rates_i36|
        t37 = rates_el35["rate"] || rates_el35[:rate]
        t38 = t37
        arr40 << t38
      end
      arr39 << arr40
    end
    return arr39
  end

  def self._big_hi(input)
    t32 = 100000000000.0
    return t32
  end

  def self._hi_eff(input)
    t45 = input["statuses"] || input[:statuses]
    arr54 = []
    t45.each_with_index do |statuses_el46, statuses_i47|
      t48 = statuses_el46["rates"] || statuses_el46[:rates]
      arr55 = []
      t48.each_with_index do |rates_el49, rates_i50|
        t51 = rates_el49["hi"] || rates_el49[:hi]
        t52 = -1
        t35 = t51 == t52
        t53 = 100000000000.0
        t39 = t35 ? t53 : t51
        arr55 << t39
      end
      arr54 << arr55
    end
    return arr54
  end

  def self._amt(input)
    t80 = input["statuses"] || input[:statuses]
    arr94 = []
    t80.each_with_index do |statuses_el81, statuses_i82|
      t83 = input["income"] || input[:income]
      t84 = statuses_el81["std"] || statuses_el81[:std]
      t55 = t83 - t84
      t85 = 0
      acc0 = t55 > t85 ? t55 : t85
      t86 = statuses_el81["rates"] || statuses_el81[:rates]
      arr95 = []
      t86.each_with_index do |rates_el87, rates_i88|
        t89 = rates_el87["lo"] || rates_el87[:lo]
        t43 = acc0 - t89
        t90 = rates_el87["hi"] || rates_el87[:hi]
        t91 = -1
        t71 = t90 == t91
        t92 = 100000000000.0
        t79 = t71 ? t92 : t90
        t48 = t79 - t89
        t93 = 0
        t49 = t43.clamp(t93, t48)
        arr95 << t49
      end
      arr94 << arr95
    end
    return arr94
  end

  def self._fed_tax(input)
    t100 = input["statuses"] || input[:statuses]
    arr116 = []
    t100.each_with_index do |statuses_el101, statuses_i102|
      t103 = input["income"] || input[:income]
      t104 = statuses_el101["std"] || statuses_el101[:std]
      t59 = t103 - t104
      t105 = 0
      acc0 = t59 > t105 ? t59 : t105
      t106 = statuses_el101["rates"] || statuses_el101[:rates]
      acc115 = 0.0
      t106.each_with_index do |rates_el107, rates_i108|
        t109 = rates_el107["lo"] || rates_el107[:lo]
        t69 = acc0 - t109
        t110 = rates_el107["hi"] || rates_el107[:hi]
        t111 = -1
        t79 = t110 == t111
        t112 = 100000000000.0
        t87 = t79 ? t112 : t110
        t93 = t87 - t109
        t113 = 0
        t94 = t69.clamp(t113, t93)
        t114 = rates_el107["rate"] || rates_el107[:rate]
        t52 = t94 * t114
        acc115 += t52
      end
      t53 = acc115
      arr116 << t53
    end
    return arr116
  end

  def self._in_br(input)
    t102 = input["statuses"] || input[:statuses]
    arr115 = []
    t102.each_with_index do |statuses_el103, statuses_i104|
      t105 = input["income"] || input[:income]
      t106 = statuses_el103["std"] || statuses_el103[:std]
      t68 = t105 - t106
      t107 = 0
      acc0 = t68 > t107 ? t68 : t107
      t108 = statuses_el103["rates"] || statuses_el103[:rates]
      arr116 = []
      t108.each_with_index do |rates_el109, rates_i110|
        t111 = rates_el109["lo"] || rates_el109[:lo]
        t57 = acc0 >= t111
        t112 = rates_el109["hi"] || rates_el109[:hi]
        t113 = -1
        t93 = t112 == t113
        t114 = 100000000000.0
        t101 = t93 ? t114 : t112
        t61 = acc0 < t101
        t62 = t57 && t61
        arr116 << t62
      end
      arr115 << arr116
    end
    return arr115
  end

  def self._fed_marg(input)
    t118 = input["statuses"] || input[:statuses]
    arr134 = []
    t118.each_with_index do |statuses_el119, statuses_i120|
      t121 = input["income"] || input[:income]
      t122 = statuses_el119["std"] || statuses_el119[:std]
      t74 = t121 - t122
      t123 = 0
      acc0 = t74 > t123 ? t74 : t123
      t124 = statuses_el119["rates"] || statuses_el119[:rates]
      acc133 = 0.0
      t124.each_with_index do |rates_el125, rates_i126|
        t127 = rates_el125["lo"] || rates_el125[:lo]
        t84 = acc0 >= t127
        t128 = rates_el125["hi"] || rates_el125[:hi]
        t129 = -1
        t102 = t128 == t129
        t130 = 100000000000.0
        t110 = t102 ? t130 : t128
        t111 = acc0 < t110
        t112 = t84 && t111
        t131 = rates_el125["rate"] || rates_el125[:rate]
        t132 = 0
        t67 = t112 ? t131 : t132
        acc133 += t67
      end
      t68 = acc133
      arr134 << t68
    end
    return arr134
  end

  def self._fed_eff(input)
    t124 = input["statuses"] || input[:statuses]
    t140 = input["income"] || input[:income]
    t141 = 1.0
    acc1 = t140 > t141 ? t140 : t141
    arr146 = []
    t124.each_with_index do |statuses_el125, statuses_i126|
      t127 = input["income"] || input[:income]
      t128 = statuses_el125["std"] || statuses_el125[:std]
      t81 = t127 - t128
      t129 = 0
      acc0 = t81 > t129 ? t81 : t129
      t130 = statuses_el125["rates"] || statuses_el125[:rates]
      acc139 = 0.0
      t130.each_with_index do |rates_el131, rates_i132|
        t133 = rates_el131["lo"] || rates_el131[:lo]
        t91 = acc0 - t133
        t134 = rates_el131["hi"] || rates_el131[:hi]
        t135 = -1
        t101 = t134 == t135
        t136 = 100000000000.0
        t109 = t101 ? t136 : t134
        t115 = t109 - t133
        t137 = 0
        t116 = t91.clamp(t137, t115)
        t138 = rates_el131["rate"] || rates_el131[:rate]
        t122 = t116 * t138
        acc139 += t122
      end
      t123 = acc139
      t75 = t123 / acc1.to_f
      arr146 << t75
    end
    return arr146
  end

  def self._ss_wage_base(input)
    t77 = 168600.0
    return t77
  end

  def self._ss_rate(input)
    t78 = 0.062
    return t78
  end

  def self._ss_tax(input)
    t84 = input["income"] || input[:income]
    t85 = 168600.0
    acc0 = t84 < t85 ? t84 : t85
    t86 = 0.062
    t83 = acc0 * t86
    return t83
  end

  def self._med_base_rate(input)
    t85 = 0.0145
    return t85
  end

  def self._med_tax(input)
    t88 = input["income"] || input[:income]
    t89 = 0.0145
    t87 = t88 * t89
    return t87
  end

  def self._addl_med_rate(input)
    t89 = 0.009
    return t89
  end

  def self._addl_med_tax(input)
    t101 = input["statuses"] || input[:statuses]
    arr108 = []
    t101.each_with_index do |statuses_el102, statuses_i103|
      t104 = input["income"] || input[:income]
      t105 = statuses_el102["addl_threshold"] || statuses_el102[:addl_threshold]
      t94 = t104 - t105
      t106 = 0
      acc0 = t94 > t106 ? t94 : t106
      t107 = 0.009
      t100 = acc0 * t107
      arr108 << t100
    end
    return arr108
  end

  def self._fica_tax(input)
    t128 = input["income"] || input[:income]
    t129 = 168600.0
    acc0 = t128 < t129 ? t128 : t129
    t130 = 0.062
    t112 = acc0 * t130
    t131 = 0.0145
    t115 = t128 * t131
    t103 = t112 + t115
    t132 = input["statuses"] || input[:statuses]
    arr139 = []
    t132.each_with_index do |statuses_el133, statuses_i134|
      t135 = input["income"] || input[:income]
      t136 = statuses_el133["addl_threshold"] || statuses_el133[:addl_threshold]
      t121 = t135 - t136
      t137 = 0
      acc1 = t121 > t137 ? t121 : t137
      t138 = 0.009
      t127 = acc1 * t138
      t106 = t103 + t127
      arr139 << t106
    end
    return arr139
  end

  def self._fica_eff(input)
    t138 = input["income"] || input[:income]
    t139 = 168600.0
    acc0 = t138 < t139 ? t138 : t139
    t140 = 0.062
    t119 = acc0 * t140
    t141 = 0.0145
    t122 = t138 * t141
    t123 = t119 + t122
    t142 = input["statuses"] || input[:statuses]
    t149 = 1.0
    acc2 = t138 > t149 ? t138 : t149
    arr154 = []
    t142.each_with_index do |statuses_el143, statuses_i144|
      t145 = input["income"] || input[:income]
      t146 = statuses_el143["addl_threshold"] || statuses_el143[:addl_threshold]
      t130 = t145 - t146
      t147 = 0
      acc1 = t130 > t147 ? t130 : t147
      t148 = 0.009
      t136 = acc1 * t148
      t137 = t123 + t136
      t113 = t137 / acc2.to_f
      arr154 << t113
    end
    return arr154
  end

  def self._total_tax(input)
    t201 = input["statuses"] || input[:statuses]
    t217 = input["income"] || input[:income]
    t218 = 168600.0
    acc1 = t217 < t218 ? t217 : t218
    t219 = 0.062
    t176 = acc1 * t219
    t220 = 0.0145
    t179 = t217 * t220
    t180 = t176 + t179
    t229 = input["state_rate"] || input[:state_rate]
    t197 = t217 * t229
    t234 = input["local_rate"] || input[:local_rate]
    t200 = t217 * t234
    arr239 = []
    t201.each_with_index do |statuses_el202, statuses_i203|
      t204 = input["income"] || input[:income]
      t205 = statuses_el202["std"] || statuses_el202[:std]
      t128 = t204 - t205
      t206 = 0
      acc0 = t128 > t206 ? t128 : t206
      t207 = statuses_el202["rates"] || statuses_el202[:rates]
      acc216 = 0.0
      t207.each_with_index do |rates_el208, rates_i209|
        t210 = rates_el208["lo"] || rates_el208[:lo]
        t138 = acc0 - t210
        t211 = rates_el208["hi"] || rates_el208[:hi]
        t212 = -1
        t148 = t211 == t212
        t213 = 100000000000.0
        t156 = t148 ? t213 : t211
        t162 = t156 - t210
        t214 = 0
        t163 = t138.clamp(t214, t162)
        t215 = rates_el208["rate"] || rates_el208[:rate]
        t169 = t163 * t215
        acc216 += t169
      end
      t170 = acc216
      t223 = input["income"] || input[:income]
      t224 = statuses_el202["addl_threshold"] || statuses_el202[:addl_threshold]
      t187 = t223 - t224
      t225 = 0
      acc2 = t187 > t225 ? t187 : t225
      t226 = 0.009
      t193 = acc2 * t226
      t194 = t180 + t193
      t116 = t170 + t194
      t119 = t116 + t197
      t122 = t119 + t200
      arr239 << t122
    end
    return arr239
  end

  def self._total_eff(input)
    t213 = input["statuses"] || input[:statuses]
    t229 = input["income"] || input[:income]
    t230 = 168600.0
    acc1 = t229 < t230 ? t229 : t230
    t231 = 0.062
    t183 = acc1 * t231
    t232 = 0.0145
    t186 = t229 * t232
    t187 = t183 + t186
    t241 = input["state_rate"] || input[:state_rate]
    t205 = t229 * t241
    t246 = input["local_rate"] || input[:local_rate]
    t210 = t229 * t246
    t251 = 1.0
    acc3 = t229 > t251 ? t229 : t251
    arr256 = []
    t213.each_with_index do |statuses_el214, statuses_i215|
      t216 = input["income"] || input[:income]
      t217 = statuses_el214["std"] || statuses_el214[:std]
      t135 = t216 - t217
      t218 = 0
      acc0 = t135 > t218 ? t135 : t218
      t219 = statuses_el214["rates"] || statuses_el214[:rates]
      acc228 = 0.0
      t219.each_with_index do |rates_el220, rates_i221|
        t222 = rates_el220["lo"] || rates_el220[:lo]
        t145 = acc0 - t222
        t223 = rates_el220["hi"] || rates_el220[:hi]
        t224 = -1
        t155 = t223 == t224
        t225 = 100000000000.0
        t163 = t155 ? t225 : t223
        t169 = t163 - t222
        t226 = 0
        t170 = t145.clamp(t226, t169)
        t227 = rates_el220["rate"] || rates_el220[:rate]
        t176 = t170 * t227
        acc228 += t176
      end
      t177 = acc228
      t235 = input["income"] || input[:income]
      t236 = statuses_el214["addl_threshold"] || statuses_el214[:addl_threshold]
      t194 = t235 - t236
      t237 = 0
      acc2 = t194 > t237 ? t194 : t237
      t238 = 0.009
      t200 = acc2 * t238
      t201 = t187 + t200
      t202 = t177 + t201
      t207 = t202 + t205
      t212 = t207 + t210
      t129 = t212 / acc3.to_f
      arr256 << t129
    end
    return arr256
  end

  def self._after_tax(input)
    t217 = input["statuses"] || input[:statuses]
    t233 = input["income"] || input[:income]
    t234 = 168600.0
    acc1 = t233 < t234 ? t233 : t234
    t235 = 0.062
    t187 = acc1 * t235
    t236 = 0.0145
    t190 = t233 * t236
    t191 = t187 + t190
    t245 = input["state_rate"] || input[:state_rate]
    t209 = t233 * t245
    t250 = input["local_rate"] || input[:local_rate]
    t214 = t233 * t250
    arr256 = []
    t217.each_with_index do |statuses_el218, statuses_i219|
      t220 = input["income"] || input[:income]
      t221 = statuses_el218["std"] || statuses_el218[:std]
      t139 = t220 - t221
      t222 = 0
      acc0 = t139 > t222 ? t139 : t222
      t223 = statuses_el218["rates"] || statuses_el218[:rates]
      acc232 = 0.0
      t223.each_with_index do |rates_el224, rates_i225|
        t226 = rates_el224["lo"] || rates_el224[:lo]
        t149 = acc0 - t226
        t227 = rates_el224["hi"] || rates_el224[:hi]
        t228 = -1
        t159 = t227 == t228
        t229 = 100000000000.0
        t167 = t159 ? t229 : t227
        t173 = t167 - t226
        t230 = 0
        t174 = t149.clamp(t230, t173)
        t231 = rates_el224["rate"] || rates_el224[:rate]
        t180 = t174 * t231
        acc232 += t180
      end
      t181 = acc232
      t239 = input["income"] || input[:income]
      t240 = statuses_el218["addl_threshold"] || statuses_el218[:addl_threshold]
      t198 = t239 - t240
      t241 = 0
      acc2 = t198 > t241 ? t198 : t241
      t242 = 0.009
      t204 = acc2 * t242
      t205 = t191 + t204
      t206 = t181 + t205
      t211 = t206 + t209
      t216 = t211 + t214
      t255 = input["income"] || input[:income]
      t133 = t255 - t216
      arr256 << t133
    end
    return arr256
  end

  def self._take_home(input)
    t224 = input["statuses"] || input[:statuses]
    t240 = input["income"] || input[:income]
    t241 = 168600.0
    acc1 = t240 < t241 ? t240 : t241
    t242 = 0.062
    t193 = acc1 * t242
    t243 = 0.0145
    t196 = t240 * t243
    t197 = t193 + t196
    t252 = input["state_rate"] || input[:state_rate]
    t215 = t240 * t252
    t257 = input["local_rate"] || input[:local_rate]
    t220 = t240 * t257
    arr264 = []
    t224.each_with_index do |statuses_el225, statuses_i226|
      t227 = input["income"] || input[:income]
      t228 = statuses_el225["std"] || statuses_el225[:std]
      t145 = t227 - t228
      t229 = 0
      acc0 = t145 > t229 ? t145 : t229
      t230 = statuses_el225["rates"] || statuses_el225[:rates]
      acc239 = 0.0
      t230.each_with_index do |rates_el231, rates_i232|
        t233 = rates_el231["lo"] || rates_el231[:lo]
        t155 = acc0 - t233
        t234 = rates_el231["hi"] || rates_el231[:hi]
        t235 = -1
        t165 = t234 == t235
        t236 = 100000000000.0
        t173 = t165 ? t236 : t234
        t179 = t173 - t233
        t237 = 0
        t180 = t155.clamp(t237, t179)
        t238 = rates_el231["rate"] || rates_el231[:rate]
        t186 = t180 * t238
        acc239 += t186
      end
      t187 = acc239
      t246 = input["income"] || input[:income]
      t247 = statuses_el225["addl_threshold"] || statuses_el225[:addl_threshold]
      t204 = t246 - t247
      t248 = 0
      acc2 = t204 > t248 ? t204 : t248
      t249 = 0.009
      t210 = acc2 * t249
      t211 = t197 + t210
      t212 = t187 + t211
      t217 = t212 + t215
      t222 = t217 + t220
      t262 = input["income"] || input[:income]
      t223 = t262 - t222
      t263 = input["retirement_contrib"] || input[:retirement_contrib]
      t137 = t223 - t263
      arr264 << t137
    end
    return arr264
  end

  def self._summary(input)
    t725 = input["statuses"] || input[:statuses]
    t742 = input["income"] || input[:income]
    t743 = 1.0
    acc3 = t742 > t743 ? t742 : t743
    t750 = 168600.0
    acc5 = t742 < t750 ? t742 : t750
    t751 = 0.062
    t323 = acc5 * t751
    t752 = 0.0145
    t326 = t742 * t752
    t327 = t323 + t326
    t759 = input["state_rate"] || input[:state_rate]
    t374 = t742 * t759
    t151 = { "marginal" => t759, "effective" => t759, "tax" => t374 }
    t760 = input["local_rate"] || input[:local_rate]
    t377 = t742 * t760
    t155 = { "marginal" => t760, "effective" => t760, "tax" => t377 }
    arr773 = []
    t725.each_with_index do |statuses_el726, statuses_i727|
      t728 = input["income"] || input[:income]
      t729 = statuses_el726["std"] || statuses_el726[:std]
      t168 = t728 - t729
      t730 = 0
      acc0 = t168 > t730 ? t168 : t730
      t731 = statuses_el726["rates"] || statuses_el726[:rates]
      acc740 = 0.0
      acc741 = 0.0
      t731.each_with_index do |rates_el732, rates_i733|
        t734 = rates_el732["lo"] || rates_el732[:lo]
        t178 = acc0 >= t734
        t735 = rates_el732["hi"] || rates_el732[:hi]
        t736 = -1
        t196 = t735 == t736
        t737 = 100000000000.0
        t204 = t196 ? t737 : t735
        t205 = acc0 < t204
        t206 = t178 && t205
        t738 = rates_el732["rate"] || rates_el732[:rate]
        t739 = 0
        t214 = t206 ? t738 : t739
        acc740 += t214
        t231 = acc0 - t734
        t255 = t204 - t734
        t256 = t231.clamp(t739, t255)
        t262 = t256 * t738
        acc741 += t262
      end
      t215 = acc740
      t263 = acc741
      t269 = t263 / acc3.to_f
      t144 = { "marginal" => t215, "effective" => t269, "tax" => t263 }
      t755 = input["income"] || input[:income]
      t756 = statuses_el726["addl_threshold"] || statuses_el726[:addl_threshold]
      t334 = t755 - t756
      t757 = 0
      acc6 = t334 > t757 ? t334 : t757
      t758 = 0.009
      t340 = acc6 * t758
      t341 = t327 + t340
      t347 = t341 / acc3.to_f
      t147 = { "effective" => t347, "tax" => t341 }
      t450 = t263 + t341
      t455 = t450 + t374
      t460 = t455 + t377
      t466 = t460 / acc3.to_f
      t158 = { "effective" => t466, "tax" => t460 }
      t766 = input["income"] || input[:income]
      t635 = t766 - t460
      t767 = input["retirement_contrib"] || input[:retirement_contrib]
      t724 = t635 - t767
      t768 = statuses_el726["name"] || statuses_el726[:name]
      t162 = { "filing_status" => t768, "federal" => t144, "fica" => t147, "state" => t151, "local" => t155, "total" => t158, "after_tax" => t635, "retirement_contrib" => t767, "take_home" => t724 }
      arr773 << t162
    end
    return arr773
  end
end
