# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_f6cd45a92014eb42b276ebc3f95d8fc9ce044e3e8e8d7326dbe60f6d699e146a
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :summary then _summary
    else raise KeyError, "Unknown declaration"
    end
  end

  def _summary(input = @input)
    t3301 = input["income"] || input[:income]
    t3302 = input["fed"] || input[:fed]
    t3303 = t3302["single"] || t3302[:single]
    t3304 = t3303["std"] || t3303[:std]
    t3305 = t3301 - t3304
    t3306 = 0
    t3307 = [t3305, t3306]
    t3308 = t3307.max
    acc3280 = 0.0
    t3281 = input["fed"] || input[:fed]
    t3282 = t3281["single"] || t3281[:single]
    t3283 = t3282["rates"] || t3282[:rates]
    acc3349 = 0.0
    t3325 = -1
    t3327 = 100000000000.0
    t3283.each_with_index do |t3284, t3285|
      t3320 = t3284["lo"] || t3284[:lo]
      t3333 = t3284["hi"] || t3284[:hi]
      t3341 = t3284["rate"] || t3284[:rate]
      t3297 = t3308 >= t3320
      t3326 = t3333 == t3325
      t3329 = t3326 ? t3327 : t3333
      t3299 = t3308 < t3329
      t3300 = t3297 && t3299
      t3289 = t3300 ? t3341 : t3306
      acc3280 += t3289
      t3364 = t3308 - t3320
      t3368 = t3329 - t3320
      t3369 = [[ t3364, t3306 ].max, t3368 ].min
      t3357 = t3369 * t3341
      acc3349 += t3357
    end
    t3290 = acc3280
    t3358 = acc3349
    t3344 = 1.0
    t3345 = [t3301, t3344]
    t3346 = t3345.max
    t3347 = t3358 / t3346.to_f
    acc3408 = 0.0
    t3283.each_with_index do |t3412, t3413|
      t3440 = t3412["lo"] || t3412[:lo]
      t3453 = t3412["hi"] || t3412[:hi]
      t3465 = t3412["rate"] || t3412[:rate]
      t3423 = t3308 - t3440
      t3446 = t3453 == t3325
      t3449 = t3446 ? t3327 : t3453
      t3427 = t3449 - t3440
      t3428 = [[ t3423, t3306 ].max, t3427 ].min
      t3416 = t3428 * t3465
      acc3408 += t3416
    end
    t3417 = acc3408
    t542 = {
      "marginal" => t3290,
      "effective" => t3347,
      "tax" => t3417
    }
    t3478 = 168600.0
    t3479 = [t3301, t3478]
    t3480 = t3479.min
    t3481 = 0.062
    t3482 = t3480 * t3481
    t3484 = 0.0145
    t3485 = t3301 * t3484
    t3474 = t3482 + t3485
    t3487 = 200000.0
    t3488 = t3301 - t3487
    t3490 = [t3488, t3306]
    t3491 = t3490.max
    t3492 = 0.009
    t3493 = t3491 * t3492
    t3476 = t3474 + t3493
    t3471 = t3476 / t3346.to_f
    t545 = {
      "effective" => t3471,
      "tax" => t3476
    }
    t546 = input["state_rate"] || input[:state_rate]
    t3518 = t3301 * t546
    t549 = {
      "marginal" => t546,
      "effective" => t546,
      "tax" => t3518
    }
    t550 = input["local_rate"] || input[:local_rate]
    t3521 = t3301 * t550
    t553 = {
      "marginal" => t550,
      "effective" => t550,
      "tax" => t3521
    }
    acc3536 = 0.0
    t3283.each_with_index do |t3540, t3541|
      t3568 = t3540["lo"] || t3540[:lo]
      t3581 = t3540["hi"] || t3540[:hi]
      t3593 = t3540["rate"] || t3540[:rate]
      t3551 = t3308 - t3568
      t3574 = t3581 == t3325
      t3577 = t3574 ? t3327 : t3581
      t3555 = t3577 - t3568
      t3556 = [[ t3551, t3306 ].max, t3555 ].min
      t3544 = t3556 * t3593
      acc3536 += t3544
    end
    t3545 = acc3536
    t3530 = t3545 + t3476
    t3532 = t3530 + t3518
    t3534 = t3532 + t3521
    t3527 = t3534 / t3346.to_f
    acc3630 = 0.0
    t3283.each_with_index do |t3634, t3635|
      t3662 = t3634["lo"] || t3634[:lo]
      t3675 = t3634["hi"] || t3634[:hi]
      t3687 = t3634["rate"] || t3634[:rate]
      t3645 = t3308 - t3662
      t3668 = t3675 == t3325
      t3671 = t3668 ? t3327 : t3675
      t3649 = t3671 - t3662
      t3650 = [[ t3645, t3306 ].max, t3649 ].min
      t3638 = t3650 * t3687
      acc3630 += t3638
    end
    t3639 = acc3630
    t3624 = t3639 + t3476
    t3626 = t3624 + t3518
    t3628 = t3626 + t3521
    t556 = {
      "effective" => t3527,
      "tax" => t3628
    }
    acc3727 = 0.0
    t3283.each_with_index do |t3731, t3732|
      t3759 = t3731["lo"] || t3731[:lo]
      t3772 = t3731["hi"] || t3731[:hi]
      t3784 = t3731["rate"] || t3731[:rate]
      t3742 = t3308 - t3759
      t3765 = t3772 == t3325
      t3768 = t3765 ? t3327 : t3772
      t3746 = t3768 - t3759
      t3747 = [[ t3742, t3306 ].max, t3746 ].min
      t3735 = t3747 * t3784
      acc3727 += t3735
    end
    t3736 = acc3727
    t3721 = t3736 + t3476
    t3723 = t3721 + t3518
    t3725 = t3723 + t3521
    t3718 = t3301 - t3725
    t558 = input["retirement_contrib"] || input[:retirement_contrib]
    acc3827 = 0.0
    t3283.each_with_index do |t3831, t3832|
      t3859 = t3831["lo"] || t3831[:lo]
      t3872 = t3831["hi"] || t3831[:hi]
      t3884 = t3831["rate"] || t3831[:rate]
      t3842 = t3308 - t3859
      t3865 = t3872 == t3325
      t3868 = t3865 ? t3327 : t3872
      t3846 = t3868 - t3859
      t3847 = [[ t3842, t3306 ].max, t3846 ].min
      t3835 = t3847 * t3884
      acc3827 += t3835
    end
    t3836 = acc3827
    t3821 = t3836 + t3476
    t3823 = t3821 + t3518
    t3825 = t3823 + t3521
    t3818 = t3301 - t3825
    t3815 = t3818 - t558
    t560 = {
      "federal" => t542,
      "fica" => t545,
      "state" => t549,
      "local" => t553,
      "total" => t556,
      "after_tax" => t3718,
      "retirement_contrib" => t558,
      "take_home" => t3815
    }
    t3937 = t3302["married_joint"] || t3302[:married_joint]
    t3938 = t3937["std"] || t3937[:std]
    t3939 = t3301 - t3938
    t3941 = [t3939, t3306]
    t3942 = t3941.max
    acc3914 = 0.0
    t3916 = t3281["married_joint"] || t3281[:married_joint]
    t3917 = t3916["rates"] || t3916[:rates]
    acc3983 = 0.0
    t3917.each_with_index do |t3918, t3919|
      t3954 = t3918["lo"] || t3918[:lo]
      t3967 = t3918["hi"] || t3918[:hi]
      t3975 = t3918["rate"] || t3918[:rate]
      t3931 = t3942 >= t3954
      t3960 = t3967 == t3325
      t3963 = t3960 ? t3327 : t3967
      t3933 = t3942 < t3963
      t3934 = t3931 && t3933
      t3923 = t3934 ? t3975 : t3306
      acc3914 += t3923
      t3998 = t3942 - t3954
      t4002 = t3963 - t3954
      t4003 = [[ t3998, t3306 ].max, t4002 ].min
      t3991 = t4003 * t3975
      acc3983 += t3991
    end
    t3924 = acc3914
    t3992 = acc3983
    t3981 = t3992 / t3346.to_f
    acc4042 = 0.0
    t3917.each_with_index do |t4046, t4047|
      t4074 = t4046["lo"] || t4046[:lo]
      t4087 = t4046["hi"] || t4046[:hi]
      t4099 = t4046["rate"] || t4046[:rate]
      t4057 = t3942 - t4074
      t4080 = t4087 == t3325
      t4083 = t4080 ? t3327 : t4087
      t4061 = t4083 - t4074
      t4062 = [[ t4057, t3306 ].max, t4061 ].min
      t4050 = t4062 * t4099
      acc4042 += t4050
    end
    t4051 = acc4042
    t564 = {
      "marginal" => t3924,
      "effective" => t3981,
      "tax" => t4051
    }
    t4123 = 250000.0
    t4124 = t3301 - t4123
    t4126 = [t4124, t3306]
    t4127 = t4126.max
    t4129 = t4127 * t3492
    t4110 = t3474 + t4129
    t4105 = t4110 / t3346.to_f
    t567 = {
      "effective" => t4105,
      "tax" => t4110
    }
    acc4174 = 0.0
    t3917.each_with_index do |t4178, t4179|
      t4206 = t4178["lo"] || t4178[:lo]
      t4219 = t4178["hi"] || t4178[:hi]
      t4231 = t4178["rate"] || t4178[:rate]
      t4189 = t3942 - t4206
      t4212 = t4219 == t3325
      t4215 = t4212 ? t3327 : t4219
      t4193 = t4215 - t4206
      t4194 = [[ t4189, t3306 ].max, t4193 ].min
      t4182 = t4194 * t4231
      acc4174 += t4182
    end
    t4183 = acc4174
    t4168 = t4183 + t4110
    t4170 = t4168 + t3518
    t4172 = t4170 + t3521
    t4165 = t4172 / t3346.to_f
    acc4270 = 0.0
    t3917.each_with_index do |t4274, t4275|
      t4302 = t4274["lo"] || t4274[:lo]
      t4315 = t4274["hi"] || t4274[:hi]
      t4327 = t4274["rate"] || t4274[:rate]
      t4285 = t3942 - t4302
      t4308 = t4315 == t3325
      t4311 = t4308 ? t3327 : t4315
      t4289 = t4311 - t4302
      t4290 = [[ t4285, t3306 ].max, t4289 ].min
      t4278 = t4290 * t4327
      acc4270 += t4278
    end
    t4279 = acc4270
    t4264 = t4279 + t4110
    t4266 = t4264 + t3518
    t4268 = t4266 + t3521
    t578 = {
      "effective" => t4165,
      "tax" => t4268
    }
    acc4369 = 0.0
    t3917.each_with_index do |t4373, t4374|
      t4401 = t4373["lo"] || t4373[:lo]
      t4414 = t4373["hi"] || t4373[:hi]
      t4426 = t4373["rate"] || t4373[:rate]
      t4384 = t3942 - t4401
      t4407 = t4414 == t3325
      t4410 = t4407 ? t3327 : t4414
      t4388 = t4410 - t4401
      t4389 = [[ t4384, t3306 ].max, t4388 ].min
      t4377 = t4389 * t4426
      acc4369 += t4377
    end
    t4378 = acc4369
    t4363 = t4378 + t4110
    t4365 = t4363 + t3518
    t4367 = t4365 + t3521
    t4360 = t3301 - t4367
    acc4471 = 0.0
    t3917.each_with_index do |t4475, t4476|
      t4503 = t4475["lo"] || t4475[:lo]
      t4516 = t4475["hi"] || t4475[:hi]
      t4528 = t4475["rate"] || t4475[:rate]
      t4486 = t3942 - t4503
      t4509 = t4516 == t3325
      t4512 = t4509 ? t3327 : t4516
      t4490 = t4512 - t4503
      t4491 = [[ t4486, t3306 ].max, t4490 ].min
      t4479 = t4491 * t4528
      acc4471 += t4479
    end
    t4480 = acc4471
    t4465 = t4480 + t4110
    t4467 = t4465 + t3518
    t4469 = t4467 + t3521
    t4462 = t3301 - t4469
    t4459 = t4462 - t558
    t582 = {
      "federal" => t564,
      "fica" => t567,
      "state" => t549,
      "local" => t553,
      "total" => t578,
      "after_tax" => t4360,
      "retirement_contrib" => t558,
      "take_home" => t4459
    }
    t4583 = t3302["married_separate"] || t3302[:married_separate]
    t4584 = t4583["std"] || t4583[:std]
    t4585 = t3301 - t4584
    t4587 = [t4585, t3306]
    t4588 = t4587.max
    acc4560 = 0.0
    t4562 = t3281["married_separate"] || t3281[:married_separate]
    t4563 = t4562["rates"] || t4562[:rates]
    acc4629 = 0.0
    t4563.each_with_index do |t4564, t4565|
      t4600 = t4564["lo"] || t4564[:lo]
      t4613 = t4564["hi"] || t4564[:hi]
      t4621 = t4564["rate"] || t4564[:rate]
      t4577 = t4588 >= t4600
      t4606 = t4613 == t3325
      t4609 = t4606 ? t3327 : t4613
      t4579 = t4588 < t4609
      t4580 = t4577 && t4579
      t4569 = t4580 ? t4621 : t3306
      acc4560 += t4569
      t4644 = t4588 - t4600
      t4648 = t4609 - t4600
      t4649 = [[ t4644, t3306 ].max, t4648 ].min
      t4637 = t4649 * t4621
      acc4629 += t4637
    end
    t4570 = acc4560
    t4638 = acc4629
    t4627 = t4638 / t3346.to_f
    acc4688 = 0.0
    t4563.each_with_index do |t4692, t4693|
      t4720 = t4692["lo"] || t4692[:lo]
      t4733 = t4692["hi"] || t4692[:hi]
      t4745 = t4692["rate"] || t4692[:rate]
      t4703 = t4588 - t4720
      t4726 = t4733 == t3325
      t4729 = t4726 ? t3327 : t4733
      t4707 = t4729 - t4720
      t4708 = [[ t4703, t3306 ].max, t4707 ].min
      t4696 = t4708 * t4745
      acc4688 += t4696
    end
    t4697 = acc4688
    t586 = {
      "marginal" => t4570,
      "effective" => t4627,
      "tax" => t4697
    }
    t4769 = 125000.0
    t4770 = t3301 - t4769
    t4772 = [t4770, t3306]
    t4773 = t4772.max
    t4775 = t4773 * t3492
    t4756 = t3474 + t4775
    t4751 = t4756 / t3346.to_f
    t589 = {
      "effective" => t4751,
      "tax" => t4756
    }
    acc4820 = 0.0
    t4563.each_with_index do |t4824, t4825|
      t4852 = t4824["lo"] || t4824[:lo]
      t4865 = t4824["hi"] || t4824[:hi]
      t4877 = t4824["rate"] || t4824[:rate]
      t4835 = t4588 - t4852
      t4858 = t4865 == t3325
      t4861 = t4858 ? t3327 : t4865
      t4839 = t4861 - t4852
      t4840 = [[ t4835, t3306 ].max, t4839 ].min
      t4828 = t4840 * t4877
      acc4820 += t4828
    end
    t4829 = acc4820
    t4814 = t4829 + t4756
    t4816 = t4814 + t3518
    t4818 = t4816 + t3521
    t4811 = t4818 / t3346.to_f
    acc4916 = 0.0
    t4563.each_with_index do |t4920, t4921|
      t4948 = t4920["lo"] || t4920[:lo]
      t4961 = t4920["hi"] || t4920[:hi]
      t4973 = t4920["rate"] || t4920[:rate]
      t4931 = t4588 - t4948
      t4954 = t4961 == t3325
      t4957 = t4954 ? t3327 : t4961
      t4935 = t4957 - t4948
      t4936 = [[ t4931, t3306 ].max, t4935 ].min
      t4924 = t4936 * t4973
      acc4916 += t4924
    end
    t4925 = acc4916
    t4910 = t4925 + t4756
    t4912 = t4910 + t3518
    t4914 = t4912 + t3521
    t600 = {
      "effective" => t4811,
      "tax" => t4914
    }
    acc5015 = 0.0
    t4563.each_with_index do |t5019, t5020|
      t5047 = t5019["lo"] || t5019[:lo]
      t5060 = t5019["hi"] || t5019[:hi]
      t5072 = t5019["rate"] || t5019[:rate]
      t5030 = t4588 - t5047
      t5053 = t5060 == t3325
      t5056 = t5053 ? t3327 : t5060
      t5034 = t5056 - t5047
      t5035 = [[ t5030, t3306 ].max, t5034 ].min
      t5023 = t5035 * t5072
      acc5015 += t5023
    end
    t5024 = acc5015
    t5009 = t5024 + t4756
    t5011 = t5009 + t3518
    t5013 = t5011 + t3521
    t5006 = t3301 - t5013
    acc5117 = 0.0
    t4563.each_with_index do |t5121, t5122|
      t5149 = t5121["lo"] || t5121[:lo]
      t5162 = t5121["hi"] || t5121[:hi]
      t5174 = t5121["rate"] || t5121[:rate]
      t5132 = t4588 - t5149
      t5155 = t5162 == t3325
      t5158 = t5155 ? t3327 : t5162
      t5136 = t5158 - t5149
      t5137 = [[ t5132, t3306 ].max, t5136 ].min
      t5125 = t5137 * t5174
      acc5117 += t5125
    end
    t5126 = acc5117
    t5111 = t5126 + t4756
    t5113 = t5111 + t3518
    t5115 = t5113 + t3521
    t5108 = t3301 - t5115
    t5105 = t5108 - t558
    t604 = {
      "federal" => t586,
      "fica" => t589,
      "state" => t549,
      "local" => t553,
      "total" => t600,
      "after_tax" => t5006,
      "retirement_contrib" => t558,
      "take_home" => t5105
    }
    t5229 = t3302["head_of_household"] || t3302[:head_of_household]
    t5230 = t5229["std"] || t5229[:std]
    t5231 = t3301 - t5230
    t5233 = [t5231, t3306]
    t5234 = t5233.max
    acc5206 = 0.0
    t5208 = t3281["head_of_household"] || t3281[:head_of_household]
    t5209 = t5208["rates"] || t5208[:rates]
    acc5275 = 0.0
    t5209.each_with_index do |t5210, t5211|
      t5246 = t5210["lo"] || t5210[:lo]
      t5259 = t5210["hi"] || t5210[:hi]
      t5267 = t5210["rate"] || t5210[:rate]
      t5223 = t5234 >= t5246
      t5252 = t5259 == t3325
      t5255 = t5252 ? t3327 : t5259
      t5225 = t5234 < t5255
      t5226 = t5223 && t5225
      t5215 = t5226 ? t5267 : t3306
      acc5206 += t5215
      t5290 = t5234 - t5246
      t5294 = t5255 - t5246
      t5295 = [[ t5290, t3306 ].max, t5294 ].min
      t5283 = t5295 * t5267
      acc5275 += t5283
    end
    t5216 = acc5206
    t5284 = acc5275
    t5273 = t5284 / t3346.to_f
    acc5334 = 0.0
    t5209.each_with_index do |t5338, t5339|
      t5366 = t5338["lo"] || t5338[:lo]
      t5379 = t5338["hi"] || t5338[:hi]
      t5391 = t5338["rate"] || t5338[:rate]
      t5349 = t5234 - t5366
      t5372 = t5379 == t3325
      t5375 = t5372 ? t3327 : t5379
      t5353 = t5375 - t5366
      t5354 = [[ t5349, t3306 ].max, t5353 ].min
      t5342 = t5354 * t5391
      acc5334 += t5342
    end
    t5343 = acc5334
    t608 = {
      "marginal" => t5216,
      "effective" => t5273,
      "tax" => t5343
    }
    acc5466 = 0.0
    t5209.each_with_index do |t5470, t5471|
      t5498 = t5470["lo"] || t5470[:lo]
      t5511 = t5470["hi"] || t5470[:hi]
      t5523 = t5470["rate"] || t5470[:rate]
      t5481 = t5234 - t5498
      t5504 = t5511 == t3325
      t5507 = t5504 ? t3327 : t5511
      t5485 = t5507 - t5498
      t5486 = [[ t5481, t3306 ].max, t5485 ].min
      t5474 = t5486 * t5523
      acc5466 += t5474
    end
    t5475 = acc5466
    t5460 = t5475 + t3476
    t5462 = t5460 + t3518
    t5464 = t5462 + t3521
    t5457 = t5464 / t3346.to_f
    acc5562 = 0.0
    t5209.each_with_index do |t5566, t5567|
      t5594 = t5566["lo"] || t5566[:lo]
      t5607 = t5566["hi"] || t5566[:hi]
      t5619 = t5566["rate"] || t5566[:rate]
      t5577 = t5234 - t5594
      t5600 = t5607 == t3325
      t5603 = t5600 ? t3327 : t5607
      t5581 = t5603 - t5594
      t5582 = [[ t5577, t3306 ].max, t5581 ].min
      t5570 = t5582 * t5619
      acc5562 += t5570
    end
    t5571 = acc5562
    t5556 = t5571 + t3476
    t5558 = t5556 + t3518
    t5560 = t5558 + t3521
    t622 = {
      "effective" => t5457,
      "tax" => t5560
    }
    acc5661 = 0.0
    t5209.each_with_index do |t5665, t5666|
      t5693 = t5665["lo"] || t5665[:lo]
      t5706 = t5665["hi"] || t5665[:hi]
      t5718 = t5665["rate"] || t5665[:rate]
      t5676 = t5234 - t5693
      t5699 = t5706 == t3325
      t5702 = t5699 ? t3327 : t5706
      t5680 = t5702 - t5693
      t5681 = [[ t5676, t3306 ].max, t5680 ].min
      t5669 = t5681 * t5718
      acc5661 += t5669
    end
    t5670 = acc5661
    t5655 = t5670 + t3476
    t5657 = t5655 + t3518
    t5659 = t5657 + t3521
    t5652 = t3301 - t5659
    acc5763 = 0.0
    t5209.each_with_index do |t5767, t5768|
      t5795 = t5767["lo"] || t5767[:lo]
      t5808 = t5767["hi"] || t5767[:hi]
      t5820 = t5767["rate"] || t5767[:rate]
      t5778 = t5234 - t5795
      t5801 = t5808 == t3325
      t5804 = t5801 ? t3327 : t5808
      t5782 = t5804 - t5795
      t5783 = [[ t5778, t3306 ].max, t5782 ].min
      t5771 = t5783 * t5820
      acc5763 += t5771
    end
    t5772 = acc5763
    t5757 = t5772 + t3476
    t5759 = t5757 + t3518
    t5761 = t5759 + t3521
    t5754 = t3301 - t5761
    t5751 = t5754 - t558
    t626 = {
      "federal" => t608,
      "fica" => t545,
      "state" => t549,
      "local" => t553,
      "total" => t622,
      "after_tax" => t5652,
      "retirement_contrib" => t558,
      "take_home" => t5751
    }
    t627 = {
      "single" => t560,
      "married_joint" => t582,
      "married_separate" => t604,
      "head_of_household" => t626
    }
    t627
  end
end
