# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :double then _double
    else raise KeyError, "Unknown declaration"
    end
  end

  def _double
    t1 = @input["x"]
    t2 = t1["y"]
    t3 = t2["z"]
    t5 = t3 * 2
    t5
  end
end
