# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_74e99814bc0b57a9643e32a4b9bfe6c82817f01606b045f3e584024d298ab322
  def self._double(input)
    t1 = input["x"] || input[:x]
    t2 = t1["y"] || t1[:y]
    t3 = t2["z"] || t2[:z]
    t4 = 2
    t3 * t4
  end
end
