# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_828578820f1f1a58e1e2eeaad09f06b89503ea9f58ca364a2b5d2440cb379ec1
  def self._double(input)
    t1 = input["x"] || input[:x]
    t2 = t1["y"] || t1[:y]
    t3 = t2["z"] || t2[:z]
    t3 * 2
  end
end
