# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_2260abe04114154d3961ca085f3e99181aa3ac57ba06128b4e81e84ee447d2db
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :double then _double
    else raise KeyError, "Unknown declaration"
    end
  end

  def _double(input = @input)
    t1 = input["x"] || input[:x]
    t2 = t1["y"] || t1[:y]
    t3 = t2["z"] || t2[:z]
    t4 = 2
    t3 * t4
  end
end
