// Autogenerated by Kumi Codegen for schema KUMI_2260abe04114154d3961ca085f3e99181aa3ac57ba06128b4e81e84ee447d2db
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'double': return this._double();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _double(input = this.input) {
    let t1 = input["x"];
    let t2 = t1.y;
    let t3 = t2.z;
    const t4 = 2;
    let t5 = t3 * t4;
    return t5;
  }

}
