// Autogenerated by Kumi Codegen for schema KUMI_6638f46fadb918fd0d9801db1cc74a8644071d3e15e8db0cebb4c1b7699ed811
export class KumiCompiledModule {
  _box(input) {
    let out = [];
    let t5 = input["x"];
    t5.forEach((x_el_6, x_i_7) => {
      let out_1 = [];
      let t29 = x_el_6.length;
      let t11 = x_i_7 * t29;
      x_el_6.forEach((y_el_8, y_i_9) => {
        let t12 = t11 + y_i_9;
        out_1.push(t12);
      });
      out.push(out_1);
    });
    return out;
  }

  _col_major(input) {
    let out = [];
    let t13 = input["x"];
    let t19 = t13.length;
    t13.forEach((x_el_14, x_i_15) => {
      let out_1 = [];
      x_el_14.forEach((y_el_16, y_i_17) => {
        let t20 = y_i_17 * t19;
        let t21 = t20 + x_i_15;
        out_1.push(t21);
      });
      out.push(out_1);
    });
    return out;
  }

  _sum_ij(input) {
    let out = [];
    let t22 = input["x"];
    t22.forEach((x_el_23, x_i_24) => {
      let out_1 = [];
      x_el_23.forEach((y_el_25, y_i_26) => {
        let t27 = x_i_24 + y_i_26;
        out_1.push(t27);
      });
      out.push(out_1);
    });
    return out;
  }

}
