# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_431ea5cd5181a00050c87deed45c5786cbfdf6464bbe3c025bf2da4e59bc2f4f
  def self._box(input)
    out = []
    t5 = input["x"] || input[:x]
    t5.each_with_index do |x_el_6, x_i_7|
      out_1 = []
      t29 = x_el_6.length
      t11 = x_i_7 * t29
      x_el_6.each_with_index do |y_el_8, y_i_9|
        t12 = t11 + y_i_9
        out_1 << t12
      end
      out << out_1
    end
    out
  end

  def self._col_major(input)
    out = []
    t13 = input["x"] || input[:x]
    t19 = t13.length
    t13.each_with_index do |x_el_14, x_i_15|
      out_1 = []
      x_el_14.each_with_index do |y_el_16, y_i_17|
        t20 = y_i_17 * t19
        t21 = t20 + x_i_15
        out_1 << t21
      end
      out << out_1
    end
    out
  end

  def self._sum_ij(input)
    out = []
    t22 = input["x"] || input[:x]
    t22.each_with_index do |x_el_23, x_i_24|
      out_1 = []
      x_el_23.each_with_index do |y_el_25, y_i_26|
        t27 = x_i_24 + y_i_26
        out_1 << t27
      end
      out << out_1
    end
    out
  end
end
