# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_65fd6b62741a9bb5be8cc780afaed94a8b4a69e3a863a66480fcbe2da5119577
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :app_name then _app_name
    when :all_flags then _all_flags
    when :server_hostnames then _server_hostnames
    when :server_count then _server_count
    when :total_ports then _total_ports
    else raise KeyError, "Unknown declaration"
    end
  end

  def _app_name(input = @input)
    t1 = input["config"] || input[:config]
    t1["app_name"] || t1[:app_name]
  end

  def _all_flags(input = @input)
    t3 = input["config"] || input[:config]
    t3["feature_flags"] || t3[:feature_flags]
  end

  def _server_hostnames(input = @input)
    out = []
    t5 = nil["config"] || nil[:config]
    t6 = t5["servers"] || t5[:servers]
    t6.each_with_index do |servers_el_7, servers_i_8|
      t9 = servers_el_7["hostname"] || servers_el_7[:hostname]
      out << t9
    end
    out
  end

  def _server_count(input = @input)
    t10 = input["config"] || input[:config]
    t11 = t10["servers"] || t10[:servers]
    t11.length
  end

  def _total_ports(input = @input)
    acc_13 = 0
    t14 = nil["config"] || nil[:config]
    t15 = t14["servers"] || t14[:servers]
    t15.each_with_index do |servers_el_16, servers_i_17|
      t18 = servers_el_16["port"] || servers_el_16[:port]
      acc_13 += t18
    end
    acc_13
  end
end
