// Autogenerated by Kumi Codegen for schema KUMI_2ef380124557e254c15bca5521c570bc0e24aafadc5c27f0e633ce665c72841d
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'app_name': return this._app_name();
      case 'all_flags': return this._all_flags();
      case 'server_hostnames': return this._server_hostnames();
      case 'server_count': return this._server_count();
      case 'total_ports': return this._total_ports();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _app_name(input = this.input) {
    let t1 = input["config"];
    let t2 = t1?.app_name;
    return t2;
  }

  _all_flags(input = this.input) {
    let t3 = input["config"];
    let t4 = t3?.feature_flags;
    return t4;
  }

  _server_hostnames(input = this.input) {
    let out = [];
    let t5 = input["config"];
    let t6 = t5?.servers;
    t6?.forEach((servers_el_7, servers_i_8) => {
      let t9 = servers_el_7?.hostname;
      out.push(t9);
    });
    return out;
  }

  _server_count(input = this.input) {
    let t10 = input["config"];
    let t11 = t10?.servers;
    let t12 = t11.length;
    return t12;
  }

  _total_ports(input = this.input) {
    let acc_13 = 0;
    let t14 = input["config"];
    let t15 = t14?.servers;
    t15?.forEach((servers_el_16, servers_i_17) => {
      let t18 = servers_el_16?.port;
      acc_13 += t18;
    });
    return acc_13;
  }

}
