# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e4d8c257f200bcd6fe2eb565f24fff1f547fe84f916bacd6b9179b69ca8a77b0
  def self._app_name(input)
    t3 = input["config"] || input[:config]
    t4 = t3["app_name"] || t3[:app_name]
    return t4
  end

  def self._all_flags(input)
    t6 = input["config"] || input[:config]
    t7 = t6["feature_flags"] || t6[:feature_flags]
    arr11 = []
    t7.each_with_index do |feature_flags_el8, feature_flags_i9|
      arr11 << feature_flags_el8
    end
    return arr11
  end

  def self._server_hostnames(input)
    t10 = input["config"] || input[:config]
    t11 = t10["servers"] || t10[:servers]
    arr16 = []
    t11.each_with_index do |servers_el12, servers_i13|
      t14 = servers_el12["hostname"] || servers_el12[:hostname]
      arr16 << t14
    end
    return arr16
  end

  def self._server_count(input)
    t13 = input["config"] || input[:config]
    t14 = t13["servers"] || t13[:servers]
    t12 = t14.length
    return t12
  end

  def self._total_ports(input)
    t18 = input["config"] || input[:config]
    t19 = t18["servers"] || t18[:servers]
    acc23 = 0
    t19.each_with_index do |servers_el20, servers_i21|
      t22 = servers_el20["port"] || servers_el20[:port]
      acc23 += t22
    end
    return acc23
  end
end
