# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_258f33c7f1c2ff232ede3b27da1338b635afb8f3ad97c453028b12f20598d7b6
  def self._scaled(input)
    t4 = input["x"] || input[:x]
    t5 = 10
    t3 = t4 * t5
    return t3
  end

  def self._affine(input)
    t9 = input["x"] || input[:x]
    t10 = 10
    t6 = t9 * t10
    t11 = 5
    t8 = t6 + t11
    return t8
  end
end
