# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_4b78bab715b79b3c4a8cc687a3dacf121d23e5c034510f5b38771ff817170994
  def self._scaled(input)
    t1 = input["x"] || input[:x]
    t1 * 10
  end

  def self._affine(input)
    t4 = input["x"] || input[:x]
    t6 = t4 * 10
    t6 + 5
  end
end
