# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_258f33c7f1c2ff232ede3b27da1338b635afb8f3ad97c453028b12f20598d7b6
  def self._scaled(input)
    t1 = input["x"] || input[:x]
    t1 * 10
  end

  def self._affine(input)
    t4 = input["x"] || input[:x]
    t6 = t4 * 10
    t6 + 5
  end
end
