# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_370ac782feb059e263a962e9d2c6b5de9914ae3e7636c3efdc00616eff6659b5
  def self._global_offset_plus(input)
    t4 = input["global_offset"] || input[:global_offset]
    t5 = 1.0
    t3 = t4 + t5
    return t3
  end

  def self._batch_bias(input)
    t13 = input["global_offset"] || input[:global_offset]
    t14 = 1.0
    t12 = t13 + t14
    t15 = input["batch"] || input[:batch]
    arr19 = []
    t15.each_with_index do |batch_el16, batch_i17|
      t18 = batch_el16["mean"] || batch_el16[:mean]
      t9 = t18 + t12
      arr19 << t9
    end
    return arr19
  end

  def self._row_scale2(input)
    t18 = input["batch"] || input[:batch]
    arr26 = []
    t18.each_with_index do |batch_el19, batch_i20|
      t21 = batch_el19["row"] || batch_el19[:row]
      arr27 = []
      t21.each_with_index do |row_el22, row_i23|
        t24 = row_el22["scale"] || row_el22[:scale]
        t25 = 2.0
        t17 = t24 * t25
        arr27 << t17
      end
      arr26 << arr27
    end
    return arr26
  end

  def self._elem_affine(input)
    t47 = input["batch"] || input[:batch]
    arr70 = []
    t47.each_with_index do |batch_el48, batch_i49|
      t50 = batch_el48["row"] || batch_el48[:row]
      arr71 = []
      t50.each_with_index do |row_el51, row_i52|
        t53 = row_el51["scale"] || row_el51[:scale]
        t54 = 2.0
        t38 = t53 * t54
        t55 = row_el51["col"] || row_el51[:col]
        arr72 = []
        t55.each_with_index do |col_el56, col_i57|
          t58 = col_el56["val"] || col_el56[:val]
          t27 = t58 * t38
          arr72 << t27
        end
        arr71 << arr72
      end
      arr70 << arr71
    end
    t59 = input["global_offset"] || input[:global_offset]
    t60 = 1.0
    t44 = t59 + t60
    arr76 = []
    t47.each_with_index do |batch_el61, batch_i62|
      t63 = batch_el61["mean"] || batch_el61[:mean]
      t46 = t63 + t44
      t64 = batch_el61["row"] || batch_el61[:row]
      arr77 = []
      t64.each_with_index do |row_el65, row_i66|
        t67 = row_el65["col"] || row_el65[:col]
        arr78 = []
        t67.each_with_index do |col_el68, col_i69|
          t73 = arr70[batch_i62]
          t74 = t73[row_i66]
          t75 = t74[col_i69]
          t30 = t75 + t46
          arr78 << t30
        end
        arr77 << arr78
      end
      arr76 << arr77
    end
    return arr76
  end

  def self._row_sum_affine(input)
    t60 = input["batch"] || input[:batch]
    arr83 = []
    t60.each_with_index do |batch_el61, batch_i62|
      t63 = batch_el61["row"] || batch_el61[:row]
      arr84 = []
      t63.each_with_index do |row_el64, row_i65|
        t66 = row_el64["scale"] || row_el64[:scale]
        t67 = 2.0
        t47 = t66 * t67
        t68 = row_el64["col"] || row_el64[:col]
        arr85 = []
        t68.each_with_index do |col_el69, col_i70|
          t71 = col_el69["val"] || col_el69[:val]
          t49 = t71 * t47
          arr85 << t49
        end
        arr84 << arr85
      end
      arr83 << arr84
    end
    t72 = input["global_offset"] || input[:global_offset]
    t73 = 1.0
    t55 = t72 + t73
    arr90 = []
    t60.each_with_index do |batch_el74, batch_i75|
      t76 = batch_el74["mean"] || batch_el74[:mean]
      t57 = t76 + t55
      t77 = batch_el74["row"] || batch_el74[:row]
      arr91 = []
      t77.each_with_index do |row_el78, row_i79|
        t80 = row_el78["col"] || row_el78[:col]
        acc89 = 0.0
        t80.each_with_index do |col_el81, col_i82|
          t86 = arr83[batch_i75]
          t87 = t86[row_i79]
          t88 = t87[col_i82]
          t59 = t88 + t57
          acc89 += t59
        end
        t32 = acc89
        arr91 << t32
      end
      arr90 << arr91
    end
    return arr90
  end

  def self._batch_total_affine(input)
    t63 = input["batch"] || input[:batch]
    arr86 = []
    t63.each_with_index do |batch_el64, batch_i65|
      t66 = batch_el64["row"] || batch_el64[:row]
      arr87 = []
      t66.each_with_index do |row_el67, row_i68|
        t69 = row_el67["scale"] || row_el67[:scale]
        t70 = 2.0
        t49 = t69 * t70
        t71 = row_el67["col"] || row_el67[:col]
        arr88 = []
        t71.each_with_index do |col_el72, col_i73|
          t74 = col_el72["val"] || col_el72[:val]
          t51 = t74 * t49
          arr88 << t51
        end
        arr87 << arr88
      end
      arr86 << arr87
    end
    t75 = input["global_offset"] || input[:global_offset]
    t76 = 1.0
    t57 = t75 + t76
    arr94 = []
    t63.each_with_index do |batch_el77, batch_i78|
      t79 = batch_el77["mean"] || batch_el77[:mean]
      t59 = t79 + t57
      t80 = batch_el77["row"] || batch_el77[:row]
      acc93 = 0.0
      t80.each_with_index do |row_el81, row_i82|
        t83 = row_el81["col"] || row_el81[:col]
        acc92 = 0.0
        t83.each_with_index do |col_el84, col_i85|
          t89 = arr86[batch_i78]
          t90 = t89[row_i82]
          t91 = t90[col_i85]
          t61 = t91 + t59
          acc92 += t61
        end
        t62 = acc92
        acc93 += t62
      end
      t34 = acc93
      arr94 << t34
    end
    return arr94
  end
end
