# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_f684eb32d324eba13b3675e15c6802b5690d74699289752d17776e156875a463
  def self._subtotal(input)
    t1 = input["item_price"] || input[:item_price]
    t2 = input["quantity"] || input[:quantity]
    t1 * t2
  end

  def self._price_after_discount(input)
    t12 = input["item_price"] || input[:item_price]
    t13 = input["quantity"] || input[:quantity]
    t14 = t12 * t13
    t5 = input["discount_rate"] || input[:discount_rate]
    Kumi::TestSharedSchemas::Price._discounted({"base_price" => t14, "discount_rate" => t5})
  end

  def self._discount_amt(input)
    t15 = input["item_price"] || input[:item_price]
    t16 = input["quantity"] || input[:quantity]
    t17 = t15 * t16
    t8 = input["discount_rate"] || input[:discount_rate]
    Kumi::TestSharedSchemas::Price._discount_amount({"base_price" => t17, "discount_rate" => t8})
  end

  def self._final_total(input)
    t21 = input["item_price"] || input[:item_price]
    t22 = input["quantity"] || input[:quantity]
    t23 = t21 * t22
    t19 = input["discount_rate"] || input[:discount_rate]
    t20 = Kumi::TestSharedSchemas::Price._discounted({"base_price" => t23, "discount_rate" => t19})
    Kumi::TestSharedSchemas::Tax._total({"amount" => t20})
  end
end
