# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :y_positive then _y_positive
    when :x_positive then _x_positive
    when :status then _status
    else raise KeyError, "Unknown declaration"
    end
  end

  def _y_positive
    t1 = @input["y"]
    t1 > 0
  end

  def _x_positive
    t4 = @input["x"]
    t4 > 0
  end

  def _status
    t19 = @input["y"]
    t21 = t19 > 0
    t22 = @input["x"]
    t24 = t22 > 0
    t9 = t21 && t24
    t16 = t21 ? "y positive" : "neither positive"
    t17 = t24 ? "x positive" : t16
    t9 ? "both positive" : t17
  end
end
