# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_cd81b9bfeb47f7e630314641ecfb0967f13fc313d96cacce162a6a0b3e6e02dc
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :y_positive then _y_positive
    when :x_positive then _x_positive
    when :status then _status
    else raise KeyError, "Unknown declaration"
    end
  end

  def _y_positive(input = @input)
    t1 = input["y"] || input[:y]
    t1 > 0
  end

  def _x_positive(input = @input)
    t4 = input["x"] || input[:x]
    t4 > 0
  end

  def _status(input = @input)
    t19 = input["y"] || input[:y]
    t21 = t19 > 0
    t22 = input["x"] || input[:x]
    t24 = t22 > 0
    t9 = t21 && t24
    t16 = t21 ? "y positive" : "neither positive"
    t17 = t24 ? "x positive" : t16
    t9 ? "both positive" : t17
  end
end
