# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e60e8afb47f1c86ac4f2de4020ddaf400fffed4cea5e472f6170855840fea947
  def self._y_positive(input)
    t1 = input["y"] || input[:y]
    t2 = 0
    t1 > t2
  end

  def self._x_positive(input)
    t4 = input["x"] || input[:x]
    t5 = 0
    t4 > t5
  end

  def self._status(input)
    t19 = input["y"] || input[:y]
    t20 = 0
    t21 = t19 > t20
    t22 = input["x"] || input[:x]
    t24 = t22 > t20
    t9 = t21 && t24
    t10 = "both positive"
    t12 = "x positive"
    t14 = "y positive"
    t15 = "neither positive"
    t16 = t21 ? t14 : t15
    t17 = t24 ? t12 : t16
    t9 ? t10 : t17
  end
end
