// Autogenerated by Kumi Codegen for schema KUMI_95342262fa1616b51bf1787ff509e7346889e099ebded0247cb7fae98826f68b
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'y_positive': return this._y_positive();
      case 'x_positive': return this._x_positive();
      case 'status': return this._status();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _y_positive(input = this.input) {
    let t1 = input["y"];
    let t3 = t1 > 0;
    return t3;
  }

  _x_positive(input = this.input) {
    let t4 = input["x"];
    let t6 = t4 > 0;
    return t6;
  }

  _status(input = this.input) {
    let t19 = input["y"];
    let t21 = t19 > 0;
    let t22 = input["x"];
    let t24 = t22 > 0;
    let t9 = t21 && t24;
    let t16 = t21 ? "y positive" : "neither positive";
    let t17 = t24 ? "x positive" : t16;
    let t18 = t9 ? "both positive" : t17;
    return t18;
  }

}
