// Autogenerated by Kumi Codegen for schema KUMI_9f3dac48d8026a1a83834f69c098561a57a3f1589ddb0335ac970aa70bea0d99
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'y_positive': return this._y_positive();
      case 'x_positive': return this._x_positive();
      case 'status': return this._status();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _y_positive(input = this.input) {
    let t1 = input["y"];
    const t2 = 0;
    let t3 = t1 > t2;
    return t3;
  }

  _x_positive(input = this.input) {
    let t4 = input["x"];
    const t5 = 0;
    let t6 = t4 > t5;
    return t6;
  }

  _status(input = this.input) {
    let t19 = input["y"];
    const t20 = 0;
    let t21 = t19 > t20;
    let t22 = input["x"];
    let t24 = t22 > t20;
    let t9 = t21 && t24;
    const t10 = "both positive";
    const t12 = "x positive";
    const t14 = "y positive";
    const t15 = "neither positive";
    let t16 = t21 ? t14 : t15;
    let t17 = t24 ? t12 : t16;
    let t18 = t9 ? t10 : t17;
    return t18;
  }

}
