# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_bfadf7e4e122e3c34f7c4e295b15d28e4885544b894edff59173316f9d0fc6c6
  def self._order_subtotals(input)
    t10 = input["orders"] || input[:orders]
    arr19 = []
    t10.each_with_index do |orders_el11, orders_i12|
      t13 = orders_el11["items"] || orders_el11[:items]
      acc18 = 0
      t13.each_with_index do |items_el14, items_i15|
        t16 = items_el14["quantity"] || items_el14[:quantity]
        t17 = items_el14["unit_price"] || items_el14[:unit_price]
        t8 = t16 * t17
        acc18 += t8
      end
      arr19 << acc18
    end
    return arr19
  end

  def self._order_with_shipping(input)
    t19 = input["orders"] || input[:orders]
    arr29 = []
    t19.each_with_index do |orders_el20, orders_i21|
      t22 = orders_el20["items"] || orders_el20[:items]
      acc27 = 0
      t22.each_with_index do |items_el23, items_i24|
        t25 = items_el23["quantity"] || items_el23[:quantity]
        t26 = items_el23["unit_price"] || items_el23[:unit_price]
        t17 = t25 * t26
        acc27 += t17
      end
      t28 = orders_el20["shipping_cost"] || orders_el20[:shipping_cost]
      t9 = acc27 + t28
      arr29 << t9
    end
    return arr29
  end

  def self._order_discounted(input)
    t30 = input["orders"] || input[:orders]
    arr42 = []
    t30.each_with_index do |orders_el31, orders_i32|
      t33 = orders_el31["items"] || orders_el31[:items]
      acc38 = 0
      t33.each_with_index do |items_el34, items_i35|
        t36 = items_el34["quantity"] || items_el34[:quantity]
        t37 = items_el34["unit_price"] || items_el34[:unit_price]
        t25 = t36 * t37
        acc38 += t25
      end
      t39 = orders_el31["shipping_cost"] || orders_el31[:shipping_cost]
      t21 = acc38 + t39
      t40 = 1.0
      t41 = input["global_discount_rate"] || input[:global_discount_rate]
      t28 = t40 - t41
      t29 = t21 * t28
      arr42 << t29
    end
    return arr42
  end

  def self._order_tax(input)
    t37 = input["orders"] || input[:orders]
    arr50 = []
    t37.each_with_index do |orders_el38, orders_i39|
      t40 = orders_el38["items"] || orders_el38[:items]
      acc45 = 0
      t40.each_with_index do |items_el41, items_i42|
        t43 = items_el41["quantity"] || items_el41[:quantity]
        t44 = items_el41["unit_price"] || items_el41[:unit_price]
        t30 = t43 * t44
        acc45 += t30
      end
      t46 = orders_el38["shipping_cost"] || orders_el38[:shipping_cost]
      t23 = acc45 + t46
      t47 = 1.0
      t48 = input["global_discount_rate"] || input[:global_discount_rate]
      t33 = t47 - t48
      t34 = t23 * t33
      t49 = 0.15
      t36 = t34 * t49
      arr50 << t36
    end
    return arr50
  end

  def self._order_totals(input)
    t52 = input["orders"] || input[:orders]
    arr65 = []
    t52.each_with_index do |orders_el53, orders_i54|
      t55 = orders_el53["items"] || orders_el53[:items]
      acc60 = 0
      t55.each_with_index do |items_el56, items_i57|
        t58 = items_el56["quantity"] || items_el56[:quantity]
        t59 = items_el56["unit_price"] || items_el56[:unit_price]
        t45 = t58 * t59
        acc60 += t45
      end
      t61 = orders_el53["shipping_cost"] || orders_el53[:shipping_cost]
      t26 = acc60 + t61
      t62 = 1.0
      t63 = input["global_discount_rate"] || input[:global_discount_rate]
      t48 = t62 - t63
      t49 = t26 * t48
      t64 = 0.15
      t51 = t49 * t64
      t18 = t49 + t51
      arr65 << t18
    end
    return arr65
  end

  def self._discount_per_order(input)
    t49 = input["orders"] || input[:orders]
    arr61 = []
    t49.each_with_index do |orders_el50, orders_i51|
      t52 = orders_el50["items"] || orders_el50[:items]
      acc57 = 0
      t52.each_with_index do |items_el53, items_i54|
        t55 = items_el53["quantity"] || items_el53[:quantity]
        t56 = items_el53["unit_price"] || items_el53[:unit_price]
        t44 = t55 * t56
        acc57 += t44
      end
      t58 = orders_el50["shipping_cost"] || orders_el50[:shipping_cost]
      t29 = acc57 + t58
      t59 = 1.0
      t60 = input["global_discount_rate"] || input[:global_discount_rate]
      t47 = t59 - t60
      t48 = t29 * t47
      t21 = t29 - t48
      arr61 << t21
    end
    return arr61
  end

  def self._total_orders(input)
    t26 = input["orders"] || input[:orders]
    acc30 = 0
    t26.each_with_index do |orders_el27, orders_i28|
      t29 = orders_el27["id"] || orders_el27[:id]
      acc30 += 1
    end
    return acc30
  end

  def self._total_revenue(input)
    t62 = input["orders"] || input[:orders]
    acc75 = 0
    t62.each_with_index do |orders_el63, orders_i64|
      t65 = orders_el63["items"] || orders_el63[:items]
      acc70 = 0
      t65.each_with_index do |items_el66, items_i67|
        t68 = items_el66["quantity"] || items_el66[:quantity]
        t69 = items_el66["unit_price"] || items_el66[:unit_price]
        t55 = t68 * t69
        acc70 += t55
      end
      t71 = orders_el63["shipping_cost"] || orders_el63[:shipping_cost]
      t35 = acc70 + t71
      t72 = 1.0
      t73 = input["global_discount_rate"] || input[:global_discount_rate]
      t58 = t72 - t73
      t59 = t35 * t58
      t74 = 0.15
      t61 = t59 * t74
      t51 = t59 + t61
      acc75 += t51
    end
    return acc75
  end

  def self._total_tax_collected(input)
    t52 = input["orders"] || input[:orders]
    acc65 = 0
    t52.each_with_index do |orders_el53, orders_i54|
      t55 = orders_el53["items"] || orders_el53[:items]
      acc60 = 0
      t55.each_with_index do |items_el56, items_i57|
        t58 = items_el56["quantity"] || items_el56[:quantity]
        t59 = items_el56["unit_price"] || items_el56[:unit_price]
        t45 = t58 * t59
        acc60 += t45
      end
      t61 = orders_el53["shipping_cost"] || orders_el53[:shipping_cost]
      t37 = acc60 + t61
      t62 = 1.0
      t63 = input["global_discount_rate"] || input[:global_discount_rate]
      t48 = t62 - t63
      t49 = t37 * t48
      t64 = 0.15
      t51 = t49 * t64
      acc65 += t51
    end
    return acc65
  end

  def self._total_discount_given(input)
    t60 = input["orders"] || input[:orders]
    acc72 = 0
    t60.each_with_index do |orders_el61, orders_i62|
      t63 = orders_el61["items"] || orders_el61[:items]
      acc68 = 0
      t63.each_with_index do |items_el64, items_i65|
        t66 = items_el64["quantity"] || items_el64[:quantity]
        t67 = items_el64["unit_price"] || items_el64[:unit_price]
        t55 = t66 * t67
        acc68 += t55
      end
      t69 = orders_el61["shipping_cost"] || orders_el61[:shipping_cost]
      t39 = acc68 + t69
      t70 = 1.0
      t71 = input["global_discount_rate"] || input[:global_discount_rate]
      t58 = t70 - t71
      t59 = t39 * t58
      t51 = t39 - t59
      acc72 += t51
    end
    return acc72
  end
end
