# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :scores then _scores
    when :first_score then _first_score
    when :second_score then _second_score
    else raise KeyError, "Unknown declaration"
    end
  end

  def _scores
    t4 = [100, 85, 92]
    t4
  end

  def _first_score
    100
  end

  def _second_score
    85
  end
end
