# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_5108af24d012f937e1c0316f75655a9577ee8e16e0b0867506c94ceb7237ae46
  def self._scores(input)
    [100, 85, 92]
  end

  def self._first_score(input)
    100
  end

  def self._second_score(input)
    85
  end
end
