// Autogenerated by Kumi Codegen for schema KUMI_17c28e1c1b3e46c489818a3be7ac12b0b504aa216e67796f805c201d74dcc30b
export class KumiCompiledModule {
  constructor(inputData = {}) {
    this.input = inputData;
  }

  static from(inputData = {}) {
    return new KumiCompiledModule(inputData);
  }

  update(inputData) {
    this.input = { ...this.input, ...inputData };
    return this;
  }

  get(name) {
    switch (name) {
      case 'scores': return this._scores();
      case 'first_score': return this._first_score();
      case 'second_score': return this._second_score();
      default: throw new Error(`Unknown declaration: ${name}`);
    }
  }

  _scores(input = this.input) {
    let t4 = [100, 85, 92];
    return t4;
  }

  _first_score(input = this.input) {
    return 100;
  }

  _second_score(input = this.input) {
    return 85;
  }

}
