# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_0ce5f86204199ff9a2beaf1e46e12ef4e985e33592c7078322bbca76859205ad
  def self._scores(input)
    t1 = 100
    t2 = 85
    t3 = 92
    [t1, t2, t3]
  end

  def self._first_score(input)
    100
  end

  def self._second_score(input)
    85
  end
end
