# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_0ba39954d9ebec17bc256d8d133a5bf61df0265e70e6cf0c8a02029e5cdeaf37
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :scores then _scores
    when :first_score then _first_score
    when :second_score then _second_score
    else raise KeyError, "Unknown declaration"
    end
  end

  def _scores(input = @input)
    [100, 85, 92]
  end

  def _first_score(input = @input)
    100
  end

  def _second_score(input = @input)
    85
  end
end
