// Autogenerated by Kumi Codegen for schema KUMI_35feff0172e3bbb3744ba19849fea0941b2edca34a7f4ecc56497afded53d9d8
export class KumiCompiledModule {
  _scores(input) {
    const t1 = 100;
    const t2 = 85;
    const t3 = 92;
    let t4 = [t1, t2, t3];
    return t4;
  }

  _first_score(input) {
    const t5 = 100;
    return t5;
  }

  _second_score(input) {
    const t6 = 85;
    return t6;
  }

}
