# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_74ec580a26866eae33665ff6d21bc0deac9b3466ec2066c2c777a8ee86f941b4
  def self._order_subtotals(input)
    t10 = input["orders"] || input[:orders]
    arr19 = []
    t10.each_with_index do |orders_el11, orders_i12|
      t13 = orders_el11["items"] || orders_el11[:items]
      acc18 = 0
      t13.each_with_index do |items_el14, items_i15|
        t16 = items_el14["quantity"] || items_el14[:quantity]
        t17 = items_el14["unit_price"] || items_el14[:unit_price]
        t8 = t16 * t17
        acc18 += t8
      end
      t9 = acc18
      arr19 << t9
    end
    return arr19
  end

  def self._total_before_tax(input)
    t16 = input["orders"] || input[:orders]
    acc25 = 0
    t16.each_with_index do |orders_el17, orders_i18|
      t19 = orders_el17["items"] || orders_el17[:items]
      acc24 = 0
      t19.each_with_index do |items_el20, items_i21|
        t22 = items_el20["quantity"] || items_el20[:quantity]
        t23 = items_el20["unit_price"] || items_el20[:unit_price]
        t14 = t22 * t23
        acc24 += t14
      end
      t15 = acc24
      acc25 += t15
    end
    t6 = acc25
    return t6
  end

  def self._tax_for_all(input)
    t21 = input["orders"] || input[:orders]
    acc30 = 0
    t21.each_with_index do |orders_el22, orders_i23|
      t24 = orders_el22["items"] || orders_el22[:items]
      acc29 = 0
      t24.each_with_index do |items_el25, items_i26|
        t27 = items_el25["quantity"] || items_el25[:quantity]
        t28 = items_el25["unit_price"] || items_el25[:unit_price]
        t17 = t27 * t28
        acc29 += t17
      end
      t18 = acc29
      acc30 += t18
    end
    t13 = acc30
    t31 = 0.15
    t20 = t13 * t31
    return t20
  end

  def self._grand_total(input)
    t30 = input["orders"] || input[:orders]
    acc39 = 0
    t30.each_with_index do |orders_el31, orders_i32|
      t33 = orders_el31["items"] || orders_el31[:items]
      acc38 = 0
      t33.each_with_index do |items_el34, items_i35|
        t36 = items_el34["quantity"] || items_el34[:quantity]
        t37 = items_el34["unit_price"] || items_el34[:unit_price]
        t26 = t36 * t37
        acc38 += t26
      end
      t27 = acc38
      acc39 += t27
    end
    t16 = acc39
    t40 = 0.15
    t29 = t16 * t40
    t11 = t16 + t29
    return t11
  end
end
