# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_495a358d9548909f41dac105cd52b6740c91569c281f3bdc36b0b6d61dc0851e
  def self._region_max(input)
    t7 = input["regions"] || input[:regions]
    arr15 = []
    t7.each_with_index do |regions_el8, regions_i9|
      t10 = regions_el8["sales"] || regions_el8[:sales]
      acc14 = nil
      t10.each_with_index do |sales_el11, sales_i12|
        t13 = sales_el11["amount"] || sales_el11[:amount]
        acc14 ||= t13
        acc14 = t13 if !t13.nil? && t13 > acc14
      end
      t6 = acc14
      arr15 << t6
    end
    return arr15
  end

  def self._region_min(input)
    t13 = input["regions"] || input[:regions]
    arr21 = []
    t13.each_with_index do |regions_el14, regions_i15|
      t16 = regions_el14["sales"] || regions_el14[:sales]
      acc20 = nil
      t16.each_with_index do |sales_el17, sales_i18|
        t19 = sales_el17["amount"] || sales_el17[:amount]
        acc20 ||= t19
        acc20 = t19 if !t19.nil? && t19 < acc20
      end
      t12 = acc20
      arr21 << t12
    end
    return arr21
  end

  def self._region_labels(input)
    t19 = input["regions"] || input[:regions]
    arr27 = []
    t19.each_with_index do |regions_el20, regions_i21|
      t22 = regions_el20["tags"] || regions_el20[:tags]
      acc26 = ""
      t22.each_with_index do |tags_el23, tags_i24|
        t25 = tags_el23["label"] || tags_el23[:label]
        acc26 += t25
      end
      t18 = acc26
      arr27 << t18
    end
    return arr27
  end

  def self._best_region_sale(input)
    t27 = input["regions"] || input[:regions]
    acc35 = nil
    t27.each_with_index do |regions_el28, regions_i29|
      t30 = regions_el28["sales"] || regions_el28[:sales]
      acc34 = nil
      t30.each_with_index do |sales_el31, sales_i32|
        t33 = sales_el31["amount"] || sales_el31[:amount]
        acc34 ||= t33
        acc34 = t33 if !t33.nil? && t33 > acc34
      end
      t26 = acc34
      acc35 ||= t26
      acc35 = t26 if !t26.nil? && t26 > acc35
    end
    t20 = acc35
    return t20
  end

  def self._worst_region_sale(input)
    t29 = input["regions"] || input[:regions]
    acc37 = nil
    t29.each_with_index do |regions_el30, regions_i31|
      t32 = regions_el30["sales"] || regions_el30[:sales]
      acc36 = nil
      t32.each_with_index do |sales_el33, sales_i34|
        t35 = sales_el33["amount"] || sales_el33[:amount]
        acc36 ||= t35
        acc36 = t35 if !t35.nil? && t35 < acc36
      end
      t28 = acc36
      acc37 ||= t28
      acc37 = t28 if !t28.nil? && t28 < acc37
    end
    t22 = acc37
    return t22
  end
end
