# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_a4afbfa25df6e01af4477832d8792f1a58ebc258d3858857b89ebcd9a23ec2c2
  def self._price_with_bonus(input)
    out = []
    t1 = input["items"] || input[:items]
    t1.each_with_index do |items_el_2, items_i_3|
      t4 = items_el_2["price"] || items_el_2[:price]
      t6 = [t4, 10]
      out << t6
    end
    out
  end
end
