# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_809efb9f30ef9472747d03f1e4bc722f400c9cff00bb918955a9aa66ae335c65
  def self._price_with_bonus(input)
    t6 = input["items"] || input[:items]
    arr11 = []
    t6.each_with_index do |items_el7, items_i8|
      t9 = items_el7["price"] || items_el7[:price]
      t10 = 10
      t5 = [t9, t10]
      arr11 << t5
    end
    return arr11
  end
end
