# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_a4afbfa25df6e01af4477832d8792f1a58ebc258d3858857b89ebcd9a23ec2c2
  def self._price_with_bonus(input)
    t6 = input["items"] || input[:items]
    arr11 = []
    t6.each_with_index do |items_el7, items_i8|
      t9 = items_el7["price"] || items_el7[:price]
      t10 = 10
      t5 = [t9, t10]
      arr11 << t5
    end
    return arr11
  end
end
