# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_991dd9e1497577901bcaee6a4ae8b50420a5fb4d07aca713a31a01d8aa47f6e6
  def self._total_payroll(input)
    t7 = input["departments"] || input[:departments]
    arr15 = []
    t7.each_with_index do |departments_el8, departments_i9|
      t10 = departments_el8["employees"] || departments_el8[:employees]
      acc14 = 0
      t10.each_with_index do |employees_el11, employees_i12|
        t13 = employees_el11["salary"] || employees_el11[:salary]
        acc14 += t13
      end
      t6 = acc14
      arr15 << t6
    end
    return arr15
  end

  def self._manager_count(input)
    t21 = input["departments"] || input[:departments]
    arr32 = []
    t21.each_with_index do |departments_el22, departments_i23|
      t24 = departments_el22["employees"] || departments_el22[:employees]
      acc31 = 0
      t24.each_with_index do |employees_el25, employees_i26|
        t27 = employees_el25["role"] || employees_el25[:role]
        t28 = "manager"
        t14 = t27 == t28
        t29 = 1
        t30 = 0
        t19 = t14 ? t29 : t30
        acc31 += t19
      end
      t20 = acc31
      arr32 << t20
    end
    return arr32
  end

  def self._department_summary(input)
    t47 = input["departments"] || input[:departments]
    arr61 = []
    t47.each_with_index do |departments_el48, departments_i49|
      t50 = departments_el48["employees"] || departments_el48[:employees]
      acc54 = 0
      acc59 = 0
      t50.each_with_index do |employees_el51, employees_i52|
        t53 = employees_el51["salary"] || employees_el51[:salary]
        acc54 += t53
        t55 = employees_el51["role"] || employees_el51[:role]
        t56 = "manager"
        t40 = t55 == t56
        t57 = 1
        t58 = 0
        t45 = t40 ? t57 : t58
        acc59 += t45
      end
      t32 = acc54
      t46 = acc59
      t60 = departments_el48["name"] || departments_el48[:name]
      t26 = { "name" => t60, "total_payroll" => t32, "manager_count" => t46 }
      arr61 << t26
    end
    return arr61
  end
end
