# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_87d4478777cfb00d94e5097e8457df82162d447c3cbbba41dd85a1ca7c72e250
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :total_payroll then _total_payroll
    when :manager_count then _manager_count
    when :senior_employee_count then _senior_employee_count
    when :max_salary then _max_salary
    when :department_summary then _department_summary
    else raise KeyError, "Unknown declaration"
    end
  end

  def _total_payroll(input = @input)
    out = []
    t1 = input["departments"] || input[:departments]
    t1.each_with_index do |departments_el_2, departments_i_3|
      acc_4 = 0
      t5 = departments_el_2["employees"] || departments_el_2[:employees]
      t5.each_with_index do |employees_el_6, employees_i_7|
        t8 = employees_el_6["salary"] || employees_el_6[:salary]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _manager_count(input = @input)
    out = []
    t10 = input["departments"] || input[:departments]
    t18 = "manager"
    t20 = 1
    t21 = 0
    t10.each_with_index do |departments_el_11, departments_i_12|
      acc_13 = 0
      t14 = departments_el_11["employees"] || departments_el_11[:employees]
      t14.each_with_index do |employees_el_15, employees_i_16|
        t17 = employees_el_15["role"] || employees_el_15[:role]
        t19 = t17 == t18
        t22 = t19 ? t20 : t21
        acc_13 += t22
      end
      t23 = acc_13
      out << t23
    end
    out
  end

  def _senior_employee_count(input = @input)
    out = []
    t24 = input["departments"] || input[:departments]
    t32 = "senior"
    t34 = 1
    t35 = 0
    t24.each_with_index do |departments_el_25, departments_i_26|
      acc_27 = 0
      t28 = departments_el_25["employees"] || departments_el_25[:employees]
      t28.each_with_index do |employees_el_29, employees_i_30|
        t31 = employees_el_29["role"] || employees_el_29[:role]
        t33 = t31 == t32
        t36 = t33 ? t34 : t35
        acc_27 += t36
      end
      t37 = acc_27
      out << t37
    end
    out
  end

  def _max_salary(input = @input)
    out = []
    t38 = input["departments"] || input[:departments]
    t38.each_with_index do |departments_el_39, departments_i_40|
      acc_41 = nil
      t42 = departments_el_39["employees"] || departments_el_39[:employees]
      t42.each_with_index do |employees_el_43, employees_i_44|
        t45 = employees_el_43["salary"] || employees_el_43[:salary]
        acc_41 ||= t45
        acc_41 = t45 if t45 > acc_41
      end
      t46 = acc_41
      out << t46
    end
    out
  end

  def _department_summary(input = @input)
    out = []
    t47 = input["departments"] || input[:departments]
    t71 = "manager"
    t73 = 1
    t74 = 0
    t84 = "senior"
    t47.each_with_index do |departments_el_48, departments_i_49|
      t50 = departments_el_48["name"] || departments_el_48[:name]
      acc58 = 0
      t59 = departments_el_48["employees"] || departments_el_48[:employees]
      acc66 = 0
      acc79 = 0
      acc92 = nil
      t59.each_with_index do |t60, t61|
        t62 = t60["salary"] || t60[:salary]
        acc58 += t62
        t70 = t60["role"] || t60[:role]
        t72 = t70 == t71
        t75 = t72 ? t73 : t74
        acc66 += t75
        acc92 ||= t62
        acc92 = t62 if t62 > acc92
        t85 = t70 == t84
        t88 = t85 ? t73 : t74
        acc79 += t88
      end
      t63 = acc58
      t76 = acc66
      t97 = acc92
      t89 = acc79
      t55 = {
        "name" => t50,
        "total_payroll" => t63,
        "manager_count" => t76,
        "senior_count" => t89,
        "top_salary" => t97
      }
      out << t55
    end
    out
  end
end
