# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_68e1e4a6f2c80cbdc8a4d9acad3d72335ba503d325ebe80d7e734d9cc822ca24
  def self._total_payroll(input)
    t7 = input["departments"] || input[:departments]
    arr15 = []
    t7.each_with_index do |departments_el8, departments_i9|
      t10 = departments_el8["employees"] || departments_el8[:employees]
      acc14 = 0
      t10.each_with_index do |employees_el11, employees_i12|
        t13 = employees_el11["salary"] || employees_el11[:salary]
        acc14 += t13
      end
      t6 = acc14
      arr15 << t6
    end
    return arr15
  end

  def self._manager_count(input)
    t21 = input["departments"] || input[:departments]
    arr32 = []
    t21.each_with_index do |departments_el22, departments_i23|
      t24 = departments_el22["employees"] || departments_el22[:employees]
      acc31 = 0
      t24.each_with_index do |employees_el25, employees_i26|
        t27 = employees_el25["role"] || employees_el25[:role]
        t28 = "manager"
        t14 = t27 == t28
        t29 = 1
        t30 = 0
        t19 = t14 ? t29 : t30
        acc31 += t19
      end
      t20 = acc31
      arr32 << t20
    end
    return arr32
  end

  def self._senior_employee_count(input)
    t35 = input["departments"] || input[:departments]
    arr46 = []
    t35.each_with_index do |departments_el36, departments_i37|
      t38 = departments_el36["employees"] || departments_el36[:employees]
      acc45 = 0
      t38.each_with_index do |employees_el39, employees_i40|
        t41 = employees_el39["role"] || employees_el39[:role]
        t42 = "senior"
        t28 = t41 == t42
        t43 = 1
        t44 = 0
        t33 = t28 ? t43 : t44
        acc45 += t33
      end
      t34 = acc45
      arr46 << t34
    end
    return arr46
  end

  def self._max_salary(input)
    t41 = input["departments"] || input[:departments]
    arr49 = []
    t41.each_with_index do |departments_el42, departments_i43|
      t44 = departments_el42["employees"] || departments_el42[:employees]
      acc48 = nil
      t44.each_with_index do |employees_el45, employees_i46|
        t47 = employees_el45["salary"] || employees_el45[:salary]
        acc48 ||= t47
        acc48 = t47 if !t47.nil? && t47 > acc48
      end
      t40 = acc48
      arr49 << t40
    end
    return arr49
  end

  def self._department_summary(input)
    t89 = input["departments"] || input[:departments]
    arr106 = []
    t89.each_with_index do |departments_el90, departments_i91|
      t92 = departments_el90["employees"] || departments_el90[:employees]
      acc96 = 0
      acc101 = 0
      acc103 = 0
      acc104 = nil
      t92.each_with_index do |employees_el93, employees_i94|
        t95 = employees_el93["salary"] || employees_el93[:salary]
        acc96 += t95
        t97 = employees_el93["role"] || employees_el93[:role]
        t98 = "manager"
        t62 = t97 == t98
        t99 = 1
        t100 = 0
        t67 = t62 ? t99 : t100
        acc101 += t67
        t102 = "senior"
        t76 = t97 == t102
        t81 = t76 ? t99 : t100
        acc103 += t81
        acc104 ||= t95
        acc104 = t95 if !t95.nil? && t95 > acc104
      end
      t54 = acc96
      t68 = acc101
      t82 = acc103
      t88 = acc104
      t105 = departments_el90["name"] || departments_el90[:name]
      t48 = { "name" => t105, "total_payroll" => t54, "manager_count" => t68, "senior_count" => t82, "top_salary" => t88 }
      arr106 << t48
    end
    return arr106
  end
end
