# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_47dbfa52aa1681915309557581518df358397f3e545db4cbadbdd1d4a11b894a
  def self._total_payroll(input)
    t7 = input["departments"] || input[:departments]
    arr15 = []
    t7.each_with_index do |departments_el8, departments_i9|
      t10 = departments_el8["employees"] || departments_el8[:employees]
      acc14 = 0
      t10.each_with_index do |employees_el11, employees_i12|
        t13 = employees_el11["salary"] || employees_el11[:salary]
        acc14 += t13
      end
      arr15 << acc14
    end
    return arr15
  end

  def self._payroll_tax(input)
    t17 = input["departments"] || input[:departments]
    arr26 = []
    t17.each_with_index do |departments_el18, departments_i19|
      t20 = departments_el18["employees"] || departments_el18[:employees]
      acc24 = 0
      t20.each_with_index do |employees_el21, employees_i22|
        t23 = employees_el21["salary"] || employees_el21[:salary]
        acc24 += t23
      end
      t25 = 0.15
      t10 = acc24 * t25
      arr26 << t10
    end
    return arr26
  end

  def self._manager_count(input)
    t25 = input["departments"] || input[:departments]
    arr36 = []
    t25.each_with_index do |departments_el26, departments_i27|
      t28 = departments_el26["employees"] || departments_el26[:employees]
      acc35 = 0
      t28.each_with_index do |employees_el29, employees_i30|
        t31 = employees_el29["role"] || employees_el29[:role]
        t32 = "manager"
        t18 = t31 == t32
        t33 = 1
        t34 = 0
        t23 = t18 ? t33 : t34
        acc35 += t23
      end
      arr36 << acc35
    end
    return arr36
  end

  def self._department_summary(input)
    t61 = input["departments"] || input[:departments]
    arr78 = []
    t61.each_with_index do |departments_el62, departments_i63|
      t64 = departments_el62["employees"] || departments_el62[:employees]
      acc68 = 0
      t64.each_with_index do |employees_el65, employees_i66|
        t67 = employees_el65["salary"] || employees_el65[:salary]
        acc68 += t67
      end
      t69 = 0.15
      t46 = acc68 * t69
      acc76 = 0
      t64.each_with_index do |employees_el70, employees_i71|
        t72 = employees_el70["role"] || employees_el70[:role]
        t73 = "manager"
        t54 = t72 == t73
        t74 = 1
        t75 = 0
        t59 = t54 ? t74 : t75
        acc76 += t59
      end
      t77 = departments_el62["name"] || departments_el62[:name]
      t31 = { "name" => t77, "payroll" => acc68, "tax" => t46, "managers" => acc76 }
      arr78 << t31
    end
    return arr78
  end
end
