# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_1523dc98fbf6f178f956575880c9b428b21c19aa91a7822a35e277983da843a8
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :total_payroll then _total_payroll
    when :payroll_tax then _payroll_tax
    when :manager_count then _manager_count
    when :department_summary then _department_summary
    else raise KeyError, "Unknown declaration"
    end
  end

  def _total_payroll(input = @input)
    out = []
    t1 = input["departments"] || input[:departments]
    t1.each_with_index do |departments_el_2, departments_i_3|
      acc_4 = 0
      t5 = departments_el_2["employees"] || departments_el_2[:employees]
      t5.each_with_index do |employees_el_6, employees_i_7|
        t8 = employees_el_6["salary"] || employees_el_6[:salary]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _payroll_tax(input = @input)
    out = []
    t10 = input["departments"] || input[:departments]
    t14 = 0.15
    t10.each_with_index do |departments_el_11, departments_i_12|
      acc40 = 0
      t41 = departments_el_11["employees"] || departments_el_11[:employees]
      t41.each_with_index do |employees_el_6, employees_i_7|
        t42 = employees_el_6["salary"] || employees_el_6[:salary]
        acc40 += t42
      end
      t43 = acc40
      t15 = t43 * t14
      out << t15
    end
    out
  end

  def _manager_count(input = @input)
    out = []
    t16 = input["departments"] || input[:departments]
    t24 = "manager"
    t26 = 1
    t27 = 0
    t16.each_with_index do |departments_el_17, departments_i_18|
      acc_19 = 0
      t20 = departments_el_17["employees"] || departments_el_17[:employees]
      t20.each_with_index do |employees_el_21, employees_i_22|
        t23 = employees_el_21["role"] || employees_el_21[:role]
        t25 = t23 == t24
        t28 = t25 ? t26 : t27
        acc_19 += t28
      end
      t29 = acc_19
      out << t29
    end
    out
  end

  def _department_summary(input = @input)
    out = []
    t30 = input["departments"] || input[:departments]
    t52 = 0.15
    t59 = "manager"
    t61 = 1
    t62 = 0
    t30.each_with_index do |departments_el_31, departments_i_32|
      t33 = departments_el_31["name"] || departments_el_31[:name]
      acc46 = 0
      t47 = departments_el_31["employees"] || departments_el_31[:employees]
      acc67 = 0
      acc56 = 0
      t47.each_with_index do |employees_el_6, employees_i_7|
        t48 = employees_el_6["salary"] || employees_el_6[:salary]
        acc46 += t48
        t58 = employees_el_6["role"] || employees_el_6[:role]
        t60 = t58 == t59
        t63 = t60 ? t61 : t62
        acc56 += t63
        acc67 += t48
      end
      t49 = acc46
      t64 = acc56
      t70 = acc67
      t53 = t70 * t52
      t37 = {
        "name" => t33,
        "payroll" => t49,
        "tax" => t53,
        "managers" => t64
      }
      out << t37
    end
    out
  end
end
