# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_babd0dd6c79515b0ea177f8a303874051c0f1c81ff6d57e90002a1cc4a6da663
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :total_payroll then _total_payroll
    when :payroll_tax then _payroll_tax
    when :manager_count then _manager_count
    when :department_summary then _department_summary
    else raise KeyError, "Unknown declaration"
    end
  end

  def _total_payroll(input = @input)
    out = []
    t1 = input["departments"] || input[:departments]
    t1.each_with_index do |departments_el_2, departments_i_3|
      acc_4 = 0
      t5 = departments_el_2["employees"] || departments_el_2[:employees]
      t5.each_with_index do |employees_el_6, employees_i_7|
        t8 = employees_el_6["salary"] || employees_el_6[:salary]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _payroll_tax(input = @input)
    out = []
    t10 = input["departments"] || input[:departments]
    t14 = 0.15
    t10.each_with_index do |departments_el_11, departments_i_12|
      acc40 = 0
      t41 = departments_el_11["employees"] || departments_el_11[:employees]
      t41.each_with_index do |t42, t43|
        t44 = t42["salary"] || t42[:salary]
        acc40 += t44
      end
      t45 = acc40
      t15 = t45 * t14
      out << t15
    end
    out
  end

  def _manager_count(input = @input)
    out = []
    t16 = input["departments"] || input[:departments]
    t24 = "manager"
    t26 = 1
    t27 = 0
    t16.each_with_index do |departments_el_17, departments_i_18|
      acc_19 = 0
      t20 = departments_el_17["employees"] || departments_el_17[:employees]
      t20.each_with_index do |employees_el_21, employees_i_22|
        t23 = employees_el_21["role"] || employees_el_21[:role]
        t25 = t23 == t24
        t28 = t25 ? t26 : t27
        acc_19 += t28
      end
      t29 = acc_19
      out << t29
    end
    out
  end

  def _department_summary(input = @input)
    out = []
    t30 = input["departments"] || input[:departments]
    t56 = 0.15
    t73 = "manager"
    t75 = 1
    t76 = 0
    t30.each_with_index do |departments_el_31, departments_i_32|
      t33 = departments_el_31["name"] || departments_el_31[:name]
      acc48 = 0
      t49 = departments_el_31["employees"] || departments_el_31[:employees]
      acc60 = 0
      acc68 = 0
      t49.each_with_index do |t50, t51|
        t52 = t50["salary"] || t50[:salary]
        acc48 += t52
        acc60 += t52
        t72 = t50["role"] || t50[:role]
        t74 = t72 == t73
        t77 = t74 ? t75 : t76
        acc68 += t77
      end
      t53 = acc48
      t65 = acc60
      t78 = acc68
      t57 = t65 * t56
      t37 = {
        "name" => t33,
        "payroll" => t53,
        "tax" => t57,
        "managers" => t78
      }
      out << t37
    end
    out
  end
end
