# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_178400032daee9a2aab79a4193b1237e41dcf4149f31a26c285326bbb3f09077
  def self._xi(input)
    t4 = input["bodies"] || input[:bodies]
    arr9 = []
    t4.each_with_index do |bodies_el5, bodies_i6|
      t7 = bodies_el5["x"] || bodies_el5[:x]
      t8 = t7
      arr9 << t8
    end
    return arr9
  end

  def self._xj(input)
    t8 = input["bodies"] || input[:bodies]
    arr15 = []
    t8.each_with_index do |bodies_el9, bodies_i10|
      t11 = input["bodies"] || input[:bodies]
      arr16 = []
      t11.each_with_index do |bodies__x_el12, bodies__x_i13|
        t14 = bodies__x_el12["x"] || bodies__x_el12[:x]
        t4 = t14
        arr16 << t4
      end
      arr15 << arr16
    end
    return arr15
  end

  def self._mj(input)
    t12 = input["bodies"] || input[:bodies]
    arr19 = []
    t12.each_with_index do |bodies_el13, bodies_i14|
      t15 = input["bodies"] || input[:bodies]
      arr20 = []
      t15.each_with_index do |bodies__x_el16, bodies__x_i17|
        t18 = bodies__x_el16["m"] || bodies__x_el16[:m]
        t8 = t18
        arr20 << t8
      end
      arr19 << arr20
    end
    return arr19
  end

  def self._dx(input)
    t20 = input["bodies"] || input[:bodies]
    arr28 = []
    t20.each_with_index do |bodies_el21, bodies_i22|
      t23 = input["bodies"] || input[:bodies]
      arr29 = []
      t23.each_with_index do |bodies__x_el24, bodies__x_i25|
        t26 = bodies__x_el24["x"] || bodies__x_el24[:x]
        t19 = t26
        t27 = bodies_el21["x"] || bodies_el21[:x]
        t15 = t19 - t27
        arr29 << t15
      end
      arr28 << arr29
    end
    return arr28
  end

  def self._dist(input)
    t30 = input["bodies"] || input[:bodies]
    arr39 = []
    t30.each_with_index do |bodies_el31, bodies_i32|
      t33 = input["bodies"] || input[:bodies]
      arr40 = []
      t33.each_with_index do |bodies__x_el34, bodies__x_i35|
        t36 = bodies__x_el34["x"] || bodies__x_el34[:x]
        t24 = t36
        t37 = bodies_el31["x"] || bodies_el31[:x]
        t29 = t24 - t37
        t17 = t29.abs
        t38 = input["eps"] || input[:eps]
        t20 = t17 + t38
        arr40 << t20
      end
      arr39 << arr40
    end
    return arr39
  end

  def self._accel(input)
    t57 = input["bodies"] || input[:bodies]
    arr68 = []
    t57.each_with_index do |bodies_el58, bodies_i59|
      t60 = input["bodies"] || input[:bodies]
      acc67 = 0.0
      t60.each_with_index do |bodies__x_el61, bodies__x_i62|
        t63 = bodies__x_el61["m"] || bodies__x_el61[:m]
        t34 = t63
        t64 = bodies__x_el61["x"] || bodies__x_el61[:x]
        t38 = t64
        t65 = bodies_el58["x"] || bodies_el58[:x]
        t43 = t38 - t65
        t23 = t34 * t43
        t53 = t43.abs
        t66 = input["eps"] || input[:eps]
        t56 = t53 + t66
        t26 = t56 * t56
        t28 = t26 * t56
        t29 = t23 / t28.to_f
        acc67 += t29
      end
      t30 = acc67
      arr68 << t30
    end
    return arr68
  end
end
