# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_f854489d5d34a8a14974d5699298d08e14bb3f9afb911e4aeea716bcb1347583
  def self._tax_result(input)
    t5 = input["amount"] || input[:amount]
    t6 = 0.15
    t4 = t5 * t6
    return t4
  end

  def self._total(input)
    t10 = input["amount"] || input[:amount]
    t11 = 0.15
    t9 = t10 * t11
    t5 = t10 + t9
    return t5
  end
end
