# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_eae980d089061584dbf8f13913be1c5420118493b1516eac6786bee17ffc405c
  def self._tax_result(input)
    t5 = input["amount"] || input[:amount]
    t6 = 0.15
    t4 = t5 * t6
    return t4
  end

  def self._total(input)
    t10 = input["amount"] || input[:amount]
    t11 = 0.15
    t9 = t10 * t11
    t5 = t10 + t9
    return t5
  end
end
