# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_3b83797e064b22309eff67138129e50624eb40b86791d4566b28462b0e350351
  def __kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input_data = input_data
  end

  def self.from(input_data=nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :sum then _sum
    when :product then _product
    when :difference then _difference
    when :results_array then _results_array
    else raise KeyError, "Unknown declaration"
    end
  end

  def _sum(input=@input)
    t1 = input["x"]
    t2 = input["y"]
    t1 + t2
  end

  def _product(input=@input)
    t4 = input["x"]
    t5 = input["y"]
    t4 * t5
  end

  def _difference(input=@input)
    t7 = input["x"]
    t8 = input["y"]
    t7 - t8
  end

  def _results_array(input=@input)
    t11 = input["x"]
    t13 = t11 + 10
    t14 = input["y"]
    t16 = t14 * 2
    [1, t13, t16]
  end
end
