# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_eae791dd08425eb940da71053204fe698c64131a118c70874455885b240f9256
  def self._sum(input)
    t4 = input["x"] || input[:x]
    t5 = input["y"] || input[:y]
    t3 = t4 + t5
    return t3
  end

  def self._product(input)
    t7 = input["x"] || input[:x]
    t8 = input["y"] || input[:y]
    t6 = t7 * t8
    return t6
  end

  def self._difference(input)
    t10 = input["x"] || input[:x]
    t11 = input["y"] || input[:y]
    t9 = t10 - t11
    return t9
  end

  def self._results_array(input)
    t18 = input["x"] || input[:x]
    t19 = 10
    t13 = t18 + t19
    t20 = input["y"] || input[:y]
    t21 = 2
    t16 = t20 * t21
    t22 = 1
    t17 = [t22, t13, t16]
    return t17
  end
end
