# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_dc70ebf961e35d148a1771999a042997fd23872bb143255018cc54b56f5f5d05
  def self._sum(input)
    t1 = input["x"] || input[:x]
    t2 = input["y"] || input[:y]
    t1 + t2
  end

  def self._product(input)
    t4 = input["x"] || input[:x]
    t5 = input["y"] || input[:y]
    t4 * t5
  end

  def self._difference(input)
    t7 = input["x"] || input[:x]
    t8 = input["y"] || input[:y]
    t7 - t8
  end

  def self._results_array(input)
    t10 = 1
    t11 = input["x"] || input[:x]
    t12 = 10
    t13 = t11 + t12
    t14 = input["y"] || input[:y]
    t15 = 2
    t16 = t14 * t15
    [t10, t13, t16]
  end
end
