// Autogenerated by Kumi Codegen for schema KUMI_df62108323660e038ce71a4d1b9bbc5d949d9b4bd8d28416546e3208f456d829
export class KumiCompiledModule {
  _sum(input) {
    let t1 = input["x"];
    let t2 = input["y"];
    let t3 = t1 + t2;
    return t3;
  }

  _product(input) {
    let t4 = input["x"];
    let t5 = input["y"];
    let t6 = t4 * t5;
    return t6;
  }

  _difference(input) {
    let t7 = input["x"];
    let t8 = input["y"];
    let t9 = t7 - t8;
    return t9;
  }

  _results_array(input) {
    const t10 = 1;
    let t11 = input["x"];
    const t12 = 10;
    let t13 = t11 + t12;
    let t14 = input["y"];
    const t15 = 2;
    let t16 = t14 * t15;
    let t17 = [t10, t13, t16];
    return t17;
  }

}
