# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_2cc0d4995a6ab48f043223e68294bb087bd5c87764dce8424f4a0d531b6534bc
  def self._ln_x(input)
    t1 = input["x"] || input[:x]
    Math.log(t1)
  end
end
