# frozen_string_literal: true

module Kumi
  module Core
    module Analyzer
      module Passes
        module Codegen
          module Ruby
            class OutputBuffer
              def initialize
                @out = []
                @indent = 0
              end

              def to_s = @out.join
              def reset! = @out.clear

              def indent!
                @indent += 1
              end

              def dedent!
                @indent -= 1
              end

              def emit_header
                write "# Autogenerated by Kumi Codegen"
                write "module SchemaModule"
                indent!
              end

              def emit_footer
                dedent!
                write "end"
              end

              def emit_class_methods(decl_names)
                write "def self.from(input_data)"
                indented do
                  write "instance = Object.new"
                  write "instance.extend(self)"
                  write "instance.instance_variable_set(:@input, input_data)"
                  write "instance"
                end
                write "end\n"

                write "def [](name)"
                indented do
                  write "case name"
                  decl_names.each { |name| write "when :#{name} then _eval_#{name}", @indent + 1 }
                  write "else raise KeyError, \"Unknown declaration\"", @indent + 1
                  write "end"
                end
                write "end\n"
              end

              def section(name)
                write "#{name}\n"
                yield
              end

              def indented
                indent!
                yield
                dedent!
              end

              def write(s, indent = @indent)
                @out << ("  " * indent) << s << "\n"
              end
            end
          end
        end
      end
    end
  end
end
