# frozen_string_literal: true

require_relative "ops/node"
require_relative "ops/constant"
require_relative "ops/load_input"
require_relative "ops/load_field"
require_relative "ops/map"
require_relative "ops/select"
require_relative "ops/axis_shift"
require_relative "ops/axis_broadcast"
require_relative "ops/array_build"
require_relative "ops/axis_index"
require_relative "ops/fold"
require_relative "ops/decl_ref"
require_relative "ops/loop_start"
require_relative "ops/loop_end"
require_relative "ops/reduce"
require_relative "ops/import_call"
require_relative "ops/make_tuple"
require_relative "ops/yield"
