# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_14a66b4f40e6421e57ad27ddcc06aba6186998019aab60bf8e87259528c95d53
  def self._total_value(input)
    t5 = input["items"] || input[:items]
    acc9 = 0
    t5.each_with_index do |items_el6, items_i7|
      t8 = items_el6["value"] || items_el6[:value]
      acc9 += t8
    end
    return acc9
  end

  def self._half_total(input)
    t12 = input["items"] || input[:items]
    acc16 = 0
    t12.each_with_index do |items_el13, items_i14|
      t15 = items_el13["value"] || items_el13[:value]
      acc16 += t15
    end
    t17 = 0.5
    t7 = acc16 * t17
    return t7
  end

  def self._high_value_sum(input)
    t27 = input["items"] || input[:items]
    acc31 = 0
    t27.each_with_index do |items_el28, items_i29|
      t30 = items_el28["value"] || items_el28[:value]
      acc31 += t30
    end
    t32 = 0.5
    t26 = acc31 * t32
    acc37 = 0
    t27.each_with_index do |items_el33, items_i34|
      t35 = items_el33["value"] || items_el33[:value]
      t13 = t35 > t26
      t36 = 0
      t19 = t13 ? t35 : t36
      acc37 += t19
    end
    return acc37
  end
end
