# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_723430f06cee2395fb5c5ec8ecc54794ce2f4d9931180cc50f4e012b7bd3969a
  def self._total_value(input)
    acc_1 = 0
    t2 = input["items"] || input[:items]
    t2.each_with_index do |items_el_3, items_i_4|
      t5 = items_el_3["value"] || items_el_3[:value]
      acc_1 += t5
    end
    acc_1
  end

  def self._half_total(input)
    acc22 = 0
    t23 = input["items"] || input[:items]
    t23.each_with_index do |t24, t25|
      t26 = t24["value"] || t24[:value]
      acc22 += t26
    end
    t27 = acc22
    t27 * 0.5
  end

  def self._high_value_sum(input)
    acc_10 = 0
    t11 = input["items"] || input[:items]
    acc32 = 0
    t11.each_with_index do |t34, t35|
      t36 = t34["value"] || t34[:value]
      acc32 += t36
    end
    t37 = acc32
    t30 = t37 * 0.5
    t11.each_with_index do |items_el_12, items_i_13|
      t14 = items_el_12["value"] || items_el_12[:value]
      t16 = t14 > t30
      t19 = t16 ? t14 : 0
      acc_10 += t19
    end
    acc_10
  end
end
