// Autogenerated by Kumi Codegen for schema KUMI_36744177cdca80fe4a508bf0af34cd8474bf232f192b273175d697342f45e382
export class KumiCompiledModule {
  _dept_total(input) {
    let out = [];
    let t1 = input["depts"];
    t1.forEach((depts_el_2, depts_i_3) => {
      let acc_4 = 0;
      depts_el_2.forEach((teams_el_5, teams_i_6) => {
        acc_4 += teams_el_5;
      });
      out.push(acc_4);
    });
    return out;
  }

  _company_total(input) {
    let acc_8 = 0;
    let t9 = input["depts"];
    t9.forEach((depts_el_10, depts_i_11) => {
      let acc_12 = 0;
      depts_el_10.forEach((teams_el_13, teams_i_14) => {
        acc_12 += teams_el_13;
      });
      acc_8 += acc_12;
    });
    return acc_8;
  }

  _big_team(input) {
    let out = [];
    let t17 = input["depts"];
    const t22 = 10;
    t17.forEach((depts_el_18, depts_i_19) => {
      let out_1 = [];
      depts_el_18.forEach((teams_el_20, teams_i_21) => {
        let t23 = teams_el_20 > t22;
        out_1.push(t23);
      });
      out.push(out_1);
    });
    return out;
  }

  _dept_total_masked(input) {
    let out = [];
    let t24 = input["depts"];
    const t35 = 10;
    const t31 = 0;
    t24.forEach((depts_el_25, depts_i_26) => {
      let acc_27 = 0;
      depts_el_25.forEach((teams_el_28, teams_i_29) => {
        let t36 = teams_el_28 > t35;
        let t32 = t36 ? teams_el_28 : t31;
        acc_27 += t32;
      });
      out.push(acc_27);
    });
    return out;
  }

}
