# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_119cc0f8a00c98d2c8f40118e2303f491340f895bba53041b192c3728ed62a6a
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :dept_total then _dept_total
    when :company_total then _company_total
    when :big_team then _big_team
    when :dept_total_masked then _dept_total_masked
    else raise KeyError, "Unknown declaration"
    end
  end

  def _dept_total(input = @input)
    out = []
    t1 = input["depts"] || input[:depts]
    t1.each_with_index do |depts_el_2, depts_i_3|
      acc_4 = 0
      t5 = depts_el_2["teams"] || depts_el_2[:teams]
      t5.each_with_index do |teams_el_6, teams_i_7|
        t8 = teams_el_6["headcount"] || teams_el_6[:headcount]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _company_total(input = @input)
    acc_10 = 0
    t11 = input["depts"] || input[:depts]
    t11.each_with_index do |depts_el_12, depts_i_13|
      acc_14 = 0
      t15 = depts_el_12["teams"] || depts_el_12[:teams]
      t15.each_with_index do |teams_el_16, teams_i_17|
        t18 = teams_el_16["headcount"] || teams_el_16[:headcount]
        acc_14 += t18
      end
      t19 = acc_14
      acc_10 += t19
    end
    acc_10
  end

  def _big_team(input = @input)
    out = []
    t21 = input["depts"] || input[:depts]
    t28 = 10
    t21.each_with_index do |depts_el_22, depts_i_23|
      out_1 = []
      t24 = depts_el_22["teams"] || depts_el_22[:teams]
      t24.each_with_index do |teams_el_25, teams_i_26|
        t27 = teams_el_25["headcount"] || teams_el_25[:headcount]
        t29 = t27 > t28
        out_1 << t29
      end
      out << out_1
    end
    out
  end

  def _dept_total_masked(input = @input)
    out = []
    t30 = input["depts"] || input[:depts]
    t45 = 10
    t39 = 0
    t30.each_with_index do |depts_el_31, depts_i_32|
      acc_33 = 0
      t34 = depts_el_31["teams"] || depts_el_31[:teams]
      t34.each_with_index do |teams_el_35, teams_i_36|
        t44 = teams_el_35["headcount"] || teams_el_35[:headcount]
        t46 = t44 > t45
        t40 = t46 ? t44 : t39
        acc_33 += t40
      end
      t41 = acc_33
      out << t41
    end
    out
  end
end
