# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_55d1e2d3bdf7c5cb9495c31da47c848746b659a18759b72f19b02c45ac47c581
  def self._items_subtotal(input)
    t8 = input["items"] || input[:items]
    arr13 = []
    t8.each_with_index do |items_el9, items_i10|
      t11 = items_el9["price"] || items_el9[:price]
      t12 = items_el9["qty"] || items_el9[:qty]
      t7 = t11 * t12
      arr13 << t7
    end
    return arr13
  end

  def self._items_discounted(input)
    t16 = 1.0
    t17 = input["discount"] || input[:discount]
    t13 = t16 - t17
    t18 = input["items"] || input[:items]
    arr22 = []
    t18.each_with_index do |items_el19, items_i20|
      t21 = items_el19["price"] || items_el19[:price]
      t15 = t21 * t13
      arr22 << t15
    end
    return arr22
  end

  def self._items_is_big(input)
    t22 = input["items"] || input[:items]
    arr27 = []
    t22.each_with_index do |items_el23, items_i24|
      t25 = items_el23["price"] || items_el23[:price]
      t26 = 100.0
      t21 = t25 > t26
      arr27 << t21
    end
    return arr27
  end

  def self._items_effective(input)
    t42 = input["items"] || input[:items]
    arr49 = []
    t42.each_with_index do |items_el43, items_i44|
      t45 = items_el43["price"] || items_el43[:price]
      t46 = 100.0
      t34 = t45 > t46
      t47 = items_el43["qty"] || items_el43[:qty]
      t41 = t45 * t47
      t48 = 0.9
      t26 = t41 * t48
      t28 = t34 ? t26 : t41
      arr49 << t28
    end
    return arr49
  end

  def self._total_qty(input)
    t33 = input["items"] || input[:items]
    acc37 = 0
    t33.each_with_index do |items_el34, items_i35|
      t36 = items_el34["qty"] || items_el34[:qty]
      acc37 += t36
    end
    t32 = acc37
    return t32
  end

  def self._cart_total(input)
    t42 = input["items"] || input[:items]
    acc47 = 0.0
    t42.each_with_index do |items_el43, items_i44|
      t45 = items_el43["price"] || items_el43[:price]
      t46 = items_el43["qty"] || items_el43[:qty]
      t41 = t45 * t46
      acc47 += t41
    end
    t34 = acc47
    return t34
  end

  def self._cart_total_effective(input)
    t61 = input["items"] || input[:items]
    acc68 = 0.0
    t61.each_with_index do |items_el62, items_i63|
      t64 = items_el62["price"] || items_el62[:price]
      t65 = 100.0
      t42 = t64 > t65
      t66 = items_el62["qty"] || items_el62[:qty]
      t49 = t64 * t66
      t67 = 0.9
      t52 = t49 * t67
      t60 = t42 ? t52 : t49
      acc68 += t60
    end
    t36 = acc68
    return t36
  end
end
