# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_a344287fc06d62ff25c9d430589975a02b44be7149533f4d58bc4e8f5f103e9f
  def self._items_subtotal(input)
    out = []
    t1 = input["items"] || input[:items]
    t1.each_with_index do |items_el_2, items_i_3|
      t4 = items_el_2["price"] || items_el_2[:price]
      t5 = items_el_2["qty"] || items_el_2[:qty]
      t6 = t4 * t5
      out << t6
    end
    out
  end

  def self._items_discounted(input)
    out = []
    t7 = input["items"] || input[:items]
    t11 = 1.0
    t12 = input["discount"] || input[:discount]
    t13 = t11 - t12
    t7.each_with_index do |items_el_8, items_i_9|
      t10 = items_el_8["price"] || items_el_8[:price]
      t14 = t10 * t13
      out << t14
    end
    out
  end

  def self._items_is_big(input)
    out = []
    t15 = input["items"] || input[:items]
    t19 = 100.0
    t15.each_with_index do |items_el_16, items_i_17|
      t18 = items_el_16["price"] || items_el_16[:price]
      t20 = t18 > t19
      out << t20
    end
    out
  end

  def self._items_effective(input)
    out = []
    t21 = input["items"] || input[:items]
    t50 = 100.0
    t26 = 0.9
    t21.each_with_index do |items_el_22, items_i_23|
      t49 = items_el_22["price"] || items_el_22[:price]
      t54 = items_el_22["qty"] || items_el_22[:qty]
      t51 = t49 > t50
      t55 = t49 * t54
      t27 = t55 * t26
      t29 = t51 ? t27 : t55
      out << t29
    end
    out
  end

  def self._total_qty(input)
    acc_30 = 0.0
    t31 = input["items"] || input[:items]
    t31.each_with_index do |items_el_32, items_i_33|
      t34 = items_el_32["qty"] || items_el_32[:qty]
      acc_30 += t34
    end
    acc_30
  end

  def self._cart_total(input)
    acc_36 = 0.0
    t37 = input["items"] || input[:items]
    t37.each_with_index do |items_el_38, items_i_39|
      t61 = items_el_38["price"] || items_el_38[:price]
      t62 = items_el_38["qty"] || items_el_38[:qty]
      t63 = t61 * t62
      acc_36 += t63
    end
    acc_36
  end

  def self._cart_total_effective(input)
    acc_42 = 0.0
    t43 = input["items"] || input[:items]
    t73 = 100.0
    t67 = 0.9
    t43.each_with_index do |items_el_44, items_i_45|
      t72 = items_el_44["price"] || items_el_44[:price]
      t77 = items_el_44["qty"] || items_el_44[:qty]
      t74 = t72 > t73
      t78 = t72 * t77
      t68 = t78 * t67
      t70 = t74 ? t68 : t78
      acc_42 += t70
    end
    acc_42
  end
end
