# Autogenerated by Kumi Codegen
module SchemaModule
  def self.from(input_data)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def [](name)
    case name
    when :dept_headcount then _dept_headcount
    when :teams_per_dept then _teams_per_dept
    when :avg_headcount_per_dept then _avg_headcount_per_dept
    when :is_above_average_team then _is_above_average_team
    else raise KeyError, "Unknown declaration"
    end
  end

  def _dept_headcount
    out = []
    t1 = @input["departments"]
    t1.each_with_index do |departments_el_2, _departments_i_3|
      acc_4 = 0
      t5 = departments_el_2["teams"]
      t5.each_with_index do |teams_el_6, _teams_i_7|
        t8 = teams_el_6["headcount"]
        acc_4 += t8
      end
      t9 = acc_4
      out << t9
    end
    out
  end

  def _teams_per_dept
    out = []
    t10 = @input["departments"]
    t10.each_with_index do |departments_el_11, _departments_i_12|
      acc_13 = 0
      t14 = departments_el_11["teams"]
      t14.each_with_index do |teams_el_15, _teams_i_16|
        t17 = teams_el_15["team_name"]
        acc_13 += 1
      end
      t18 = acc_13
      out << t18
    end
    out
  end

  def _avg_headcount_per_dept
    out = []
    t19 = @input["departments"]
    t19.each_with_index do |departments_el_20, _departments_i_21|
      acc36 = 0
      t37 = departments_el_20["teams"]
      t37.each_with_index do |teams_el_6, _teams_i_7|
        t38 = teams_el_6["headcount"]
        acc36 += t38
      end
      t39 = acc36
      acc42 = 0
      t37.each_with_index do |teams_el_15, _teams_i_16|
        t44 = teams_el_15["team_name"]
        acc42 += 1
      end
      t45 = acc42
      t24 = t39 / t45
      out << t24
    end
    out
  end

  def _is_above_average_team
    out = []
    t25 = @input["departments"]
    t25.each_with_index do |departments_el_26, _departments_i_27|
      out_1 = []
      t28 = departments_el_26["teams"]
      acc52 = 0
      t28.each_with_index do |teams_el_6, _teams_i_7|
        t54 = teams_el_6["headcount"]
        acc52 += t54
      end
      t55 = acc52
      acc58 = 0
      t28.each_with_index do |teams_el_15, _teams_i_16|
        t60 = teams_el_15["team_name"]
        acc58 += 1
      end
      t61 = acc58
      t49 = t55 / t61
      t28.each_with_index do |teams_el_29, _teams_i_30|
        t31 = teams_el_29["headcount"]
        t33 = t31 > t49
        out_1 << t33
      end
      out << out_1
    end
    out
  end
end
