# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_cb65f5b72457bc6c2c00039c4c245397b40bacb3ddd05447b83a371478af94e1
  def self._dept_headcount(input)
    t7 = input["departments"] || input[:departments]
    arr15 = []
    t7.each_with_index do |departments_el8, departments_i9|
      t10 = departments_el8["teams"] || departments_el8[:teams]
      acc14 = 0
      t10.each_with_index do |teams_el11, teams_i12|
        t13 = teams_el11["headcount"] || teams_el11[:headcount]
        acc14 += t13
      end
      arr15 << acc14
    end
    return arr15
  end

  def self._teams_per_dept(input)
    t13 = input["departments"] || input[:departments]
    arr21 = []
    t13.each_with_index do |departments_el14, departments_i15|
      t16 = departments_el14["teams"] || departments_el14[:teams]
      acc20 = 0
      t16.each_with_index do |teams_el17, teams_i18|
        t19 = teams_el17["team_name"] || teams_el17[:team_name]
        acc20 += 1
      end
      arr21 << acc20
    end
    return arr21
  end

  def self._avg_headcount_per_dept(input)
    t28 = input["departments"] || input[:departments]
    arr38 = []
    t28.each_with_index do |departments_el29, departments_i30|
      t31 = departments_el29["teams"] || departments_el29[:teams]
      acc35 = 0
      acc37 = 0
      t31.each_with_index do |teams_el32, teams_i33|
        t34 = teams_el32["headcount"] || teams_el32[:headcount]
        acc35 += t34
        t36 = teams_el32["team_name"] || teams_el32[:team_name]
        acc37 += 1
      end
      t15 = acc35 / acc37.to_f
      arr38 << t15
    end
    return arr38
  end

  def self._is_above_average_team(input)
    t37 = input["departments"] || input[:departments]
    arr50 = []
    t37.each_with_index do |departments_el38, departments_i39|
      t40 = departments_el38["teams"] || departments_el38[:teams]
      acc44 = 0
      acc46 = 0
      t40.each_with_index do |teams_el41, teams_i42|
        t43 = teams_el41["headcount"] || teams_el41[:headcount]
        acc44 += t43
        t45 = teams_el41["team_name"] || teams_el41[:team_name]
        acc46 += 1
      end
      t36 = acc44 / acc46.to_f
      arr51 = []
      t40.each_with_index do |teams_el47, teams_i48|
        t49 = teams_el47["headcount"] || teams_el47[:headcount]
        t23 = t49 > t36
        arr51 << t23
      end
      arr50 << arr51
    end
    return arr50
  end
end
