# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_68f4eddfaff654547ab5cc255f2967d355341b0897b614578dddd6fd9e25c7b8
  def self.from(input_data = nil)
    instance = Object.new
    instance.extend(self)
    instance.instance_variable_set(:@input, input_data)
    instance
  end

  def self.__kumi_executable__
    instance = Object.new
    instance.extend(self)
    instance
  end

  def update(input_data)
    @input = @input.merge(input_data)
    self
  end

  def [](name)
    case name
    when :distance then _distance
    else raise KeyError, "Unknown declaration"
    end
  end

  def _distance(input = @input)
    t22 = input["x"] || input[:x]
    t24 = t22 * t22
    t25 = input["y"] || input[:y]
    t27 = t25 * t25
    t21 = t24 + t27
    t11 = 0.5
    t21 ** t11
  end
end
