# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_e1770a87f5908c45ce123c37f83a13dd10f3651397af4f75453392061c62fb24
  def self._users(input)
    out = []
    t1 = input["users"] || input[:users]
    t1.each_with_index do |users_el_2, users_i_3|
      t4 = users_el_2["name"] || users_el_2[:name]
      t5 = users_el_2["state"] || users_el_2[:state]
      t6 = {
        "name" => t4,
        "state" => t5
      }
      out << t6
    end
    out
  end

  def self._is_john(input)
    out = []
    t7 = input["users"] || input[:users]
    t7.each_with_index do |users_el_8, users_i_9|
      t10 = users_el_8["name"] || users_el_8[:name]
      t12 = t10 == "John"
      out << t12
    end
    out
  end

  def self._john_user(input)
    out = []
    t13 = input["users"] || input[:users]
    t13.each_with_index do |users_el_14, users_i_15|
      t21 = users_el_14["name"] || users_el_14[:name]
      t26 = users_el_14["state"] || users_el_14[:state]
      t23 = t21 == "John"
      t27 = {
        "name" => t21,
        "state" => t26
      }
      t19 = t23 ? t27 : "NOT_JOHN"
      out << t19
    end
    out
  end
end
