# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_6c14f403d34353e2f46b1a752fa0674c9bb49f21c279e29bb58de69c2aabcd08
  def self._users(input)
    t8 = input["users"] || input[:users]
    arr13 = []
    t8.each_with_index do |users_el9, users_i10|
      t11 = users_el9["name"] || users_el9[:name]
      t12 = users_el9["state"] || users_el9[:state]
      t7 = { "name" => t11, "state" => t12 }
      arr13 << t7
    end
    return arr13
  end

  def self._is_john(input)
    t14 = input["users"] || input[:users]
    arr19 = []
    t14.each_with_index do |users_el15, users_i16|
      t17 = users_el15["name"] || users_el15[:name]
      t18 = "John"
      t13 = t17 == t18
      arr19 << t13
    end
    return arr19
  end

  def self._john_user(input)
    t32 = input["users"] || input[:users]
    arr39 = []
    t32.each_with_index do |users_el33, users_i34|
      t35 = users_el33["name"] || users_el33[:name]
      t36 = "John"
      t24 = t35 == t36
      t37 = users_el33["state"] || users_el33[:state]
      t31 = { "name" => t35, "state" => t37 }
      t38 = "NOT_JOHN"
      t18 = t24 ? t31 : t38
      arr39 << t18
    end
    return arr39
  end
end
