# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_9fe49ee74f21b1768dbc6a50c1231a6d0d0c7a7e0d1fe3aee6d69faa1260ec86
  def self._e(input)
    t5 = input["xs"] || input[:xs]
    arr9 = []
    t5.each_with_index do |xs_el6, xs_i7|
      t8 = xs_el6["v"] || xs_el6[:v]
      t4 = Math.exp(t8)
      arr9 << t4
    end
    return arr9
  end

  def self._l(input)
    t9 = input["xs"] || input[:xs]
    arr13 = []
    t9.each_with_index do |xs_el10, xs_i11|
      t12 = xs_el10["v"] || xs_el10[:v]
      t8 = Math.log(t12)
      arr13 << t8
    end
    return arr13
  end

  def self._t(input)
    t13 = input["xs"] || input[:xs]
    arr17 = []
    t13.each_with_index do |xs_el14, xs_i15|
      t16 = xs_el14["v"] || xs_el14[:v]
      t12 = Math.tanh(t16)
      arr17 << t12
    end
    return arr17
  end

  def self._neg(input)
    t19 = input["xs"] || input[:xs]
    arr24 = []
    t19.each_with_index do |xs_el20, xs_i21|
      t22 = 0.0
      t23 = xs_el20["v"] || xs_el20[:v]
      t18 = t22 - t23
      arr24 << t18
    end
    return arr24
  end

  def self._sigmoid(input)
    t33 = input["xs"] || input[:xs]
    arr39 = []
    t33.each_with_index do |xs_el34, xs_i35|
      t36 = 0.0
      t37 = xs_el34["v"] || xs_el34[:v]
      t32 = t36 - t37
      t24 = Math.exp(t32)
      t38 = 1.0
      t25 = t38 + t24
      t26 = t38 / t25.to_f
      arr39 << t26
    end
    return arr39
  end
end
