# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_47622dacfc4573d398a479e75bddc5793da13b50095b7dd04a19342e4ed9ef69
  def self._price(input)
    t3 = input["price_text"] || input[:price_text]
    t2 = t3.is_a?(BigDecimal) ? t3 : BigDecimal(t3.to_s)
    return t2
  end

  def self._rate(input)
    t5 = input["rate_text"] || input[:rate_text]
    t4 = t5.is_a?(BigDecimal) ? t5 : BigDecimal(t5.to_s)
    return t4
  end

  def self._int_times_float(input)
    t8 = input["count"] || input[:count]
    t9 = input["weight"] || input[:weight]
    t7 = t8 * t9
    return t7
  end

  def self._decimal_times_int(input)
    t13 = input["price_text"] || input[:price_text]
    t12 = t13.is_a?(BigDecimal) ? t13 : BigDecimal(t13.to_s)
    t14 = input["count"] || input[:count]
    t10 = t12 * t14
    return t10
  end

  def self._decimal_plus_float(input)
    t16 = input["price_text"] || input[:price_text]
    t15 = t16.is_a?(BigDecimal) ? t16 : BigDecimal(t16.to_s)
    t17 = input["weight"] || input[:weight]
    t13 = t15 + t17
    return t13
  end

  def self._float_plus_int(input)
    t17 = input["weight"] || input[:weight]
    t18 = input["count"] || input[:count]
    t16 = t17 + t18
    return t16
  end

  def self._amount_values(input)
    t21 = input["amounts"] || input[:amounts]
    arr25 = []
    t21.each_with_index do |amounts_el22, amounts_i23|
      t24 = amounts_el22["value"] || amounts_el22[:value]
      t20 = t24.is_a?(BigDecimal) ? t24 : BigDecimal(t24.to_s)
      arr25 << t20
    end
    return arr25
  end

  def self._scaled_amounts(input)
    t31 = input["amounts"] || input[:amounts]
    t35 = input["rate_text"] || input[:rate_text]
    t30 = t35.is_a?(BigDecimal) ? t35 : BigDecimal(t35.to_s)
    arr40 = []
    t31.each_with_index do |amounts_el32, amounts_i33|
      t34 = amounts_el32["value"] || amounts_el32[:value]
      t28 = t34.is_a?(BigDecimal) ? t34 : BigDecimal(t34.to_s)
      t24 = t28 * t30
      arr40 << t24
    end
    return arr40
  end

  def self._total_scaled(input)
    t35 = input["amounts"] || input[:amounts]
    t39 = input["rate_text"] || input[:rate_text]
    t32 = t39.is_a?(BigDecimal) ? t39 : BigDecimal(t39.to_s)
    acc44 = 0
    t35.each_with_index do |amounts_el36, amounts_i37|
      t38 = amounts_el36["value"] || amounts_el36[:value]
      t30 = t38.is_a?(BigDecimal) ? t38 : BigDecimal(t38.to_s)
      t34 = t30 * t32
      acc44 += t34
    end
    t26 = acc44
    return t26
  end

  def self._amount_count(input)
    t29 = input["amounts"] || input[:amounts]
    t28 = t29.length
    return t28
  end
end
