# Autogenerated by Kumi Codegen
module Kumi::Compiled::KUMI_6959cd74bef943cba3465c45be449ee152699a09f30e985e99266e6d175f9226
  def self._price(input)
    t3 = input["unit_price"] || input[:unit_price]
    t2 = t3.is_a?(BigDecimal) ? t3 : BigDecimal(t3.to_s)
    return t2
  end

  def self._rate(input)
    t5 = input["tax_rate"] || input[:tax_rate]
    t4 = t5.is_a?(BigDecimal) ? t5 : BigDecimal(t5.to_s)
    return t4
  end

  def self._subtotal(input)
    t10 = input["unit_price"] || input[:unit_price]
    t9 = t10.is_a?(BigDecimal) ? t10 : BigDecimal(t10.to_s)
    t11 = input["quantity"] || input[:quantity]
    t7 = t9 * t11
    return t7
  end

  def self._tax_amount(input)
    t17 = input["unit_price"] || input[:unit_price]
    t12 = t17.is_a?(BigDecimal) ? t17 : BigDecimal(t17.to_s)
    t18 = input["quantity"] || input[:quantity]
    t14 = t12 * t18
    t19 = input["tax_rate"] || input[:tax_rate]
    t16 = t19.is_a?(BigDecimal) ? t19 : BigDecimal(t19.to_s)
    t10 = t14 * t16
    return t10
  end

  def self._total(input)
    t25 = input["unit_price"] || input[:unit_price]
    t15 = t25.is_a?(BigDecimal) ? t25 : BigDecimal(t25.to_s)
    t26 = input["quantity"] || input[:quantity]
    t17 = t15 * t26
    t27 = input["tax_rate"] || input[:tax_rate]
    t23 = t27.is_a?(BigDecimal) ? t27 : BigDecimal(t27.to_s)
    t24 = t17 * t23
    t13 = t17 + t24
    return t13
  end
end
